// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ClbEventStatus string

const (
	ClbEventStatusPending    ClbEventStatus = "pending"
	ClbEventStatusProcessing ClbEventStatus = "processing"
	ClbEventStatusOk         ClbEventStatus = "ok"
	ClbEventStatusReject     ClbEventStatus = "reject"
)

func (e *ClbEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClbEventStatus(s)
	case string:
		*e = ClbEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClbEventStatus: %T", src)
	}
	return nil
}

type NullClbEventStatus struct {
	ClbEventStatus ClbEventStatus `json:"clb_event_status"`
	Valid          bool           `json:"valid"` // Valid is true if ClbEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClbEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClbEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClbEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClbEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClbEventStatus), nil
}

type ClbEvent struct {
	ID                 uint64         `json:"id"`
	SourceService      string         `json:"source_service"`
	EventType          string         `json:"event_type"`
	EventKey           string         `json:"event_key"`
	IdempotencyKey     string         `json:"idempotency_key"`
	Payload            []byte         `json:"payload"`
	PayloadContentType string         `json:"payload_content_type"`
	Status             ClbEventStatus `json:"status"`
	AttemptCount       uint32         `json:"attempt_count"`
	NextAttemptAt      time.Time      `json:"next_attempt_at"`
	LockedBy           sql.NullString `json:"locked_by"`
	LockedUntil        sql.NullTime   `json:"locked_until"`
	DeliveredAt        sql.NullTime   `json:"delivered_at"`
	RejectedAt         sql.NullTime   `json:"rejected_at"`
	LastError          sql.NullString `json:"last_error"`
	RejectReason       sql.NullString `json:"reject_reason"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}
