// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adminCreateTaskStmt, err = db.PrepareContext(ctx, adminCreateTask); err != nil {
		return nil, fmt.Errorf("error preparing query AdminCreateTask: %w", err)
	}
	if q.adminDeletePartnerRewardRuleStmt, err = db.PrepareContext(ctx, adminDeletePartnerRewardRule); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeletePartnerRewardRule: %w", err)
	}
	if q.adminDeleteRewardStmt, err = db.PrepareContext(ctx, adminDeleteReward); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteReward: %w", err)
	}
	if q.adminDeleteTaskStmt, err = db.PrepareContext(ctx, adminDeleteTask); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteTask: %w", err)
	}
	if q.adminGetPartnerConfigStmt, err = db.PrepareContext(ctx, adminGetPartnerConfig); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetPartnerConfig: %w", err)
	}
	if q.adminGetSingleTaskStatsStmt, err = db.PrepareContext(ctx, adminGetSingleTaskStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetSingleTaskStats: %w", err)
	}
	if q.adminGetTaskStmt, err = db.PrepareContext(ctx, adminGetTask); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetTask: %w", err)
	}
	if q.adminGetTaskStatsStmt, err = db.PrepareContext(ctx, adminGetTaskStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetTaskStats: %w", err)
	}
	if q.adminListPartnerConfigsStmt, err = db.PrepareContext(ctx, adminListPartnerConfigs); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListPartnerConfigs: %w", err)
	}
	if q.adminListPartnerDailyStatsStmt, err = db.PrepareContext(ctx, adminListPartnerDailyStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListPartnerDailyStats: %w", err)
	}
	if q.adminListTaskDailyOverviewStmt, err = db.PrepareContext(ctx, adminListTaskDailyOverview); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListTaskDailyOverview: %w", err)
	}
	if q.adminListTaskDailyStatsStmt, err = db.PrepareContext(ctx, adminListTaskDailyStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListTaskDailyStats: %w", err)
	}
	if q.adminListTasksStmt, err = db.PrepareContext(ctx, adminListTasks); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListTasks: %w", err)
	}
	if q.adminListTasksByGroupStmt, err = db.PrepareContext(ctx, adminListTasksByGroup); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListTasksByGroup: %w", err)
	}
	if q.adminUpdateTaskStmt, err = db.PrepareContext(ctx, adminUpdateTask); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpdateTask: %w", err)
	}
	if q.adminUpsertGroupStmt, err = db.PrepareContext(ctx, adminUpsertGroup); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertGroup: %w", err)
	}
	if q.adminUpsertGroupLocalizationStmt, err = db.PrepareContext(ctx, adminUpsertGroupLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertGroupLocalization: %w", err)
	}
	if q.adminUpsertPartnerConfigStmt, err = db.PrepareContext(ctx, adminUpsertPartnerConfig); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertPartnerConfig: %w", err)
	}
	if q.adminUpsertPartnerRewardRuleStmt, err = db.PrepareContext(ctx, adminUpsertPartnerRewardRule); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertPartnerRewardRule: %w", err)
	}
	if q.adminUpsertRewardStmt, err = db.PrepareContext(ctx, adminUpsertReward); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertReward: %w", err)
	}
	if q.adminUpsertSequenceStmt, err = db.PrepareContext(ctx, adminUpsertSequence); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertSequence: %w", err)
	}
	if q.adminUpsertTaskLocalizationStmt, err = db.PrepareContext(ctx, adminUpsertTaskLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertTaskLocalization: %w", err)
	}
	if q.claimPartnerIssueStmt, err = db.PrepareContext(ctx, claimPartnerIssue); err != nil {
		return nil, fmt.Errorf("error preparing query ClaimPartnerIssue: %w", err)
	}
	if q.completePartnerIssueStmt, err = db.PrepareContext(ctx, completePartnerIssue); err != nil {
		return nil, fmt.Errorf("error preparing query CompletePartnerIssue: %w", err)
	}
	if q.countProgressEventsByExternalKeyStmt, err = db.PrepareContext(ctx, countProgressEventsByExternalKey); err != nil {
		return nil, fmt.Errorf("error preparing query CountProgressEventsByExternalKey: %w", err)
	}
	if q.createPartnerIssueStmt, err = db.PrepareContext(ctx, createPartnerIssue); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePartnerIssue: %w", err)
	}
	if q.ensureProgressStmt, err = db.PrepareContext(ctx, ensureProgress); err != nil {
		return nil, fmt.Errorf("error preparing query EnsureProgress: %w", err)
	}
	if q.getClaimBundleByIDForUpdateStmt, err = db.PrepareContext(ctx, getClaimBundleByIDForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetClaimBundleByIDForUpdate: %w", err)
	}
	if q.getClaimBundleByKeyForUpdateStmt, err = db.PrepareContext(ctx, getClaimBundleByKeyForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetClaimBundleByKeyForUpdate: %w", err)
	}
	if q.getClaimCatalogByIDStmt, err = db.PrepareContext(ctx, getClaimCatalogByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetClaimCatalogByID: %w", err)
	}
	if q.getClaimCatalogByKeyStmt, err = db.PrepareContext(ctx, getClaimCatalogByKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetClaimCatalogByKey: %w", err)
	}
	if q.getCurrentProgressForUpdateStmt, err = db.PrepareContext(ctx, getCurrentProgressForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetCurrentProgressForUpdate: %w", err)
	}
	if q.getIntegrationCheckTaskByIDStmt, err = db.PrepareContext(ctx, getIntegrationCheckTaskByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetIntegrationCheckTaskByID: %w", err)
	}
	if q.getIntegrationCheckTaskByKeyStmt, err = db.PrepareContext(ctx, getIntegrationCheckTaskByKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetIntegrationCheckTaskByKey: %w", err)
	}
	if q.getNextSequenceTaskIDStmt, err = db.PrepareContext(ctx, getNextSequenceTaskID); err != nil {
		return nil, fmt.Errorf("error preparing query GetNextSequenceTaskID: %w", err)
	}
	if q.getPartnerIssueByIDStmt, err = db.PrepareContext(ctx, getPartnerIssueByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPartnerIssueByID: %w", err)
	}
	if q.getPartnerIssueByIDForUpdateStmt, err = db.PrepareContext(ctx, getPartnerIssueByIDForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetPartnerIssueByIDForUpdate: %w", err)
	}
	if q.getSequenceStateForUpdateStmt, err = db.PrepareContext(ctx, getSequenceStateForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetSequenceStateForUpdate: %w", err)
	}
	if q.incrementPartnerStatsDailyStmt, err = db.PrepareContext(ctx, incrementPartnerStatsDaily); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementPartnerStatsDaily: %w", err)
	}
	if q.insertPartnerRewardGrantStmt, err = db.PrepareContext(ctx, insertPartnerRewardGrant); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPartnerRewardGrant: %w", err)
	}
	if q.insertPartnerStatsEventStmt, err = db.PrepareContext(ctx, insertPartnerStatsEvent); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPartnerStatsEvent: %w", err)
	}
	if q.insertPartnerStatsUniqueUserStmt, err = db.PrepareContext(ctx, insertPartnerStatsUniqueUser); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPartnerStatsUniqueUser: %w", err)
	}
	if q.insertProgressEventStmt, err = db.PrepareContext(ctx, insertProgressEvent); err != nil {
		return nil, fmt.Errorf("error preparing query InsertProgressEvent: %w", err)
	}
	if q.listActiveTaskBundlesStmt, err = db.PrepareContext(ctx, listActiveTaskBundles); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveTaskBundles: %w", err)
	}
	if q.listCurrentProgressForUserStmt, err = db.PrepareContext(ctx, listCurrentProgressForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListCurrentProgressForUser: %w", err)
	}
	if q.listCurrentProgressForUserForUpdateStmt, err = db.PrepareContext(ctx, listCurrentProgressForUserForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query ListCurrentProgressForUserForUpdate: %w", err)
	}
	if q.listPartnerIssuesForUserStmt, err = db.PrepareContext(ctx, listPartnerIssuesForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListPartnerIssuesForUser: %w", err)
	}
	if q.listPartnerRewardRulesStmt, err = db.PrepareContext(ctx, listPartnerRewardRules); err != nil {
		return nil, fmt.Errorf("error preparing query ListPartnerRewardRules: %w", err)
	}
	if q.listRecordCatalogStmt, err = db.PrepareContext(ctx, listRecordCatalog); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecordCatalog: %w", err)
	}
	if q.listRecordTasksStmt, err = db.PrepareContext(ctx, listRecordTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecordTasks: %w", err)
	}
	if q.listRewardsStmt, err = db.PrepareContext(ctx, listRewards); err != nil {
		return nil, fmt.Errorf("error preparing query ListRewards: %w", err)
	}
	if q.listRewardsCatalogStmt, err = db.PrepareContext(ctx, listRewardsCatalog); err != nil {
		return nil, fmt.Errorf("error preparing query ListRewardsCatalog: %w", err)
	}
	if q.listSequenceStatesForUserStmt, err = db.PrepareContext(ctx, listSequenceStatesForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListSequenceStatesForUser: %w", err)
	}
	if q.refreshTaskDailyOverviewStmt, err = db.PrepareContext(ctx, refreshTaskDailyOverview); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshTaskDailyOverview: %w", err)
	}
	if q.refreshTaskDailyStatsStmt, err = db.PrepareContext(ctx, refreshTaskDailyStats); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshTaskDailyStats: %w", err)
	}
	if q.updateProgressStmt, err = db.PrepareContext(ctx, updateProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProgress: %w", err)
	}
	if q.upsertProgressStmt, err = db.PrepareContext(ctx, upsertProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertProgress: %w", err)
	}
	if q.upsertSequenceStateStmt, err = db.PrepareContext(ctx, upsertSequenceState); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSequenceState: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adminCreateTaskStmt != nil {
		if cerr := q.adminCreateTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminCreateTaskStmt: %w", cerr)
		}
	}
	if q.adminDeletePartnerRewardRuleStmt != nil {
		if cerr := q.adminDeletePartnerRewardRuleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeletePartnerRewardRuleStmt: %w", cerr)
		}
	}
	if q.adminDeleteRewardStmt != nil {
		if cerr := q.adminDeleteRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteRewardStmt: %w", cerr)
		}
	}
	if q.adminDeleteTaskStmt != nil {
		if cerr := q.adminDeleteTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteTaskStmt: %w", cerr)
		}
	}
	if q.adminGetPartnerConfigStmt != nil {
		if cerr := q.adminGetPartnerConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetPartnerConfigStmt: %w", cerr)
		}
	}
	if q.adminGetSingleTaskStatsStmt != nil {
		if cerr := q.adminGetSingleTaskStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetSingleTaskStatsStmt: %w", cerr)
		}
	}
	if q.adminGetTaskStmt != nil {
		if cerr := q.adminGetTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetTaskStmt: %w", cerr)
		}
	}
	if q.adminGetTaskStatsStmt != nil {
		if cerr := q.adminGetTaskStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetTaskStatsStmt: %w", cerr)
		}
	}
	if q.adminListPartnerConfigsStmt != nil {
		if cerr := q.adminListPartnerConfigsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListPartnerConfigsStmt: %w", cerr)
		}
	}
	if q.adminListPartnerDailyStatsStmt != nil {
		if cerr := q.adminListPartnerDailyStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListPartnerDailyStatsStmt: %w", cerr)
		}
	}
	if q.adminListTaskDailyOverviewStmt != nil {
		if cerr := q.adminListTaskDailyOverviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListTaskDailyOverviewStmt: %w", cerr)
		}
	}
	if q.adminListTaskDailyStatsStmt != nil {
		if cerr := q.adminListTaskDailyStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListTaskDailyStatsStmt: %w", cerr)
		}
	}
	if q.adminListTasksStmt != nil {
		if cerr := q.adminListTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListTasksStmt: %w", cerr)
		}
	}
	if q.adminListTasksByGroupStmt != nil {
		if cerr := q.adminListTasksByGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListTasksByGroupStmt: %w", cerr)
		}
	}
	if q.adminUpdateTaskStmt != nil {
		if cerr := q.adminUpdateTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpdateTaskStmt: %w", cerr)
		}
	}
	if q.adminUpsertGroupStmt != nil {
		if cerr := q.adminUpsertGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertGroupStmt: %w", cerr)
		}
	}
	if q.adminUpsertGroupLocalizationStmt != nil {
		if cerr := q.adminUpsertGroupLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertGroupLocalizationStmt: %w", cerr)
		}
	}
	if q.adminUpsertPartnerConfigStmt != nil {
		if cerr := q.adminUpsertPartnerConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertPartnerConfigStmt: %w", cerr)
		}
	}
	if q.adminUpsertPartnerRewardRuleStmt != nil {
		if cerr := q.adminUpsertPartnerRewardRuleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertPartnerRewardRuleStmt: %w", cerr)
		}
	}
	if q.adminUpsertRewardStmt != nil {
		if cerr := q.adminUpsertRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertRewardStmt: %w", cerr)
		}
	}
	if q.adminUpsertSequenceStmt != nil {
		if cerr := q.adminUpsertSequenceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertSequenceStmt: %w", cerr)
		}
	}
	if q.adminUpsertTaskLocalizationStmt != nil {
		if cerr := q.adminUpsertTaskLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertTaskLocalizationStmt: %w", cerr)
		}
	}
	if q.claimPartnerIssueStmt != nil {
		if cerr := q.claimPartnerIssueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing claimPartnerIssueStmt: %w", cerr)
		}
	}
	if q.completePartnerIssueStmt != nil {
		if cerr := q.completePartnerIssueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completePartnerIssueStmt: %w", cerr)
		}
	}
	if q.countProgressEventsByExternalKeyStmt != nil {
		if cerr := q.countProgressEventsByExternalKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProgressEventsByExternalKeyStmt: %w", cerr)
		}
	}
	if q.createPartnerIssueStmt != nil {
		if cerr := q.createPartnerIssueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPartnerIssueStmt: %w", cerr)
		}
	}
	if q.ensureProgressStmt != nil {
		if cerr := q.ensureProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ensureProgressStmt: %w", cerr)
		}
	}
	if q.getClaimBundleByIDForUpdateStmt != nil {
		if cerr := q.getClaimBundleByIDForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClaimBundleByIDForUpdateStmt: %w", cerr)
		}
	}
	if q.getClaimBundleByKeyForUpdateStmt != nil {
		if cerr := q.getClaimBundleByKeyForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClaimBundleByKeyForUpdateStmt: %w", cerr)
		}
	}
	if q.getClaimCatalogByIDStmt != nil {
		if cerr := q.getClaimCatalogByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClaimCatalogByIDStmt: %w", cerr)
		}
	}
	if q.getClaimCatalogByKeyStmt != nil {
		if cerr := q.getClaimCatalogByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClaimCatalogByKeyStmt: %w", cerr)
		}
	}
	if q.getCurrentProgressForUpdateStmt != nil {
		if cerr := q.getCurrentProgressForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCurrentProgressForUpdateStmt: %w", cerr)
		}
	}
	if q.getIntegrationCheckTaskByIDStmt != nil {
		if cerr := q.getIntegrationCheckTaskByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIntegrationCheckTaskByIDStmt: %w", cerr)
		}
	}
	if q.getIntegrationCheckTaskByKeyStmt != nil {
		if cerr := q.getIntegrationCheckTaskByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIntegrationCheckTaskByKeyStmt: %w", cerr)
		}
	}
	if q.getNextSequenceTaskIDStmt != nil {
		if cerr := q.getNextSequenceTaskIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNextSequenceTaskIDStmt: %w", cerr)
		}
	}
	if q.getPartnerIssueByIDStmt != nil {
		if cerr := q.getPartnerIssueByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartnerIssueByIDStmt: %w", cerr)
		}
	}
	if q.getPartnerIssueByIDForUpdateStmt != nil {
		if cerr := q.getPartnerIssueByIDForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartnerIssueByIDForUpdateStmt: %w", cerr)
		}
	}
	if q.getSequenceStateForUpdateStmt != nil {
		if cerr := q.getSequenceStateForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSequenceStateForUpdateStmt: %w", cerr)
		}
	}
	if q.incrementPartnerStatsDailyStmt != nil {
		if cerr := q.incrementPartnerStatsDailyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementPartnerStatsDailyStmt: %w", cerr)
		}
	}
	if q.insertPartnerRewardGrantStmt != nil {
		if cerr := q.insertPartnerRewardGrantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPartnerRewardGrantStmt: %w", cerr)
		}
	}
	if q.insertPartnerStatsEventStmt != nil {
		if cerr := q.insertPartnerStatsEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPartnerStatsEventStmt: %w", cerr)
		}
	}
	if q.insertPartnerStatsUniqueUserStmt != nil {
		if cerr := q.insertPartnerStatsUniqueUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPartnerStatsUniqueUserStmt: %w", cerr)
		}
	}
	if q.insertProgressEventStmt != nil {
		if cerr := q.insertProgressEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertProgressEventStmt: %w", cerr)
		}
	}
	if q.listActiveTaskBundlesStmt != nil {
		if cerr := q.listActiveTaskBundlesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveTaskBundlesStmt: %w", cerr)
		}
	}
	if q.listCurrentProgressForUserStmt != nil {
		if cerr := q.listCurrentProgressForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCurrentProgressForUserStmt: %w", cerr)
		}
	}
	if q.listCurrentProgressForUserForUpdateStmt != nil {
		if cerr := q.listCurrentProgressForUserForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCurrentProgressForUserForUpdateStmt: %w", cerr)
		}
	}
	if q.listPartnerIssuesForUserStmt != nil {
		if cerr := q.listPartnerIssuesForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPartnerIssuesForUserStmt: %w", cerr)
		}
	}
	if q.listPartnerRewardRulesStmt != nil {
		if cerr := q.listPartnerRewardRulesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPartnerRewardRulesStmt: %w", cerr)
		}
	}
	if q.listRecordCatalogStmt != nil {
		if cerr := q.listRecordCatalogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecordCatalogStmt: %w", cerr)
		}
	}
	if q.listRecordTasksStmt != nil {
		if cerr := q.listRecordTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecordTasksStmt: %w", cerr)
		}
	}
	if q.listRewardsStmt != nil {
		if cerr := q.listRewardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRewardsStmt: %w", cerr)
		}
	}
	if q.listRewardsCatalogStmt != nil {
		if cerr := q.listRewardsCatalogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRewardsCatalogStmt: %w", cerr)
		}
	}
	if q.listSequenceStatesForUserStmt != nil {
		if cerr := q.listSequenceStatesForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSequenceStatesForUserStmt: %w", cerr)
		}
	}
	if q.refreshTaskDailyOverviewStmt != nil {
		if cerr := q.refreshTaskDailyOverviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshTaskDailyOverviewStmt: %w", cerr)
		}
	}
	if q.refreshTaskDailyStatsStmt != nil {
		if cerr := q.refreshTaskDailyStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshTaskDailyStatsStmt: %w", cerr)
		}
	}
	if q.updateProgressStmt != nil {
		if cerr := q.updateProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProgressStmt: %w", cerr)
		}
	}
	if q.upsertProgressStmt != nil {
		if cerr := q.upsertProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertProgressStmt: %w", cerr)
		}
	}
	if q.upsertSequenceStateStmt != nil {
		if cerr := q.upsertSequenceStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSequenceStateStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                      DBTX
	tx                                      *sql.Tx
	adminCreateTaskStmt                     *sql.Stmt
	adminDeletePartnerRewardRuleStmt        *sql.Stmt
	adminDeleteRewardStmt                   *sql.Stmt
	adminDeleteTaskStmt                     *sql.Stmt
	adminGetPartnerConfigStmt               *sql.Stmt
	adminGetSingleTaskStatsStmt             *sql.Stmt
	adminGetTaskStmt                        *sql.Stmt
	adminGetTaskStatsStmt                   *sql.Stmt
	adminListPartnerConfigsStmt             *sql.Stmt
	adminListPartnerDailyStatsStmt          *sql.Stmt
	adminListTaskDailyOverviewStmt          *sql.Stmt
	adminListTaskDailyStatsStmt             *sql.Stmt
	adminListTasksStmt                      *sql.Stmt
	adminListTasksByGroupStmt               *sql.Stmt
	adminUpdateTaskStmt                     *sql.Stmt
	adminUpsertGroupStmt                    *sql.Stmt
	adminUpsertGroupLocalizationStmt        *sql.Stmt
	adminUpsertPartnerConfigStmt            *sql.Stmt
	adminUpsertPartnerRewardRuleStmt        *sql.Stmt
	adminUpsertRewardStmt                   *sql.Stmt
	adminUpsertSequenceStmt                 *sql.Stmt
	adminUpsertTaskLocalizationStmt         *sql.Stmt
	claimPartnerIssueStmt                   *sql.Stmt
	completePartnerIssueStmt                *sql.Stmt
	countProgressEventsByExternalKeyStmt    *sql.Stmt
	createPartnerIssueStmt                  *sql.Stmt
	ensureProgressStmt                      *sql.Stmt
	getClaimBundleByIDForUpdateStmt         *sql.Stmt
	getClaimBundleByKeyForUpdateStmt        *sql.Stmt
	getClaimCatalogByIDStmt                 *sql.Stmt
	getClaimCatalogByKeyStmt                *sql.Stmt
	getCurrentProgressForUpdateStmt         *sql.Stmt
	getIntegrationCheckTaskByIDStmt         *sql.Stmt
	getIntegrationCheckTaskByKeyStmt        *sql.Stmt
	getNextSequenceTaskIDStmt               *sql.Stmt
	getPartnerIssueByIDStmt                 *sql.Stmt
	getPartnerIssueByIDForUpdateStmt        *sql.Stmt
	getSequenceStateForUpdateStmt           *sql.Stmt
	incrementPartnerStatsDailyStmt          *sql.Stmt
	insertPartnerRewardGrantStmt            *sql.Stmt
	insertPartnerStatsEventStmt             *sql.Stmt
	insertPartnerStatsUniqueUserStmt        *sql.Stmt
	insertProgressEventStmt                 *sql.Stmt
	listActiveTaskBundlesStmt               *sql.Stmt
	listCurrentProgressForUserStmt          *sql.Stmt
	listCurrentProgressForUserForUpdateStmt *sql.Stmt
	listPartnerIssuesForUserStmt            *sql.Stmt
	listPartnerRewardRulesStmt              *sql.Stmt
	listRecordCatalogStmt                   *sql.Stmt
	listRecordTasksStmt                     *sql.Stmt
	listRewardsStmt                         *sql.Stmt
	listRewardsCatalogStmt                  *sql.Stmt
	listSequenceStatesForUserStmt           *sql.Stmt
	refreshTaskDailyOverviewStmt            *sql.Stmt
	refreshTaskDailyStatsStmt               *sql.Stmt
	updateProgressStmt                      *sql.Stmt
	upsertProgressStmt                      *sql.Stmt
	upsertSequenceStateStmt                 *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                      tx,
		tx:                                      tx,
		adminCreateTaskStmt:                     q.adminCreateTaskStmt,
		adminDeletePartnerRewardRuleStmt:        q.adminDeletePartnerRewardRuleStmt,
		adminDeleteRewardStmt:                   q.adminDeleteRewardStmt,
		adminDeleteTaskStmt:                     q.adminDeleteTaskStmt,
		adminGetPartnerConfigStmt:               q.adminGetPartnerConfigStmt,
		adminGetSingleTaskStatsStmt:             q.adminGetSingleTaskStatsStmt,
		adminGetTaskStmt:                        q.adminGetTaskStmt,
		adminGetTaskStatsStmt:                   q.adminGetTaskStatsStmt,
		adminListPartnerConfigsStmt:             q.adminListPartnerConfigsStmt,
		adminListPartnerDailyStatsStmt:          q.adminListPartnerDailyStatsStmt,
		adminListTaskDailyOverviewStmt:          q.adminListTaskDailyOverviewStmt,
		adminListTaskDailyStatsStmt:             q.adminListTaskDailyStatsStmt,
		adminListTasksStmt:                      q.adminListTasksStmt,
		adminListTasksByGroupStmt:               q.adminListTasksByGroupStmt,
		adminUpdateTaskStmt:                     q.adminUpdateTaskStmt,
		adminUpsertGroupStmt:                    q.adminUpsertGroupStmt,
		adminUpsertGroupLocalizationStmt:        q.adminUpsertGroupLocalizationStmt,
		adminUpsertPartnerConfigStmt:            q.adminUpsertPartnerConfigStmt,
		adminUpsertPartnerRewardRuleStmt:        q.adminUpsertPartnerRewardRuleStmt,
		adminUpsertRewardStmt:                   q.adminUpsertRewardStmt,
		adminUpsertSequenceStmt:                 q.adminUpsertSequenceStmt,
		adminUpsertTaskLocalizationStmt:         q.adminUpsertTaskLocalizationStmt,
		claimPartnerIssueStmt:                   q.claimPartnerIssueStmt,
		completePartnerIssueStmt:                q.completePartnerIssueStmt,
		countProgressEventsByExternalKeyStmt:    q.countProgressEventsByExternalKeyStmt,
		createPartnerIssueStmt:                  q.createPartnerIssueStmt,
		ensureProgressStmt:                      q.ensureProgressStmt,
		getClaimBundleByIDForUpdateStmt:         q.getClaimBundleByIDForUpdateStmt,
		getClaimBundleByKeyForUpdateStmt:        q.getClaimBundleByKeyForUpdateStmt,
		getClaimCatalogByIDStmt:                 q.getClaimCatalogByIDStmt,
		getClaimCatalogByKeyStmt:                q.getClaimCatalogByKeyStmt,
		getCurrentProgressForUpdateStmt:         q.getCurrentProgressForUpdateStmt,
		getIntegrationCheckTaskByIDStmt:         q.getIntegrationCheckTaskByIDStmt,
		getIntegrationCheckTaskByKeyStmt:        q.getIntegrationCheckTaskByKeyStmt,
		getNextSequenceTaskIDStmt:               q.getNextSequenceTaskIDStmt,
		getPartnerIssueByIDStmt:                 q.getPartnerIssueByIDStmt,
		getPartnerIssueByIDForUpdateStmt:        q.getPartnerIssueByIDForUpdateStmt,
		getSequenceStateForUpdateStmt:           q.getSequenceStateForUpdateStmt,
		incrementPartnerStatsDailyStmt:          q.incrementPartnerStatsDailyStmt,
		insertPartnerRewardGrantStmt:            q.insertPartnerRewardGrantStmt,
		insertPartnerStatsEventStmt:             q.insertPartnerStatsEventStmt,
		insertPartnerStatsUniqueUserStmt:        q.insertPartnerStatsUniqueUserStmt,
		insertProgressEventStmt:                 q.insertProgressEventStmt,
		listActiveTaskBundlesStmt:               q.listActiveTaskBundlesStmt,
		listCurrentProgressForUserStmt:          q.listCurrentProgressForUserStmt,
		listCurrentProgressForUserForUpdateStmt: q.listCurrentProgressForUserForUpdateStmt,
		listPartnerIssuesForUserStmt:            q.listPartnerIssuesForUserStmt,
		listPartnerRewardRulesStmt:              q.listPartnerRewardRulesStmt,
		listRecordCatalogStmt:                   q.listRecordCatalogStmt,
		listRecordTasksStmt:                     q.listRecordTasksStmt,
		listRewardsStmt:                         q.listRewardsStmt,
		listRewardsCatalogStmt:                  q.listRewardsCatalogStmt,
		listSequenceStatesForUserStmt:           q.listSequenceStatesForUserStmt,
		refreshTaskDailyOverviewStmt:            q.refreshTaskDailyOverviewStmt,
		refreshTaskDailyStatsStmt:               q.refreshTaskDailyStatsStmt,
		updateProgressStmt:                      q.updateProgressStmt,
		upsertProgressStmt:                      q.upsertProgressStmt,
		upsertSequenceStateStmt:                 q.upsertSequenceStateStmt,
	}
}
