// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adminCreateTaskStmt, err = db.PrepareContext(ctx, adminCreateTask); err != nil {
		return nil, fmt.Errorf("error preparing query AdminCreateTask: %w", err)
	}
	if q.adminDeleteRewardStmt, err = db.PrepareContext(ctx, adminDeleteReward); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteReward: %w", err)
	}
	if q.adminDeleteTaskStmt, err = db.PrepareContext(ctx, adminDeleteTask); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteTask: %w", err)
	}
	if q.adminGetSingleTaskStatsStmt, err = db.PrepareContext(ctx, adminGetSingleTaskStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetSingleTaskStats: %w", err)
	}
	if q.adminGetTaskStmt, err = db.PrepareContext(ctx, adminGetTask); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetTask: %w", err)
	}
	if q.adminGetTaskStatsStmt, err = db.PrepareContext(ctx, adminGetTaskStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetTaskStats: %w", err)
	}
	if q.adminListTaskDailyOverviewStmt, err = db.PrepareContext(ctx, adminListTaskDailyOverview); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListTaskDailyOverview: %w", err)
	}
	if q.adminListTaskDailyStatsStmt, err = db.PrepareContext(ctx, adminListTaskDailyStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListTaskDailyStats: %w", err)
	}
	if q.adminListTasksStmt, err = db.PrepareContext(ctx, adminListTasks); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListTasks: %w", err)
	}
	if q.adminListTasksByGroupStmt, err = db.PrepareContext(ctx, adminListTasksByGroup); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListTasksByGroup: %w", err)
	}
	if q.adminUpdateTaskStmt, err = db.PrepareContext(ctx, adminUpdateTask); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpdateTask: %w", err)
	}
	if q.adminUpsertGroupStmt, err = db.PrepareContext(ctx, adminUpsertGroup); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertGroup: %w", err)
	}
	if q.adminUpsertGroupLocalizationStmt, err = db.PrepareContext(ctx, adminUpsertGroupLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertGroupLocalization: %w", err)
	}
	if q.adminUpsertRewardStmt, err = db.PrepareContext(ctx, adminUpsertReward); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertReward: %w", err)
	}
	if q.adminUpsertSequenceStmt, err = db.PrepareContext(ctx, adminUpsertSequence); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertSequence: %w", err)
	}
	if q.adminUpsertTaskLocalizationStmt, err = db.PrepareContext(ctx, adminUpsertTaskLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertTaskLocalization: %w", err)
	}
	if q.countProgressEventsByExternalKeyStmt, err = db.PrepareContext(ctx, countProgressEventsByExternalKey); err != nil {
		return nil, fmt.Errorf("error preparing query CountProgressEventsByExternalKey: %w", err)
	}
	if q.ensureProgressStmt, err = db.PrepareContext(ctx, ensureProgress); err != nil {
		return nil, fmt.Errorf("error preparing query EnsureProgress: %w", err)
	}
	if q.getClaimBundleByIDForUpdateStmt, err = db.PrepareContext(ctx, getClaimBundleByIDForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetClaimBundleByIDForUpdate: %w", err)
	}
	if q.getClaimBundleByKeyForUpdateStmt, err = db.PrepareContext(ctx, getClaimBundleByKeyForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetClaimBundleByKeyForUpdate: %w", err)
	}
	if q.getNextSequenceTaskIDStmt, err = db.PrepareContext(ctx, getNextSequenceTaskID); err != nil {
		return nil, fmt.Errorf("error preparing query GetNextSequenceTaskID: %w", err)
	}
	if q.insertProgressEventStmt, err = db.PrepareContext(ctx, insertProgressEvent); err != nil {
		return nil, fmt.Errorf("error preparing query InsertProgressEvent: %w", err)
	}
	if q.listActiveTaskBundlesStmt, err = db.PrepareContext(ctx, listActiveTaskBundles); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveTaskBundles: %w", err)
	}
	if q.listCurrentProgressForUserStmt, err = db.PrepareContext(ctx, listCurrentProgressForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListCurrentProgressForUser: %w", err)
	}
	if q.listCurrentProgressForUserForUpdateStmt, err = db.PrepareContext(ctx, listCurrentProgressForUserForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query ListCurrentProgressForUserForUpdate: %w", err)
	}
	if q.listRecordTasksStmt, err = db.PrepareContext(ctx, listRecordTasks); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecordTasks: %w", err)
	}
	if q.listRewardsStmt, err = db.PrepareContext(ctx, listRewards); err != nil {
		return nil, fmt.Errorf("error preparing query ListRewards: %w", err)
	}
	if q.refreshTaskDailyOverviewStmt, err = db.PrepareContext(ctx, refreshTaskDailyOverview); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshTaskDailyOverview: %w", err)
	}
	if q.refreshTaskDailyStatsStmt, err = db.PrepareContext(ctx, refreshTaskDailyStats); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshTaskDailyStats: %w", err)
	}
	if q.updateProgressStmt, err = db.PrepareContext(ctx, updateProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProgress: %w", err)
	}
	if q.upsertSequenceStateStmt, err = db.PrepareContext(ctx, upsertSequenceState); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSequenceState: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adminCreateTaskStmt != nil {
		if cerr := q.adminCreateTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminCreateTaskStmt: %w", cerr)
		}
	}
	if q.adminDeleteRewardStmt != nil {
		if cerr := q.adminDeleteRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteRewardStmt: %w", cerr)
		}
	}
	if q.adminDeleteTaskStmt != nil {
		if cerr := q.adminDeleteTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteTaskStmt: %w", cerr)
		}
	}
	if q.adminGetSingleTaskStatsStmt != nil {
		if cerr := q.adminGetSingleTaskStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetSingleTaskStatsStmt: %w", cerr)
		}
	}
	if q.adminGetTaskStmt != nil {
		if cerr := q.adminGetTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetTaskStmt: %w", cerr)
		}
	}
	if q.adminGetTaskStatsStmt != nil {
		if cerr := q.adminGetTaskStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetTaskStatsStmt: %w", cerr)
		}
	}
	if q.adminListTaskDailyOverviewStmt != nil {
		if cerr := q.adminListTaskDailyOverviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListTaskDailyOverviewStmt: %w", cerr)
		}
	}
	if q.adminListTaskDailyStatsStmt != nil {
		if cerr := q.adminListTaskDailyStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListTaskDailyStatsStmt: %w", cerr)
		}
	}
	if q.adminListTasksStmt != nil {
		if cerr := q.adminListTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListTasksStmt: %w", cerr)
		}
	}
	if q.adminListTasksByGroupStmt != nil {
		if cerr := q.adminListTasksByGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListTasksByGroupStmt: %w", cerr)
		}
	}
	if q.adminUpdateTaskStmt != nil {
		if cerr := q.adminUpdateTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpdateTaskStmt: %w", cerr)
		}
	}
	if q.adminUpsertGroupStmt != nil {
		if cerr := q.adminUpsertGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertGroupStmt: %w", cerr)
		}
	}
	if q.adminUpsertGroupLocalizationStmt != nil {
		if cerr := q.adminUpsertGroupLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertGroupLocalizationStmt: %w", cerr)
		}
	}
	if q.adminUpsertRewardStmt != nil {
		if cerr := q.adminUpsertRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertRewardStmt: %w", cerr)
		}
	}
	if q.adminUpsertSequenceStmt != nil {
		if cerr := q.adminUpsertSequenceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertSequenceStmt: %w", cerr)
		}
	}
	if q.adminUpsertTaskLocalizationStmt != nil {
		if cerr := q.adminUpsertTaskLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertTaskLocalizationStmt: %w", cerr)
		}
	}
	if q.countProgressEventsByExternalKeyStmt != nil {
		if cerr := q.countProgressEventsByExternalKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProgressEventsByExternalKeyStmt: %w", cerr)
		}
	}
	if q.ensureProgressStmt != nil {
		if cerr := q.ensureProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ensureProgressStmt: %w", cerr)
		}
	}
	if q.getClaimBundleByIDForUpdateStmt != nil {
		if cerr := q.getClaimBundleByIDForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClaimBundleByIDForUpdateStmt: %w", cerr)
		}
	}
	if q.getClaimBundleByKeyForUpdateStmt != nil {
		if cerr := q.getClaimBundleByKeyForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClaimBundleByKeyForUpdateStmt: %w", cerr)
		}
	}
	if q.getNextSequenceTaskIDStmt != nil {
		if cerr := q.getNextSequenceTaskIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNextSequenceTaskIDStmt: %w", cerr)
		}
	}
	if q.insertProgressEventStmt != nil {
		if cerr := q.insertProgressEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertProgressEventStmt: %w", cerr)
		}
	}
	if q.listActiveTaskBundlesStmt != nil {
		if cerr := q.listActiveTaskBundlesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveTaskBundlesStmt: %w", cerr)
		}
	}
	if q.listCurrentProgressForUserStmt != nil {
		if cerr := q.listCurrentProgressForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCurrentProgressForUserStmt: %w", cerr)
		}
	}
	if q.listCurrentProgressForUserForUpdateStmt != nil {
		if cerr := q.listCurrentProgressForUserForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCurrentProgressForUserForUpdateStmt: %w", cerr)
		}
	}
	if q.listRecordTasksStmt != nil {
		if cerr := q.listRecordTasksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecordTasksStmt: %w", cerr)
		}
	}
	if q.listRewardsStmt != nil {
		if cerr := q.listRewardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRewardsStmt: %w", cerr)
		}
	}
	if q.refreshTaskDailyOverviewStmt != nil {
		if cerr := q.refreshTaskDailyOverviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshTaskDailyOverviewStmt: %w", cerr)
		}
	}
	if q.refreshTaskDailyStatsStmt != nil {
		if cerr := q.refreshTaskDailyStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshTaskDailyStatsStmt: %w", cerr)
		}
	}
	if q.updateProgressStmt != nil {
		if cerr := q.updateProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProgressStmt: %w", cerr)
		}
	}
	if q.upsertSequenceStateStmt != nil {
		if cerr := q.upsertSequenceStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSequenceStateStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                      DBTX
	tx                                      *sql.Tx
	adminCreateTaskStmt                     *sql.Stmt
	adminDeleteRewardStmt                   *sql.Stmt
	adminDeleteTaskStmt                     *sql.Stmt
	adminGetSingleTaskStatsStmt             *sql.Stmt
	adminGetTaskStmt                        *sql.Stmt
	adminGetTaskStatsStmt                   *sql.Stmt
	adminListTaskDailyOverviewStmt          *sql.Stmt
	adminListTaskDailyStatsStmt             *sql.Stmt
	adminListTasksStmt                      *sql.Stmt
	adminListTasksByGroupStmt               *sql.Stmt
	adminUpdateTaskStmt                     *sql.Stmt
	adminUpsertGroupStmt                    *sql.Stmt
	adminUpsertGroupLocalizationStmt        *sql.Stmt
	adminUpsertRewardStmt                   *sql.Stmt
	adminUpsertSequenceStmt                 *sql.Stmt
	adminUpsertTaskLocalizationStmt         *sql.Stmt
	countProgressEventsByExternalKeyStmt    *sql.Stmt
	ensureProgressStmt                      *sql.Stmt
	getClaimBundleByIDForUpdateStmt         *sql.Stmt
	getClaimBundleByKeyForUpdateStmt        *sql.Stmt
	getNextSequenceTaskIDStmt               *sql.Stmt
	insertProgressEventStmt                 *sql.Stmt
	listActiveTaskBundlesStmt               *sql.Stmt
	listCurrentProgressForUserStmt          *sql.Stmt
	listCurrentProgressForUserForUpdateStmt *sql.Stmt
	listRecordTasksStmt                     *sql.Stmt
	listRewardsStmt                         *sql.Stmt
	refreshTaskDailyOverviewStmt            *sql.Stmt
	refreshTaskDailyStatsStmt               *sql.Stmt
	updateProgressStmt                      *sql.Stmt
	upsertSequenceStateStmt                 *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                      tx,
		tx:                                      tx,
		adminCreateTaskStmt:                     q.adminCreateTaskStmt,
		adminDeleteRewardStmt:                   q.adminDeleteRewardStmt,
		adminDeleteTaskStmt:                     q.adminDeleteTaskStmt,
		adminGetSingleTaskStatsStmt:             q.adminGetSingleTaskStatsStmt,
		adminGetTaskStmt:                        q.adminGetTaskStmt,
		adminGetTaskStatsStmt:                   q.adminGetTaskStatsStmt,
		adminListTaskDailyOverviewStmt:          q.adminListTaskDailyOverviewStmt,
		adminListTaskDailyStatsStmt:             q.adminListTaskDailyStatsStmt,
		adminListTasksStmt:                      q.adminListTasksStmt,
		adminListTasksByGroupStmt:               q.adminListTasksByGroupStmt,
		adminUpdateTaskStmt:                     q.adminUpdateTaskStmt,
		adminUpsertGroupStmt:                    q.adminUpsertGroupStmt,
		adminUpsertGroupLocalizationStmt:        q.adminUpsertGroupLocalizationStmt,
		adminUpsertRewardStmt:                   q.adminUpsertRewardStmt,
		adminUpsertSequenceStmt:                 q.adminUpsertSequenceStmt,
		adminUpsertTaskLocalizationStmt:         q.adminUpsertTaskLocalizationStmt,
		countProgressEventsByExternalKeyStmt:    q.countProgressEventsByExternalKeyStmt,
		ensureProgressStmt:                      q.ensureProgressStmt,
		getClaimBundleByIDForUpdateStmt:         q.getClaimBundleByIDForUpdateStmt,
		getClaimBundleByKeyForUpdateStmt:        q.getClaimBundleByKeyForUpdateStmt,
		getNextSequenceTaskIDStmt:               q.getNextSequenceTaskIDStmt,
		insertProgressEventStmt:                 q.insertProgressEventStmt,
		listActiveTaskBundlesStmt:               q.listActiveTaskBundlesStmt,
		listCurrentProgressForUserStmt:          q.listCurrentProgressForUserStmt,
		listCurrentProgressForUserForUpdateStmt: q.listCurrentProgressForUserForUpdateStmt,
		listRecordTasksStmt:                     q.listRecordTasksStmt,
		listRewardsStmt:                         q.listRewardsStmt,
		refreshTaskDailyOverviewStmt:            q.refreshTaskDailyOverviewStmt,
		refreshTaskDailyStatsStmt:               q.refreshTaskDailyStatsStmt,
		updateProgressStmt:                      q.updateProgressStmt,
		upsertSequenceStateStmt:                 q.upsertSequenceStateStmt,
	}
}
