// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const adminCreateTask = `-- name: AdminCreateTask :execlastid
INSERT INTO task_definition (
    workspace_id, ` + "`" + `key` + "`" + `, group_key, sequence_key, sequence_position,
    action_key, action_kind, claim_mode, target_count, reset_unit,
    reset_every, position, payload, image_url, is_visible, is_active,
    start_at, end_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AdminCreateTaskParams struct {
	WorkspaceID      string                   `json:"workspace_id"`
	Key              string                   `json:"key"`
	GroupKey         string                   `json:"group_key"`
	SequenceKey      sql.NullString           `json:"sequence_key"`
	SequencePosition sql.NullInt32            `json:"sequence_position"`
	ActionKey        string                   `json:"action_key"`
	ActionKind       TaskDefinitionActionKind `json:"action_kind"`
	ClaimMode        TaskDefinitionClaimMode  `json:"claim_mode"`
	TargetCount      uint64                   `json:"target_count"`
	ResetUnit        TaskDefinitionResetUnit  `json:"reset_unit"`
	ResetEvery       uint32                   `json:"reset_every"`
	Position         int32                    `json:"position"`
	Payload          json.RawMessage          `json:"payload"`
	ImageUrl         sql.NullString           `json:"image_url"`
	IsVisible        bool                     `json:"is_visible"`
	IsActive         bool                     `json:"is_active"`
	StartAt          sql.NullTime             `json:"start_at"`
	EndAt            sql.NullTime             `json:"end_at"`
}

func (q *Queries) AdminCreateTask(ctx context.Context, arg AdminCreateTaskParams) (int64, error) {
	result, err := q.exec(ctx, q.adminCreateTaskStmt, adminCreateTask,
		arg.WorkspaceID,
		arg.Key,
		arg.GroupKey,
		arg.SequenceKey,
		arg.SequencePosition,
		arg.ActionKey,
		arg.ActionKind,
		arg.ClaimMode,
		arg.TargetCount,
		arg.ResetUnit,
		arg.ResetEvery,
		arg.Position,
		arg.Payload,
		arg.ImageUrl,
		arg.IsVisible,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const adminDeleteReward = `-- name: AdminDeleteReward :execrows
DELETE FROM task_reward
WHERE workspace_id = ? AND task_id = ? AND reward_key = ?
`

type AdminDeleteRewardParams struct {
	WorkspaceID string `json:"workspace_id"`
	TaskID      uint64 `json:"task_id"`
	RewardKey   string `json:"reward_key"`
}

func (q *Queries) AdminDeleteReward(ctx context.Context, arg AdminDeleteRewardParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteRewardStmt, adminDeleteReward, arg.WorkspaceID, arg.TaskID, arg.RewardKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteTask = `-- name: AdminDeleteTask :execrows
UPDATE task_definition
SET deleted_at = NOW(), is_active = FALSE, is_visible = FALSE
WHERE workspace_id = ? AND id = ? AND deleted_at IS NULL
`

type AdminDeleteTaskParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) AdminDeleteTask(ctx context.Context, arg AdminDeleteTaskParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteTaskStmt, adminDeleteTask, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminGetSingleTaskStats = `-- name: AdminGetSingleTaskStats :one
SELECT
    definition.id AS task_id,
    progress.progress_total,
    progress.open_progress,
    progress.ready_progress,
    progress.claimed_progress,
    events.progress_created,
    events.progress_amount,
    events.ready_count,
    events.claimed_count,
    events.manual_claimed_count,
    events.auto_claimed_count,
    events.unique_participants,
    events.unique_claimers
FROM task_definition definition
CROSS JOIN (
    SELECT
        COUNT(*) AS progress_total,
        CAST(COALESCE(SUM(status = 'open'), 0) AS UNSIGNED) AS open_progress,
        CAST(COALESCE(SUM(status = 'ready'), 0) AS UNSIGNED) AS ready_progress,
        CAST(COALESCE(SUM(status = 'claimed'), 0) AS UNSIGNED) AS claimed_progress
    FROM task_progress single_progress
    WHERE single_progress.workspace_id = ? AND single_progress.task_id = ?
) progress
CROSS JOIN (
    SELECT
        CAST(COALESCE(SUM(event_type = 'progress_created'), 0) AS UNSIGNED) AS progress_created,
        CAST(COALESCE(SUM(IF(event_type = 'progress_added', amount, 0)), 0) AS UNSIGNED) AS progress_amount,
        CAST(COALESCE(SUM(event_type = 'ready'), 0) AS UNSIGNED) AS ready_count,
        CAST(COALESCE(SUM(event_type = 'claimed'), 0) AS UNSIGNED) AS claimed_count,
        CAST(COALESCE(SUM(event_type = 'claimed' AND claim_mode = 'manual'), 0) AS UNSIGNED) AS manual_claimed_count,
        CAST(COALESCE(SUM(event_type = 'claimed' AND claim_mode = 'auto'), 0) AS UNSIGNED) AS auto_claimed_count,
        COUNT(DISTINCT CONCAT_WS(':', app_id, platform_id, platform_user_id)) AS unique_participants,
        COUNT(DISTINCT IF(
            event_type = 'claimed',
            CONCAT_WS(':', app_id, platform_id, platform_user_id),
            NULL
        )) AS unique_claimers
    FROM task_stats_event single_events
    WHERE single_events.workspace_id = ? AND single_events.task_id = ?
) events
WHERE definition.workspace_id = ? AND definition.id = ?
LIMIT 1
`

type AdminGetSingleTaskStatsParams struct {
	WorkspaceID   string `json:"workspace_id"`
	TaskID        uint64 `json:"task_id"`
	WorkspaceID_2 string `json:"workspace_id_2"`
	TaskID_2      uint64 `json:"task_id_2"`
	WorkspaceID_3 string `json:"workspace_id_3"`
	ID            uint64 `json:"id"`
}

type AdminGetSingleTaskStatsRow struct {
	TaskID             uint64 `json:"task_id"`
	ProgressTotal      int64  `json:"progress_total"`
	OpenProgress       int64  `json:"open_progress"`
	ReadyProgress      int64  `json:"ready_progress"`
	ClaimedProgress    int64  `json:"claimed_progress"`
	ProgressCreated    int64  `json:"progress_created"`
	ProgressAmount     int64  `json:"progress_amount"`
	ReadyCount         int64  `json:"ready_count"`
	ClaimedCount       int64  `json:"claimed_count"`
	ManualClaimedCount int64  `json:"manual_claimed_count"`
	AutoClaimedCount   int64  `json:"auto_claimed_count"`
	UniqueParticipants int64  `json:"unique_participants"`
	UniqueClaimers     int64  `json:"unique_claimers"`
}

func (q *Queries) AdminGetSingleTaskStats(ctx context.Context, arg AdminGetSingleTaskStatsParams) (AdminGetSingleTaskStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetSingleTaskStatsStmt, adminGetSingleTaskStats,
		arg.WorkspaceID,
		arg.TaskID,
		arg.WorkspaceID_2,
		arg.TaskID_2,
		arg.WorkspaceID_3,
		arg.ID,
	)
	var i AdminGetSingleTaskStatsRow
	err := row.Scan(
		&i.TaskID,
		&i.ProgressTotal,
		&i.OpenProgress,
		&i.ReadyProgress,
		&i.ClaimedProgress,
		&i.ProgressCreated,
		&i.ProgressAmount,
		&i.ReadyCount,
		&i.ClaimedCount,
		&i.ManualClaimedCount,
		&i.AutoClaimedCount,
		&i.UniqueParticipants,
		&i.UniqueClaimers,
	)
	return i, err
}

const adminGetTask = `-- name: AdminGetTask :one
SELECT id, workspace_id, ` + "`" + `key` + "`" + `, group_key, sequence_key, sequence_position,
       action_key, action_kind, claim_mode, target_count, reset_unit,
       reset_every, position, payload, image_url, is_visible, is_active,
       start_at, end_at, deleted_at, branch_sort_key, created_at, updated_at
FROM task_definition
WHERE workspace_id = ? AND id = ?
LIMIT 1
`

type AdminGetTaskParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) AdminGetTask(ctx context.Context, arg AdminGetTaskParams) (TaskDefinition, error) {
	row := q.queryRow(ctx, q.adminGetTaskStmt, adminGetTask, arg.WorkspaceID, arg.ID)
	var i TaskDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.GroupKey,
		&i.SequenceKey,
		&i.SequencePosition,
		&i.ActionKey,
		&i.ActionKind,
		&i.ClaimMode,
		&i.TargetCount,
		&i.ResetUnit,
		&i.ResetEvery,
		&i.Position,
		&i.Payload,
		&i.ImageUrl,
		&i.IsVisible,
		&i.IsActive,
		&i.StartAt,
		&i.EndAt,
		&i.DeletedAt,
		&i.BranchSortKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetTaskStats = `-- name: AdminGetTaskStats :one
SELECT
    definitions.tasks_total,
    definitions.active_tasks,
    definitions.visible_tasks,
    progress.progress_total,
    progress.open_progress,
    progress.ready_progress,
    progress.claimed_progress,
    events.progress_created,
    events.progress_amount,
    events.ready_count,
    events.claimed_count,
    events.manual_claimed_count,
    events.auto_claimed_count,
    events.unique_participants,
    events.unique_claimers
FROM (
    SELECT
        COUNT(*) AS tasks_total,
        CAST(COALESCE(SUM(
            is_active = TRUE
            AND deleted_at IS NULL
            AND (start_at IS NULL OR start_at <= NOW())
            AND (end_at IS NULL OR end_at > NOW())
        ), 0) AS UNSIGNED) AS active_tasks,
        CAST(COALESCE(SUM(
            is_visible = TRUE
            AND is_active = TRUE
            AND deleted_at IS NULL
            AND (start_at IS NULL OR start_at <= NOW())
            AND (end_at IS NULL OR end_at > NOW())
        ), 0) AS UNSIGNED) AS visible_tasks
    FROM task_definition stats_definitions
    WHERE stats_definitions.workspace_id = ?
) definitions
CROSS JOIN (
    SELECT
        COUNT(*) AS progress_total,
        CAST(COALESCE(SUM(status = 'open'), 0) AS UNSIGNED) AS open_progress,
        CAST(COALESCE(SUM(status = 'ready'), 0) AS UNSIGNED) AS ready_progress,
        CAST(COALESCE(SUM(status = 'claimed'), 0) AS UNSIGNED) AS claimed_progress
    FROM task_progress stats_progress
    WHERE stats_progress.workspace_id = ?
) progress
CROSS JOIN (
    SELECT
        CAST(COALESCE(SUM(event_type = 'progress_created'), 0) AS UNSIGNED) AS progress_created,
        CAST(COALESCE(SUM(IF(event_type = 'progress_added', amount, 0)), 0) AS UNSIGNED) AS progress_amount,
        CAST(COALESCE(SUM(event_type = 'ready'), 0) AS UNSIGNED) AS ready_count,
        CAST(COALESCE(SUM(event_type = 'claimed'), 0) AS UNSIGNED) AS claimed_count,
        CAST(COALESCE(SUM(event_type = 'claimed' AND claim_mode = 'manual'), 0) AS UNSIGNED) AS manual_claimed_count,
        CAST(COALESCE(SUM(event_type = 'claimed' AND claim_mode = 'auto'), 0) AS UNSIGNED) AS auto_claimed_count,
        COUNT(DISTINCT CONCAT_WS(':', app_id, platform_id, platform_user_id)) AS unique_participants,
        COUNT(DISTINCT IF(
            event_type = 'claimed',
            CONCAT_WS(':', app_id, platform_id, platform_user_id),
            NULL
        )) AS unique_claimers
    FROM task_stats_event stats_events
    WHERE stats_events.workspace_id = ?
) events
`

type AdminGetTaskStatsParams struct {
	WorkspaceID   string `json:"workspace_id"`
	WorkspaceID_2 string `json:"workspace_id_2"`
	WorkspaceID_3 string `json:"workspace_id_3"`
}

type AdminGetTaskStatsRow struct {
	TasksTotal         int64 `json:"tasks_total"`
	ActiveTasks        int64 `json:"active_tasks"`
	VisibleTasks       int64 `json:"visible_tasks"`
	ProgressTotal      int64 `json:"progress_total"`
	OpenProgress       int64 `json:"open_progress"`
	ReadyProgress      int64 `json:"ready_progress"`
	ClaimedProgress    int64 `json:"claimed_progress"`
	ProgressCreated    int64 `json:"progress_created"`
	ProgressAmount     int64 `json:"progress_amount"`
	ReadyCount         int64 `json:"ready_count"`
	ClaimedCount       int64 `json:"claimed_count"`
	ManualClaimedCount int64 `json:"manual_claimed_count"`
	AutoClaimedCount   int64 `json:"auto_claimed_count"`
	UniqueParticipants int64 `json:"unique_participants"`
	UniqueClaimers     int64 `json:"unique_claimers"`
}

func (q *Queries) AdminGetTaskStats(ctx context.Context, arg AdminGetTaskStatsParams) (AdminGetTaskStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetTaskStatsStmt, adminGetTaskStats, arg.WorkspaceID, arg.WorkspaceID_2, arg.WorkspaceID_3)
	var i AdminGetTaskStatsRow
	err := row.Scan(
		&i.TasksTotal,
		&i.ActiveTasks,
		&i.VisibleTasks,
		&i.ProgressTotal,
		&i.OpenProgress,
		&i.ReadyProgress,
		&i.ClaimedProgress,
		&i.ProgressCreated,
		&i.ProgressAmount,
		&i.ReadyCount,
		&i.ClaimedCount,
		&i.ManualClaimedCount,
		&i.AutoClaimedCount,
		&i.UniqueParticipants,
		&i.UniqueClaimers,
	)
	return i, err
}

const adminListTaskDailyOverview = `-- name: AdminListTaskDailyOverview :many
SELECT
    workspace_id,
    stats_date,
    tasks_total,
    active_tasks,
    visible_tasks,
    progress_created,
    progress_amount,
    ready_count,
    claimed_count,
    manual_claimed_count,
    auto_claimed_count,
    unique_participants,
    unique_claimers,
    updated_at
FROM task_stats_daily_overview stored_overview
WHERE stored_overview.workspace_id = ?
  AND stored_overview.stats_date >= ?
  AND stored_overview.stats_date <= ?
  AND stored_overview.stats_date < CURRENT_DATE
UNION ALL
SELECT
    ? AS workspace_id,
    CURRENT_DATE AS stats_date,
    definitions.tasks_total,
    definitions.active_tasks,
    definitions.visible_tasks,
    events.progress_created,
    events.progress_amount,
    events.ready_count,
    events.claimed_count,
    events.manual_claimed_count,
    events.auto_claimed_count,
    events.unique_participants,
    events.unique_claimers,
    NOW() AS updated_at
FROM (
    SELECT
        COUNT(*) AS tasks_total,
        CAST(COALESCE(SUM(
            is_active = TRUE
            AND deleted_at IS NULL
            AND (start_at IS NULL OR start_at <= NOW())
            AND (end_at IS NULL OR end_at > NOW())
        ), 0) AS UNSIGNED) AS active_tasks,
        CAST(COALESCE(SUM(
            is_visible = TRUE
            AND is_active = TRUE
            AND deleted_at IS NULL
            AND (start_at IS NULL OR start_at <= NOW())
            AND (end_at IS NULL OR end_at > NOW())
        ), 0) AS UNSIGNED) AS visible_tasks
    FROM task_definition current_definitions
    WHERE current_definitions.workspace_id = ?
) definitions
CROSS JOIN (
    SELECT
        CAST(COALESCE(SUM(event_type = 'progress_created'), 0) AS UNSIGNED) AS progress_created,
        CAST(COALESCE(SUM(IF(event_type = 'progress_added', amount, 0)), 0) AS UNSIGNED) AS progress_amount,
        CAST(COALESCE(SUM(event_type = 'ready'), 0) AS UNSIGNED) AS ready_count,
        CAST(COALESCE(SUM(event_type = 'claimed'), 0) AS UNSIGNED) AS claimed_count,
        CAST(COALESCE(SUM(event_type = 'claimed' AND claim_mode = 'manual'), 0) AS UNSIGNED) AS manual_claimed_count,
        CAST(COALESCE(SUM(event_type = 'claimed' AND claim_mode = 'auto'), 0) AS UNSIGNED) AS auto_claimed_count,
        COUNT(DISTINCT CONCAT_WS(':', app_id, platform_id, platform_user_id)) AS unique_participants,
        COUNT(DISTINCT IF(
            event_type = 'claimed',
            CONCAT_WS(':', app_id, platform_id, platform_user_id),
            NULL
        )) AS unique_claimers
    FROM task_stats_event current_overview_events
    WHERE current_overview_events.workspace_id = ?
      AND current_overview_events.occurred_at >= CURRENT_DATE
      AND current_overview_events.occurred_at < CURRENT_DATE + INTERVAL 1 DAY
) events
WHERE CURRENT_DATE >= ?
  AND CURRENT_DATE <= ?
ORDER BY stats_date
`

type AdminListTaskDailyOverviewParams struct {
	WorkspaceID   string      `json:"workspace_id"`
	StatsDate     time.Time   `json:"stats_date"`
	StatsDate_2   time.Time   `json:"stats_date_2"`
	WorkspaceID_2 string      `json:"workspace_id_2"`
	WorkspaceID_3 string      `json:"workspace_id_3"`
	WorkspaceID_4 string      `json:"workspace_id_4"`
	Column7       interface{} `json:"column_7"`
	Column8       interface{} `json:"column_8"`
}

func (q *Queries) AdminListTaskDailyOverview(ctx context.Context, arg AdminListTaskDailyOverviewParams) ([]TaskStatsDailyOverview, error) {
	rows, err := q.query(ctx, q.adminListTaskDailyOverviewStmt, adminListTaskDailyOverview,
		arg.WorkspaceID,
		arg.StatsDate,
		arg.StatsDate_2,
		arg.WorkspaceID_2,
		arg.WorkspaceID_3,
		arg.WorkspaceID_4,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskStatsDailyOverview
	for rows.Next() {
		var i TaskStatsDailyOverview
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.StatsDate,
			&i.TasksTotal,
			&i.ActiveTasks,
			&i.VisibleTasks,
			&i.ProgressCreated,
			&i.ProgressAmount,
			&i.ReadyCount,
			&i.ClaimedCount,
			&i.ManualClaimedCount,
			&i.AutoClaimedCount,
			&i.UniqueParticipants,
			&i.UniqueClaimers,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTaskDailyStats = `-- name: AdminListTaskDailyStats :many
SELECT
    workspace_id,
    task_id,
    stats_date,
    progress_created,
    progress_amount,
    ready_count,
    claimed_count,
    manual_claimed_count,
    auto_claimed_count,
    unique_participants,
    unique_claimers,
    updated_at
FROM task_stats_daily stored_stats
WHERE stored_stats.workspace_id = ?
  AND stored_stats.task_id = ?
  AND stored_stats.stats_date >= ?
  AND stored_stats.stats_date <= ?
  AND stored_stats.stats_date < CURRENT_DATE
UNION ALL
SELECT
    ? AS workspace_id,
    ? AS task_id,
    CURRENT_DATE AS stats_date,
    CAST(COALESCE(SUM(event_type = 'progress_created'), 0) AS UNSIGNED) AS progress_created,
    CAST(COALESCE(SUM(IF(event_type = 'progress_added', amount, 0)), 0) AS UNSIGNED) AS progress_amount,
    CAST(COALESCE(SUM(event_type = 'ready'), 0) AS UNSIGNED) AS ready_count,
    CAST(COALESCE(SUM(event_type = 'claimed'), 0) AS UNSIGNED) AS claimed_count,
    CAST(COALESCE(SUM(event_type = 'claimed' AND claim_mode = 'manual'), 0) AS UNSIGNED) AS manual_claimed_count,
    CAST(COALESCE(SUM(event_type = 'claimed' AND claim_mode = 'auto'), 0) AS UNSIGNED) AS auto_claimed_count,
    COUNT(DISTINCT CONCAT_WS(':', app_id, platform_id, platform_user_id)) AS unique_participants,
    COUNT(DISTINCT IF(
        event_type = 'claimed',
        CONCAT_WS(':', app_id, platform_id, platform_user_id),
        NULL
    )) AS unique_claimers,
    NOW() AS updated_at
FROM task_stats_event current_events
WHERE current_events.workspace_id = ?
  AND current_events.task_id = ?
  AND current_events.occurred_at >= CURRENT_DATE
  AND current_events.occurred_at < CURRENT_DATE + INTERVAL 1 DAY
  AND CURRENT_DATE >= ?
  AND CURRENT_DATE <= ?
ORDER BY stats_date
`

type AdminListTaskDailyStatsParams struct {
	WorkspaceID   string      `json:"workspace_id"`
	TaskID        uint64      `json:"task_id"`
	StatsDate     time.Time   `json:"stats_date"`
	StatsDate_2   time.Time   `json:"stats_date_2"`
	WorkspaceID_2 string      `json:"workspace_id_2"`
	TaskID_2      uint64      `json:"task_id_2"`
	WorkspaceID_3 string      `json:"workspace_id_3"`
	TaskID_3      uint64      `json:"task_id_3"`
	Column9       interface{} `json:"column_9"`
	Column10      interface{} `json:"column_10"`
}

func (q *Queries) AdminListTaskDailyStats(ctx context.Context, arg AdminListTaskDailyStatsParams) ([]TaskStatsDaily, error) {
	rows, err := q.query(ctx, q.adminListTaskDailyStatsStmt, adminListTaskDailyStats,
		arg.WorkspaceID,
		arg.TaskID,
		arg.StatsDate,
		arg.StatsDate_2,
		arg.WorkspaceID_2,
		arg.TaskID_2,
		arg.WorkspaceID_3,
		arg.TaskID_3,
		arg.Column9,
		arg.Column10,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskStatsDaily
	for rows.Next() {
		var i TaskStatsDaily
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.TaskID,
			&i.StatsDate,
			&i.ProgressCreated,
			&i.ProgressAmount,
			&i.ReadyCount,
			&i.ClaimedCount,
			&i.ManualClaimedCount,
			&i.AutoClaimedCount,
			&i.UniqueParticipants,
			&i.UniqueClaimers,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTasks = `-- name: AdminListTasks :many
SELECT id, workspace_id, ` + "`" + `key` + "`" + `, group_key, sequence_key, sequence_position,
       action_key, action_kind, claim_mode, target_count, reset_unit,
       reset_every, position, payload, image_url, is_visible, is_active,
       start_at, end_at, deleted_at, branch_sort_key, created_at, updated_at
FROM task_definition
WHERE workspace_id = ? AND deleted_at IS NULL
ORDER BY position, id
LIMIT ? OFFSET ?
`

type AdminListTasksParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) AdminListTasks(ctx context.Context, arg AdminListTasksParams) ([]TaskDefinition, error) {
	rows, err := q.query(ctx, q.adminListTasksStmt, adminListTasks, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDefinition
	for rows.Next() {
		var i TaskDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.GroupKey,
			&i.SequenceKey,
			&i.SequencePosition,
			&i.ActionKey,
			&i.ActionKind,
			&i.ClaimMode,
			&i.TargetCount,
			&i.ResetUnit,
			&i.ResetEvery,
			&i.Position,
			&i.Payload,
			&i.ImageUrl,
			&i.IsVisible,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.BranchSortKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTasksByGroup = `-- name: AdminListTasksByGroup :many
SELECT id, workspace_id, ` + "`" + `key` + "`" + `, group_key, sequence_key, sequence_position,
       action_key, action_kind, claim_mode, target_count, reset_unit,
       reset_every, position, payload, image_url, is_visible, is_active,
       start_at, end_at, deleted_at, branch_sort_key, created_at, updated_at
FROM task_definition
WHERE workspace_id = ? AND group_key = ? AND deleted_at IS NULL
ORDER BY position, id
LIMIT ? OFFSET ?
`

type AdminListTasksByGroupParams struct {
	WorkspaceID string `json:"workspace_id"`
	GroupKey    string `json:"group_key"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) AdminListTasksByGroup(ctx context.Context, arg AdminListTasksByGroupParams) ([]TaskDefinition, error) {
	rows, err := q.query(ctx, q.adminListTasksByGroupStmt, adminListTasksByGroup,
		arg.WorkspaceID,
		arg.GroupKey,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskDefinition
	for rows.Next() {
		var i TaskDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.GroupKey,
			&i.SequenceKey,
			&i.SequencePosition,
			&i.ActionKey,
			&i.ActionKind,
			&i.ClaimMode,
			&i.TargetCount,
			&i.ResetUnit,
			&i.ResetEvery,
			&i.Position,
			&i.Payload,
			&i.ImageUrl,
			&i.IsVisible,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.BranchSortKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateTask = `-- name: AdminUpdateTask :execrows
UPDATE task_definition
SET group_key = ?, sequence_key = ?, sequence_position = ?, action_key = ?,
    action_kind = ?, claim_mode = ?, target_count = ?, reset_unit = ?,
    reset_every = ?, position = ?, payload = ?, image_url = ?,
    is_visible = ?, is_active = ?, start_at = ?, end_at = ?
WHERE workspace_id = ? AND id = ? AND deleted_at IS NULL
`

type AdminUpdateTaskParams struct {
	GroupKey         string                   `json:"group_key"`
	SequenceKey      sql.NullString           `json:"sequence_key"`
	SequencePosition sql.NullInt32            `json:"sequence_position"`
	ActionKey        string                   `json:"action_key"`
	ActionKind       TaskDefinitionActionKind `json:"action_kind"`
	ClaimMode        TaskDefinitionClaimMode  `json:"claim_mode"`
	TargetCount      uint64                   `json:"target_count"`
	ResetUnit        TaskDefinitionResetUnit  `json:"reset_unit"`
	ResetEvery       uint32                   `json:"reset_every"`
	Position         int32                    `json:"position"`
	Payload          json.RawMessage          `json:"payload"`
	ImageUrl         sql.NullString           `json:"image_url"`
	IsVisible        bool                     `json:"is_visible"`
	IsActive         bool                     `json:"is_active"`
	StartAt          sql.NullTime             `json:"start_at"`
	EndAt            sql.NullTime             `json:"end_at"`
	WorkspaceID      string                   `json:"workspace_id"`
	ID               uint64                   `json:"id"`
}

func (q *Queries) AdminUpdateTask(ctx context.Context, arg AdminUpdateTaskParams) (int64, error) {
	result, err := q.exec(ctx, q.adminUpdateTaskStmt, adminUpdateTask,
		arg.GroupKey,
		arg.SequenceKey,
		arg.SequencePosition,
		arg.ActionKey,
		arg.ActionKind,
		arg.ClaimMode,
		arg.TargetCount,
		arg.ResetUnit,
		arg.ResetEvery,
		arg.Position,
		arg.Payload,
		arg.ImageUrl,
		arg.IsVisible,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpsertGroup = `-- name: AdminUpsertGroup :exec
INSERT INTO task_group (workspace_id, ` + "`" + `key` + "`" + `, position, is_active)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE position = VALUES(position), is_active = VALUES(is_active), deleted_at = NULL
`

type AdminUpsertGroupParams struct {
	WorkspaceID string `json:"workspace_id"`
	Key         string `json:"key"`
	Position    int32  `json:"position"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) AdminUpsertGroup(ctx context.Context, arg AdminUpsertGroupParams) error {
	_, err := q.exec(ctx, q.adminUpsertGroupStmt, adminUpsertGroup,
		arg.WorkspaceID,
		arg.Key,
		arg.Position,
		arg.IsActive,
	)
	return err
}

const adminUpsertGroupLocalization = `-- name: AdminUpsertGroupLocalization :exec
INSERT INTO task_group_localization (workspace_id, group_key, locale, title, description)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE title = VALUES(title), description = VALUES(description)
`

type AdminUpsertGroupLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	GroupKey    string `json:"group_key"`
	Locale      string `json:"locale"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) AdminUpsertGroupLocalization(ctx context.Context, arg AdminUpsertGroupLocalizationParams) error {
	_, err := q.exec(ctx, q.adminUpsertGroupLocalizationStmt, adminUpsertGroupLocalization,
		arg.WorkspaceID,
		arg.GroupKey,
		arg.Locale,
		arg.Title,
		arg.Description,
	)
	return err
}

const adminUpsertReward = `-- name: AdminUpsertReward :exec
INSERT INTO task_reward (
    workspace_id, task_id, reward_key, reward_type, quantity, duration_unit, position
)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    reward_type = VALUES(reward_type),
    quantity = VALUES(quantity),
    duration_unit = VALUES(duration_unit),
    position = VALUES(position)
`

type AdminUpsertRewardParams struct {
	WorkspaceID  string                     `json:"workspace_id"`
	TaskID       uint64                     `json:"task_id"`
	RewardKey    string                     `json:"reward_key"`
	RewardType   TaskRewardRewardType       `json:"reward_type"`
	Quantity     int64                      `json:"quantity"`
	DurationUnit NullTaskRewardDurationUnit `json:"duration_unit"`
	Position     int32                      `json:"position"`
}

func (q *Queries) AdminUpsertReward(ctx context.Context, arg AdminUpsertRewardParams) error {
	_, err := q.exec(ctx, q.adminUpsertRewardStmt, adminUpsertReward,
		arg.WorkspaceID,
		arg.TaskID,
		arg.RewardKey,
		arg.RewardType,
		arg.Quantity,
		arg.DurationUnit,
		arg.Position,
	)
	return err
}

const adminUpsertSequence = `-- name: AdminUpsertSequence :exec
INSERT INTO task_sequence (workspace_id, ` + "`" + `key` + "`" + `, position, is_active)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE position = VALUES(position), is_active = VALUES(is_active), deleted_at = NULL
`

type AdminUpsertSequenceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Key         string `json:"key"`
	Position    int32  `json:"position"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) AdminUpsertSequence(ctx context.Context, arg AdminUpsertSequenceParams) error {
	_, err := q.exec(ctx, q.adminUpsertSequenceStmt, adminUpsertSequence,
		arg.WorkspaceID,
		arg.Key,
		arg.Position,
		arg.IsActive,
	)
	return err
}

const adminUpsertTaskLocalization = `-- name: AdminUpsertTaskLocalization :exec
INSERT INTO task_localization (workspace_id, task_id, locale, title, description)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE title = VALUES(title), description = VALUES(description)
`

type AdminUpsertTaskLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	TaskID      uint64 `json:"task_id"`
	Locale      string `json:"locale"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) AdminUpsertTaskLocalization(ctx context.Context, arg AdminUpsertTaskLocalizationParams) error {
	_, err := q.exec(ctx, q.adminUpsertTaskLocalizationStmt, adminUpsertTaskLocalization,
		arg.WorkspaceID,
		arg.TaskID,
		arg.Locale,
		arg.Title,
		arg.Description,
	)
	return err
}

const countProgressEventsByExternalKey = `-- name: CountProgressEventsByExternalKey :one
SELECT COUNT(*)
FROM task_progress_event
WHERE workspace_id = ?
  AND app_id = ?
  AND platform_id = ?
  AND platform_user_id = ?
  AND source = ?
  AND external_event_key = ?
`

type CountProgressEventsByExternalKeyParams struct {
	WorkspaceID      string `json:"workspace_id"`
	AppID            int64  `json:"app_id"`
	PlatformID       int64  `json:"platform_id"`
	PlatformUserID   string `json:"platform_user_id"`
	Source           string `json:"source"`
	ExternalEventKey string `json:"external_event_key"`
}

func (q *Queries) CountProgressEventsByExternalKey(ctx context.Context, arg CountProgressEventsByExternalKeyParams) (int64, error) {
	row := q.queryRow(ctx, q.countProgressEventsByExternalKeyStmt, countProgressEventsByExternalKey,
		arg.WorkspaceID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.Source,
		arg.ExternalEventKey,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureProgress = `-- name: EnsureProgress :execlastid
INSERT INTO task_progress (
    workspace_id, task_id, app_id, platform_id, platform_user_id,
    period_start_at, period_end_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), period_end_at = VALUES(period_end_at)
`

type EnsureProgressParams struct {
	WorkspaceID    string    `json:"workspace_id"`
	TaskID         uint64    `json:"task_id"`
	AppID          int64     `json:"app_id"`
	PlatformID     int64     `json:"platform_id"`
	PlatformUserID string    `json:"platform_user_id"`
	PeriodStartAt  time.Time `json:"period_start_at"`
	PeriodEndAt    time.Time `json:"period_end_at"`
}

func (q *Queries) EnsureProgress(ctx context.Context, arg EnsureProgressParams) (int64, error) {
	result, err := q.exec(ctx, q.ensureProgressStmt, ensureProgress,
		arg.WorkspaceID,
		arg.TaskID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.PeriodStartAt,
		arg.PeriodEndAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getClaimBundleByIDForUpdate = `-- name: GetClaimBundleByIDForUpdate :many
SELECT t.id, t.workspace_id, t.` + "`" + `key` + "`" + `, t.group_key, t.sequence_key, t.sequence_position,
       t.action_key, t.action_kind, t.claim_mode, t.target_count,
       t.payload, t.image_url,
       p.id AS progress_id, p.progress, p.status, p.period_start_at, p.period_end_at,
    p.ready_at, p.claimed_at, p.operation_id, COALESCE(p.rewards_snapshot, JSON_ARRAY()) AS rewards_snapshot,
       r.id AS reward_id, r.reward_key, r.reward_type,
       r.quantity AS reward_quantity, r.duration_unit, r.position AS reward_position
FROM task_definition t
LEFT JOIN task_progress p
  ON p.workspace_id = t.workspace_id AND p.task_id = t.id
 AND p.app_id = ? AND p.platform_id = ? AND p.platform_user_id = ?
 AND p.period_start_at <= ? AND p.period_end_at > ?
LEFT JOIN task_reward r ON r.workspace_id = t.workspace_id AND r.task_id = t.id
WHERE t.workspace_id = ? AND t.id = ?
ORDER BY r.position, r.id
FOR UPDATE
`

type GetClaimBundleByIDForUpdateParams struct {
	AppID          int64     `json:"app_id"`
	PlatformID     int64     `json:"platform_id"`
	PlatformUserID string    `json:"platform_user_id"`
	PeriodStartAt  time.Time `json:"period_start_at"`
	PeriodEndAt    time.Time `json:"period_end_at"`
	WorkspaceID    string    `json:"workspace_id"`
	ID             uint64    `json:"id"`
}

type GetClaimBundleByIDForUpdateRow struct {
	ID               uint64                     `json:"id"`
	WorkspaceID      string                     `json:"workspace_id"`
	Key              string                     `json:"key"`
	GroupKey         string                     `json:"group_key"`
	SequenceKey      sql.NullString             `json:"sequence_key"`
	SequencePosition sql.NullInt32              `json:"sequence_position"`
	ActionKey        string                     `json:"action_key"`
	ActionKind       TaskDefinitionActionKind   `json:"action_kind"`
	ClaimMode        TaskDefinitionClaimMode    `json:"claim_mode"`
	TargetCount      uint64                     `json:"target_count"`
	Payload          json.RawMessage            `json:"payload"`
	ImageUrl         sql.NullString             `json:"image_url"`
	ProgressID       sql.NullInt64              `json:"progress_id"`
	Progress         sql.NullInt64              `json:"progress"`
	Status           NullTaskProgressStatus     `json:"status"`
	PeriodStartAt    sql.NullTime               `json:"period_start_at"`
	PeriodEndAt      sql.NullTime               `json:"period_end_at"`
	ReadyAt          sql.NullTime               `json:"ready_at"`
	ClaimedAt        sql.NullTime               `json:"claimed_at"`
	OperationID      sql.NullString             `json:"operation_id"`
	RewardsSnapshot  json.RawMessage            `json:"rewards_snapshot"`
	RewardID         sql.NullInt64              `json:"reward_id"`
	RewardKey        sql.NullString             `json:"reward_key"`
	RewardType       NullTaskRewardRewardType   `json:"reward_type"`
	RewardQuantity   sql.NullInt64              `json:"reward_quantity"`
	DurationUnit     NullTaskRewardDurationUnit `json:"duration_unit"`
	RewardPosition   sql.NullInt32              `json:"reward_position"`
}

func (q *Queries) GetClaimBundleByIDForUpdate(ctx context.Context, arg GetClaimBundleByIDForUpdateParams) ([]GetClaimBundleByIDForUpdateRow, error) {
	rows, err := q.query(ctx, q.getClaimBundleByIDForUpdateStmt, getClaimBundleByIDForUpdate,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.PeriodStartAt,
		arg.PeriodEndAt,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClaimBundleByIDForUpdateRow
	for rows.Next() {
		var i GetClaimBundleByIDForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.GroupKey,
			&i.SequenceKey,
			&i.SequencePosition,
			&i.ActionKey,
			&i.ActionKind,
			&i.ClaimMode,
			&i.TargetCount,
			&i.Payload,
			&i.ImageUrl,
			&i.ProgressID,
			&i.Progress,
			&i.Status,
			&i.PeriodStartAt,
			&i.PeriodEndAt,
			&i.ReadyAt,
			&i.ClaimedAt,
			&i.OperationID,
			&i.RewardsSnapshot,
			&i.RewardID,
			&i.RewardKey,
			&i.RewardType,
			&i.RewardQuantity,
			&i.DurationUnit,
			&i.RewardPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaimBundleByKeyForUpdate = `-- name: GetClaimBundleByKeyForUpdate :many
SELECT t.id, t.workspace_id, t.` + "`" + `key` + "`" + `, t.group_key, t.sequence_key, t.sequence_position,
       t.action_key, t.action_kind, t.claim_mode, t.target_count,
       t.payload, t.image_url,
       p.id AS progress_id, p.progress, p.status, p.period_start_at, p.period_end_at,
    p.ready_at, p.claimed_at, p.operation_id, COALESCE(p.rewards_snapshot, JSON_ARRAY()) AS rewards_snapshot,
       r.id AS reward_id, r.reward_key, r.reward_type,
       r.quantity AS reward_quantity, r.duration_unit, r.position AS reward_position
FROM task_definition t
LEFT JOIN task_progress p
  ON p.workspace_id = t.workspace_id AND p.task_id = t.id
 AND p.app_id = ? AND p.platform_id = ? AND p.platform_user_id = ?
 AND p.period_start_at <= ? AND p.period_end_at > ?
LEFT JOIN task_reward r ON r.workspace_id = t.workspace_id AND r.task_id = t.id
WHERE t.workspace_id = ? AND t.` + "`" + `key` + "`" + ` = ?
ORDER BY r.position, r.id
FOR UPDATE
`

type GetClaimBundleByKeyForUpdateParams struct {
	AppID          int64     `json:"app_id"`
	PlatformID     int64     `json:"platform_id"`
	PlatformUserID string    `json:"platform_user_id"`
	PeriodStartAt  time.Time `json:"period_start_at"`
	PeriodEndAt    time.Time `json:"period_end_at"`
	WorkspaceID    string    `json:"workspace_id"`
	Key            string    `json:"key"`
}

type GetClaimBundleByKeyForUpdateRow struct {
	ID               uint64                     `json:"id"`
	WorkspaceID      string                     `json:"workspace_id"`
	Key              string                     `json:"key"`
	GroupKey         string                     `json:"group_key"`
	SequenceKey      sql.NullString             `json:"sequence_key"`
	SequencePosition sql.NullInt32              `json:"sequence_position"`
	ActionKey        string                     `json:"action_key"`
	ActionKind       TaskDefinitionActionKind   `json:"action_kind"`
	ClaimMode        TaskDefinitionClaimMode    `json:"claim_mode"`
	TargetCount      uint64                     `json:"target_count"`
	Payload          json.RawMessage            `json:"payload"`
	ImageUrl         sql.NullString             `json:"image_url"`
	ProgressID       sql.NullInt64              `json:"progress_id"`
	Progress         sql.NullInt64              `json:"progress"`
	Status           NullTaskProgressStatus     `json:"status"`
	PeriodStartAt    sql.NullTime               `json:"period_start_at"`
	PeriodEndAt      sql.NullTime               `json:"period_end_at"`
	ReadyAt          sql.NullTime               `json:"ready_at"`
	ClaimedAt        sql.NullTime               `json:"claimed_at"`
	OperationID      sql.NullString             `json:"operation_id"`
	RewardsSnapshot  json.RawMessage            `json:"rewards_snapshot"`
	RewardID         sql.NullInt64              `json:"reward_id"`
	RewardKey        sql.NullString             `json:"reward_key"`
	RewardType       NullTaskRewardRewardType   `json:"reward_type"`
	RewardQuantity   sql.NullInt64              `json:"reward_quantity"`
	DurationUnit     NullTaskRewardDurationUnit `json:"duration_unit"`
	RewardPosition   sql.NullInt32              `json:"reward_position"`
}

func (q *Queries) GetClaimBundleByKeyForUpdate(ctx context.Context, arg GetClaimBundleByKeyForUpdateParams) ([]GetClaimBundleByKeyForUpdateRow, error) {
	rows, err := q.query(ctx, q.getClaimBundleByKeyForUpdateStmt, getClaimBundleByKeyForUpdate,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.PeriodStartAt,
		arg.PeriodEndAt,
		arg.WorkspaceID,
		arg.Key,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClaimBundleByKeyForUpdateRow
	for rows.Next() {
		var i GetClaimBundleByKeyForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.GroupKey,
			&i.SequenceKey,
			&i.SequencePosition,
			&i.ActionKey,
			&i.ActionKind,
			&i.ClaimMode,
			&i.TargetCount,
			&i.Payload,
			&i.ImageUrl,
			&i.ProgressID,
			&i.Progress,
			&i.Status,
			&i.PeriodStartAt,
			&i.PeriodEndAt,
			&i.ReadyAt,
			&i.ClaimedAt,
			&i.OperationID,
			&i.RewardsSnapshot,
			&i.RewardID,
			&i.RewardKey,
			&i.RewardType,
			&i.RewardQuantity,
			&i.DurationUnit,
			&i.RewardPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextSequenceTaskID = `-- name: GetNextSequenceTaskID :one
SELECT id
FROM task_definition
WHERE workspace_id = ?
  AND sequence_key = ?
  AND sequence_position > ?
  AND deleted_at IS NULL
ORDER BY sequence_position, id
LIMIT 1
`

type GetNextSequenceTaskIDParams struct {
	WorkspaceID      string         `json:"workspace_id"`
	SequenceKey      sql.NullString `json:"sequence_key"`
	SequencePosition sql.NullInt32  `json:"sequence_position"`
}

func (q *Queries) GetNextSequenceTaskID(ctx context.Context, arg GetNextSequenceTaskIDParams) (uint64, error) {
	row := q.queryRow(ctx, q.getNextSequenceTaskIDStmt, getNextSequenceTaskID, arg.WorkspaceID, arg.SequenceKey, arg.SequencePosition)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const insertProgressEvent = `-- name: InsertProgressEvent :execrows
INSERT IGNORE INTO task_progress_event (
    workspace_id, app_id, platform_id, platform_user_id,
    source, external_event_key, action_key, amount, payload
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProgressEventParams struct {
	WorkspaceID      string          `json:"workspace_id"`
	AppID            int64           `json:"app_id"`
	PlatformID       int64           `json:"platform_id"`
	PlatformUserID   string          `json:"platform_user_id"`
	Source           string          `json:"source"`
	ExternalEventKey string          `json:"external_event_key"`
	ActionKey        string          `json:"action_key"`
	Amount           uint64          `json:"amount"`
	Payload          json.RawMessage `json:"payload"`
}

func (q *Queries) InsertProgressEvent(ctx context.Context, arg InsertProgressEventParams) (int64, error) {
	result, err := q.exec(ctx, q.insertProgressEventStmt, insertProgressEvent,
		arg.WorkspaceID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.Source,
		arg.ExternalEventKey,
		arg.ActionKey,
		arg.Amount,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveTaskBundles = `-- name: ListActiveTaskBundles :many
SELECT t.id, t.` + "`" + `key` + "`" + `, t.group_key,
       t.action_key, t.action_kind, t.claim_mode, t.target_count,
       t.payload, t.image_url,
       l.locale, l.title, l.description,
       r.id AS reward_id, r.reward_key, r.reward_type,
       r.quantity AS reward_quantity, r.duration_unit
FROM task_definition t FORCE INDEX (task_definition_visible_user_list_idx)
LEFT JOIN task_localization l ON l.workspace_id = t.workspace_id AND l.task_id = t.id AND l.locale = ?
LEFT JOIN task_reward r ON r.workspace_id = t.workspace_id AND r.task_id = t.id
WHERE t.workspace_id = ? AND t.is_visible = TRUE AND t.is_active = TRUE
  AND t.deleted_at IS NULL
  AND (t.start_at IS NULL OR t.start_at <= ?)
  AND (t.end_at IS NULL OR t.end_at > ?)
ORDER BY t.position, t.id, r.position, r.id
`

type ListActiveTaskBundlesParams struct {
	Locale      string       `json:"locale"`
	WorkspaceID string       `json:"workspace_id"`
	StartAt     sql.NullTime `json:"start_at"`
	EndAt       sql.NullTime `json:"end_at"`
}

type ListActiveTaskBundlesRow struct {
	ID             uint64                     `json:"id"`
	Key            string                     `json:"key"`
	GroupKey       string                     `json:"group_key"`
	ActionKey      string                     `json:"action_key"`
	ActionKind     TaskDefinitionActionKind   `json:"action_kind"`
	ClaimMode      TaskDefinitionClaimMode    `json:"claim_mode"`
	TargetCount    uint64                     `json:"target_count"`
	Payload        json.RawMessage            `json:"payload"`
	ImageUrl       sql.NullString             `json:"image_url"`
	Locale         sql.NullString             `json:"locale"`
	Title          sql.NullString             `json:"title"`
	Description    sql.NullString             `json:"description"`
	RewardID       sql.NullInt64              `json:"reward_id"`
	RewardKey      sql.NullString             `json:"reward_key"`
	RewardType     NullTaskRewardRewardType   `json:"reward_type"`
	RewardQuantity sql.NullInt64              `json:"reward_quantity"`
	DurationUnit   NullTaskRewardDurationUnit `json:"duration_unit"`
}

func (q *Queries) ListActiveTaskBundles(ctx context.Context, arg ListActiveTaskBundlesParams) ([]ListActiveTaskBundlesRow, error) {
	rows, err := q.query(ctx, q.listActiveTaskBundlesStmt, listActiveTaskBundles,
		arg.Locale,
		arg.WorkspaceID,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTaskBundlesRow
	for rows.Next() {
		var i ListActiveTaskBundlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.GroupKey,
			&i.ActionKey,
			&i.ActionKind,
			&i.ClaimMode,
			&i.TargetCount,
			&i.Payload,
			&i.ImageUrl,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.RewardID,
			&i.RewardKey,
			&i.RewardType,
			&i.RewardQuantity,
			&i.DurationUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentProgressForUser = `-- name: ListCurrentProgressForUser :many
SELECT id, workspace_id, task_id, app_id, platform_id, platform_user_id,
       period_start_at, period_end_at, progress, status, ready_at, claimed_at,
       operation_id, COALESCE(rewards_snapshot, JSON_ARRAY()) AS rewards_snapshot, created_at, updated_at
FROM task_progress
WHERE workspace_id = ?
  AND app_id = ?
  AND platform_id = ?
  AND platform_user_id = ?
  AND period_start_at <= ?
  AND period_end_at > ?
`

type ListCurrentProgressForUserParams struct {
	WorkspaceID    string    `json:"workspace_id"`
	AppID          int64     `json:"app_id"`
	PlatformID     int64     `json:"platform_id"`
	PlatformUserID string    `json:"platform_user_id"`
	PeriodStartAt  time.Time `json:"period_start_at"`
	PeriodEndAt    time.Time `json:"period_end_at"`
}

func (q *Queries) ListCurrentProgressForUser(ctx context.Context, arg ListCurrentProgressForUserParams) ([]TaskProgress, error) {
	rows, err := q.query(ctx, q.listCurrentProgressForUserStmt, listCurrentProgressForUser,
		arg.WorkspaceID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.PeriodStartAt,
		arg.PeriodEndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskProgress
	for rows.Next() {
		var i TaskProgress
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TaskID,
			&i.AppID,
			&i.PlatformID,
			&i.PlatformUserID,
			&i.PeriodStartAt,
			&i.PeriodEndAt,
			&i.Progress,
			&i.Status,
			&i.ReadyAt,
			&i.ClaimedAt,
			&i.OperationID,
			&i.RewardsSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentProgressForUserForUpdate = `-- name: ListCurrentProgressForUserForUpdate :many
SELECT id, workspace_id, task_id, app_id, platform_id, platform_user_id,
       period_start_at, period_end_at, progress, status, ready_at, claimed_at,
       operation_id, COALESCE(rewards_snapshot, JSON_ARRAY()) AS rewards_snapshot, created_at, updated_at
FROM task_progress
WHERE workspace_id = ?
  AND app_id = ?
  AND platform_id = ?
  AND platform_user_id = ?
  AND period_start_at <= ?
  AND period_end_at > ?
FOR UPDATE
`

type ListCurrentProgressForUserForUpdateParams struct {
	WorkspaceID    string    `json:"workspace_id"`
	AppID          int64     `json:"app_id"`
	PlatformID     int64     `json:"platform_id"`
	PlatformUserID string    `json:"platform_user_id"`
	PeriodStartAt  time.Time `json:"period_start_at"`
	PeriodEndAt    time.Time `json:"period_end_at"`
}

func (q *Queries) ListCurrentProgressForUserForUpdate(ctx context.Context, arg ListCurrentProgressForUserForUpdateParams) ([]TaskProgress, error) {
	rows, err := q.query(ctx, q.listCurrentProgressForUserForUpdateStmt, listCurrentProgressForUserForUpdate,
		arg.WorkspaceID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.PeriodStartAt,
		arg.PeriodEndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskProgress
	for rows.Next() {
		var i TaskProgress
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TaskID,
			&i.AppID,
			&i.PlatformID,
			&i.PlatformUserID,
			&i.PeriodStartAt,
			&i.PeriodEndAt,
			&i.Progress,
			&i.Status,
			&i.ReadyAt,
			&i.ClaimedAt,
			&i.OperationID,
			&i.RewardsSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordTasks = `-- name: ListRecordTasks :many
SELECT t.id, t.workspace_id, t.` + "`" + `key` + "`" + `, t.group_key, t.sequence_key, t.sequence_position,
       t.action_key, t.action_kind, t.claim_mode, t.target_count, t.reset_unit,
       t.reset_every, t.payload, t.branch_sort_key, t.position
FROM task_definition t FORCE INDEX (task_definition_action_idx)
WHERE t.workspace_id = ?
  AND t.action_key = ?
  AND t.sequence_key IS NULL
  AND t.is_active = TRUE
  AND t.deleted_at IS NULL
  AND (t.start_at IS NULL OR t.start_at <= ?)
  AND (t.end_at IS NULL OR t.end_at > ?)
UNION ALL
SELECT t.id, t.workspace_id, t.` + "`" + `key` + "`" + `, t.group_key, t.sequence_key, t.sequence_position,
       t.action_key, t.action_kind, t.claim_mode, t.target_count, t.reset_unit,
       t.reset_every, t.payload, t.branch_sort_key, t.position
FROM task_sequence_state s
JOIN task_definition t
  ON t.workspace_id = s.workspace_id AND t.id = s.current_task_id
WHERE s.workspace_id = ?
  AND s.app_id = ?
  AND s.platform_id = ?
  AND s.platform_user_id = ?
  AND s.status = 'active'
  AND t.action_key = ?
  AND t.is_active = TRUE
  AND t.deleted_at IS NULL
  AND (t.start_at IS NULL OR t.start_at <= ?)
  AND (t.end_at IS NULL OR t.end_at > ?)
UNION ALL
SELECT t.id, t.workspace_id, t.` + "`" + `key` + "`" + `, t.group_key, t.sequence_key, t.sequence_position,
       t.action_key, t.action_kind, t.claim_mode, t.target_count, t.reset_unit,
       t.reset_every, t.payload, t.branch_sort_key, t.position
FROM task_definition t FORCE INDEX (task_definition_action_idx)
LEFT JOIN task_sequence_state s
  ON s.workspace_id = t.workspace_id
 AND s.sequence_key = t.sequence_key
 AND s.app_id = ?
 AND s.platform_id = ?
 AND s.platform_user_id = ?
WHERE t.workspace_id = ?
  AND t.action_key = ?
  AND t.sequence_key IS NOT NULL
  AND t.sequence_position = 1
  AND s.sequence_key IS NULL
  AND t.is_active = TRUE
  AND t.deleted_at IS NULL
  AND (t.start_at IS NULL OR t.start_at <= ?)
  AND (t.end_at IS NULL OR t.end_at > ?)
ORDER BY branch_sort_key, sequence_position, position, id
`

type ListRecordTasksParams struct {
	WorkspaceID      string       `json:"workspace_id"`
	ActionKey        string       `json:"action_key"`
	StartAt          sql.NullTime `json:"start_at"`
	EndAt            sql.NullTime `json:"end_at"`
	WorkspaceID_2    string       `json:"workspace_id_2"`
	AppID            int64        `json:"app_id"`
	PlatformID       int64        `json:"platform_id"`
	PlatformUserID   string       `json:"platform_user_id"`
	ActionKey_2      string       `json:"action_key_2"`
	StartAt_2        sql.NullTime `json:"start_at_2"`
	EndAt_2          sql.NullTime `json:"end_at_2"`
	AppID_2          int64        `json:"app_id_2"`
	PlatformID_2     int64        `json:"platform_id_2"`
	PlatformUserID_2 string       `json:"platform_user_id_2"`
	WorkspaceID_3    string       `json:"workspace_id_3"`
	ActionKey_3      string       `json:"action_key_3"`
	StartAt_3        sql.NullTime `json:"start_at_3"`
	EndAt_3          sql.NullTime `json:"end_at_3"`
}

type ListRecordTasksRow struct {
	ID               uint64                   `json:"id"`
	WorkspaceID      string                   `json:"workspace_id"`
	Key              string                   `json:"key"`
	GroupKey         string                   `json:"group_key"`
	SequenceKey      sql.NullString           `json:"sequence_key"`
	SequencePosition sql.NullInt32            `json:"sequence_position"`
	ActionKey        string                   `json:"action_key"`
	ActionKind       TaskDefinitionActionKind `json:"action_kind"`
	ClaimMode        TaskDefinitionClaimMode  `json:"claim_mode"`
	TargetCount      uint64                   `json:"target_count"`
	ResetUnit        TaskDefinitionResetUnit  `json:"reset_unit"`
	ResetEvery       uint32                   `json:"reset_every"`
	Payload          json.RawMessage          `json:"payload"`
	BranchSortKey    sql.NullString           `json:"branch_sort_key"`
	Position         int32                    `json:"position"`
}

func (q *Queries) ListRecordTasks(ctx context.Context, arg ListRecordTasksParams) ([]ListRecordTasksRow, error) {
	rows, err := q.query(ctx, q.listRecordTasksStmt, listRecordTasks,
		arg.WorkspaceID,
		arg.ActionKey,
		arg.StartAt,
		arg.EndAt,
		arg.WorkspaceID_2,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.ActionKey_2,
		arg.StartAt_2,
		arg.EndAt_2,
		arg.AppID_2,
		arg.PlatformID_2,
		arg.PlatformUserID_2,
		arg.WorkspaceID_3,
		arg.ActionKey_3,
		arg.StartAt_3,
		arg.EndAt_3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordTasksRow
	for rows.Next() {
		var i ListRecordTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.GroupKey,
			&i.SequenceKey,
			&i.SequencePosition,
			&i.ActionKey,
			&i.ActionKind,
			&i.ClaimMode,
			&i.TargetCount,
			&i.ResetUnit,
			&i.ResetEvery,
			&i.Payload,
			&i.BranchSortKey,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewards = `-- name: ListRewards :many
SELECT id, workspace_id, task_id, reward_key, reward_type, quantity, duration_unit, position, created_at, updated_at
FROM task_reward
WHERE workspace_id = ? AND task_id = ?
ORDER BY position, id
`

type ListRewardsParams struct {
	WorkspaceID string `json:"workspace_id"`
	TaskID      uint64 `json:"task_id"`
}

func (q *Queries) ListRewards(ctx context.Context, arg ListRewardsParams) ([]TaskReward, error) {
	rows, err := q.query(ctx, q.listRewardsStmt, listRewards, arg.WorkspaceID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskReward
	for rows.Next() {
		var i TaskReward
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TaskID,
			&i.RewardKey,
			&i.RewardType,
			&i.Quantity,
			&i.DurationUnit,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTaskDailyOverview = `-- name: RefreshTaskDailyOverview :exec
INSERT INTO task_stats_daily_overview (
    workspace_id,
    stats_date,
    tasks_total,
    active_tasks,
    visible_tasks,
    progress_created,
    progress_amount,
    ready_count,
    claimed_count,
    manual_claimed_count,
    auto_claimed_count,
    unique_participants,
    unique_claimers
)
SELECT
    event_rows.workspace_id,
    event_rows.stats_date,
    definitions.tasks_total,
    definitions.active_tasks,
    definitions.visible_tasks,
    event_rows.progress_created,
    event_rows.progress_amount,
    event_rows.ready_count,
    event_rows.claimed_count,
    event_rows.manual_claimed_count,
    event_rows.auto_claimed_count,
    event_rows.unique_participants,
    event_rows.unique_claimers
FROM (
    SELECT
        workspace_id,
        DATE(occurred_at) AS stats_date,
        SUM(event_type = 'progress_created') AS progress_created,
        SUM(IF(event_type = 'progress_added', amount, 0)) AS progress_amount,
        SUM(event_type = 'ready') AS ready_count,
        SUM(event_type = 'claimed') AS claimed_count,
        SUM(event_type = 'claimed' AND claim_mode = 'manual') AS manual_claimed_count,
        SUM(event_type = 'claimed' AND claim_mode = 'auto') AS auto_claimed_count,
        COUNT(DISTINCT CONCAT_WS(':', app_id, platform_id, platform_user_id)) AS unique_participants,
        COUNT(DISTINCT IF(
            event_type = 'claimed',
            CONCAT_WS(':', app_id, platform_id, platform_user_id),
            NULL
        )) AS unique_claimers
    FROM task_stats_event refresh_events
    WHERE refresh_events.occurred_at >= ? AND refresh_events.occurred_at < ?
    GROUP BY refresh_events.workspace_id, DATE(refresh_events.occurred_at)
) event_rows
JOIN (
    SELECT
        workspace_id,
        COUNT(*) AS tasks_total,
        SUM(
            is_active = TRUE
            AND deleted_at IS NULL
            AND (start_at IS NULL OR start_at <= NOW())
            AND (end_at IS NULL OR end_at > NOW())
        ) AS active_tasks,
        SUM(
            is_visible = TRUE
            AND is_active = TRUE
            AND deleted_at IS NULL
            AND (start_at IS NULL OR start_at <= NOW())
            AND (end_at IS NULL OR end_at > NOW())
        ) AS visible_tasks
    FROM task_definition
    GROUP BY workspace_id
) definitions ON definitions.workspace_id = event_rows.workspace_id
ON DUPLICATE KEY UPDATE
    progress_created = VALUES(progress_created),
    progress_amount = VALUES(progress_amount),
    ready_count = VALUES(ready_count),
    claimed_count = VALUES(claimed_count),
    manual_claimed_count = VALUES(manual_claimed_count),
    auto_claimed_count = VALUES(auto_claimed_count),
    unique_participants = VALUES(unique_participants),
    unique_claimers = VALUES(unique_claimers),
    updated_at = NOW()
`

type RefreshTaskDailyOverviewParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

func (q *Queries) RefreshTaskDailyOverview(ctx context.Context, arg RefreshTaskDailyOverviewParams) error {
	_, err := q.exec(ctx, q.refreshTaskDailyOverviewStmt, refreshTaskDailyOverview, arg.OccurredAt, arg.OccurredAt_2)
	return err
}

const refreshTaskDailyStats = `-- name: RefreshTaskDailyStats :exec
INSERT INTO task_stats_daily (
    workspace_id,
    task_id,
    stats_date,
    progress_created,
    progress_amount,
    ready_count,
    claimed_count,
    manual_claimed_count,
    auto_claimed_count,
    unique_participants,
    unique_claimers
)
SELECT
    workspace_id,
    task_id,
    DATE(occurred_at),
    SUM(event_type = 'progress_created'),
    SUM(IF(event_type = 'progress_added', amount, 0)),
    SUM(event_type = 'ready'),
    SUM(event_type = 'claimed'),
    SUM(event_type = 'claimed' AND claim_mode = 'manual'),
    SUM(event_type = 'claimed' AND claim_mode = 'auto'),
    COUNT(DISTINCT CONCAT_WS(':', app_id, platform_id, platform_user_id)),
    COUNT(DISTINCT IF(
        event_type = 'claimed',
        CONCAT_WS(':', app_id, platform_id, platform_user_id),
        NULL
    ))
FROM task_stats_event
WHERE occurred_at >= ? AND occurred_at < ?
GROUP BY workspace_id, task_id, DATE(occurred_at)
ON DUPLICATE KEY UPDATE
    progress_created = VALUES(progress_created),
    progress_amount = VALUES(progress_amount),
    ready_count = VALUES(ready_count),
    claimed_count = VALUES(claimed_count),
    manual_claimed_count = VALUES(manual_claimed_count),
    auto_claimed_count = VALUES(auto_claimed_count),
    unique_participants = VALUES(unique_participants),
    unique_claimers = VALUES(unique_claimers),
    updated_at = NOW()
`

type RefreshTaskDailyStatsParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

func (q *Queries) RefreshTaskDailyStats(ctx context.Context, arg RefreshTaskDailyStatsParams) error {
	_, err := q.exec(ctx, q.refreshTaskDailyStatsStmt, refreshTaskDailyStats, arg.OccurredAt, arg.OccurredAt_2)
	return err
}

const updateProgress = `-- name: UpdateProgress :execrows
UPDATE task_progress
SET progress = ?, status = ?, ready_at = ?, claimed_at = ?,
    operation_id = ?, rewards_snapshot = ?
WHERE id = ?
`

type UpdateProgressParams struct {
	Progress        uint64             `json:"progress"`
	Status          TaskProgressStatus `json:"status"`
	ReadyAt         sql.NullTime       `json:"ready_at"`
	ClaimedAt       sql.NullTime       `json:"claimed_at"`
	OperationID     sql.NullString     `json:"operation_id"`
	RewardsSnapshot json.RawMessage    `json:"rewards_snapshot"`
	ID              uint64             `json:"id"`
}

func (q *Queries) UpdateProgress(ctx context.Context, arg UpdateProgressParams) (int64, error) {
	result, err := q.exec(ctx, q.updateProgressStmt, updateProgress,
		arg.Progress,
		arg.Status,
		arg.ReadyAt,
		arg.ClaimedAt,
		arg.OperationID,
		arg.RewardsSnapshot,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSequenceState = `-- name: UpsertSequenceState :exec
INSERT INTO task_sequence_state (
    workspace_id, sequence_key, app_id, platform_id, platform_user_id,
    current_task_id, status
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    current_task_id = VALUES(current_task_id),
    status = VALUES(status)
`

type UpsertSequenceStateParams struct {
	WorkspaceID    string                  `json:"workspace_id"`
	SequenceKey    string                  `json:"sequence_key"`
	AppID          int64                   `json:"app_id"`
	PlatformID     int64                   `json:"platform_id"`
	PlatformUserID string                  `json:"platform_user_id"`
	CurrentTaskID  sql.NullInt64           `json:"current_task_id"`
	Status         TaskSequenceStateStatus `json:"status"`
}

func (q *Queries) UpsertSequenceState(ctx context.Context, arg UpsertSequenceStateParams) error {
	_, err := q.exec(ctx, q.upsertSequenceStateStmt, upsertSequenceState,
		arg.WorkspaceID,
		arg.SequenceKey,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.CurrentTaskID,
		arg.Status,
	)
	return err
}
