// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const adminCreateCalendar = `-- name: AdminCreateCalendar :exec
INSERT INTO calendar_definition (
    id, workspace_id, type, mode, interval_type, interval_unit,
    interval_count, reset_after_intervals, end_behavior, timezone,
    hide_future_rewards, is_active, start_at, end_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AdminCreateCalendarParams struct {
	ID                  string                         `json:"id"`
	WorkspaceID         string                         `json:"workspace_id"`
	Type                string                         `json:"type"`
	Mode                CalendarDefinitionMode         `json:"mode"`
	IntervalType        CalendarDefinitionIntervalType `json:"interval_type"`
	IntervalUnit        CalendarDefinitionIntervalUnit `json:"interval_unit"`
	IntervalCount       uint32                         `json:"interval_count"`
	ResetAfterIntervals uint32                         `json:"reset_after_intervals"`
	EndBehavior         CalendarDefinitionEndBehavior  `json:"end_behavior"`
	Timezone            string                         `json:"timezone"`
	HideFutureRewards   bool                           `json:"hide_future_rewards"`
	IsActive            bool                           `json:"is_active"`
	StartAt             sql.NullTime                   `json:"start_at"`
	EndAt               sql.NullTime                   `json:"end_at"`
}

func (q *Queries) AdminCreateCalendar(ctx context.Context, arg AdminCreateCalendarParams) error {
	_, err := q.exec(ctx, q.adminCreateCalendarStmt, adminCreateCalendar,
		arg.ID,
		arg.WorkspaceID,
		arg.Type,
		arg.Mode,
		arg.IntervalType,
		arg.IntervalUnit,
		arg.IntervalCount,
		arg.ResetAfterIntervals,
		arg.EndBehavior,
		arg.Timezone,
		arg.HideFutureRewards,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
	)
	return err
}

const adminCreateStep = `-- name: AdminCreateStep :execlastid
INSERT INTO calendar_step (workspace_id, calendar_id, position)
VALUES (?, ?, ?)
`

type AdminCreateStepParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
	Position    uint32 `json:"position"`
}

func (q *Queries) AdminCreateStep(ctx context.Context, arg AdminCreateStepParams) (int64, error) {
	result, err := q.exec(ctx, q.adminCreateStepStmt, adminCreateStep, arg.WorkspaceID, arg.CalendarID, arg.Position)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const adminDeleteLocalization = `-- name: AdminDeleteLocalization :execrows
DELETE FROM calendar_localization
WHERE workspace_id = ? AND calendar_id = ? AND locale = ?
`

type AdminDeleteLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminDeleteLocalization(ctx context.Context, arg AdminDeleteLocalizationParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteLocalizationStmt, adminDeleteLocalization, arg.WorkspaceID, arg.CalendarID, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteReward = `-- name: AdminDeleteReward :execrows
DELETE FROM calendar_reward
WHERE workspace_id = ? AND calendar_id = ? AND id = ?
`

type AdminDeleteRewardParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) AdminDeleteReward(ctx context.Context, arg AdminDeleteRewardParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteRewardStmt, adminDeleteReward, arg.WorkspaceID, arg.CalendarID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteStep = `-- name: AdminDeleteStep :execrows
DELETE FROM calendar_step
WHERE workspace_id = ? AND calendar_id = ? AND id = ?
`

type AdminDeleteStepParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) AdminDeleteStep(ctx context.Context, arg AdminDeleteStepParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteStepStmt, adminDeleteStep, arg.WorkspaceID, arg.CalendarID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminGetCalendar = `-- name: AdminGetCalendar :one
SELECT id, workspace_id, type, mode, interval_type, interval_unit, interval_count, reset_after_intervals, end_behavior, timezone, hide_future_rewards, is_active, start_at, end_at, deleted_at, created_at, updated_at
FROM calendar_definition
WHERE workspace_id = ? AND id = ?
LIMIT 1
`

type AdminGetCalendarParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) AdminGetCalendar(ctx context.Context, arg AdminGetCalendarParams) (CalendarDefinition, error) {
	row := q.queryRow(ctx, q.adminGetCalendarStmt, adminGetCalendar, arg.WorkspaceID, arg.ID)
	var i CalendarDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Mode,
		&i.IntervalType,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.ResetAfterIntervals,
		&i.EndBehavior,
		&i.Timezone,
		&i.HideFutureRewards,
		&i.IsActive,
		&i.StartAt,
		&i.EndAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetLocalization = `-- name: AdminGetLocalization :one
SELECT workspace_id, calendar_id, locale, title, description, created_at, updated_at
FROM calendar_localization
WHERE workspace_id = ? AND calendar_id = ? AND locale = ?
LIMIT 1
`

type AdminGetLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminGetLocalization(ctx context.Context, arg AdminGetLocalizationParams) (CalendarLocalization, error) {
	row := q.queryRow(ctx, q.adminGetLocalizationStmt, adminGetLocalization, arg.WorkspaceID, arg.CalendarID, arg.Locale)
	var i CalendarLocalization
	err := row.Scan(
		&i.WorkspaceID,
		&i.CalendarID,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetReward = `-- name: AdminGetReward :one
SELECT id, workspace_id, calendar_id, step_id, item_key, reward_type, item_count, duration_unit, position, created_at, updated_at
FROM calendar_reward
WHERE workspace_id = ? AND calendar_id = ? AND id = ?
LIMIT 1
`

type AdminGetRewardParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) AdminGetReward(ctx context.Context, arg AdminGetRewardParams) (CalendarReward, error) {
	row := q.queryRow(ctx, q.adminGetRewardStmt, adminGetReward, arg.WorkspaceID, arg.CalendarID, arg.ID)
	var i CalendarReward
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CalendarID,
		&i.StepID,
		&i.ItemKey,
		&i.RewardType,
		&i.ItemCount,
		&i.DurationUnit,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetStats = `-- name: AdminGetStats :one
SELECT
    COUNT(*) AS operation_count,
    COALESCE(SUM(granted), 0) AS grant_count,
    COUNT(DISTINCT CONCAT_WS(':', app_id, platform_id, platform_user_id)) AS unique_users
FROM calendar_operation
WHERE workspace_id = ? AND calendar_id = ?
`

type AdminGetStatsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
}

type AdminGetStatsRow struct {
	OperationCount int64       `json:"operation_count"`
	GrantCount     interface{} `json:"grant_count"`
	UniqueUsers    int64       `json:"unique_users"`
}

func (q *Queries) AdminGetStats(ctx context.Context, arg AdminGetStatsParams) (AdminGetStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetStatsStmt, adminGetStats, arg.WorkspaceID, arg.CalendarID)
	var i AdminGetStatsRow
	err := row.Scan(&i.OperationCount, &i.GrantCount, &i.UniqueUsers)
	return i, err
}

const adminListCalendars = `-- name: AdminListCalendars :many
SELECT id, workspace_id, type, mode, interval_type, interval_unit, interval_count, reset_after_intervals, end_behavior, timezone, hide_future_rewards, is_active, start_at, end_at, deleted_at, created_at, updated_at
FROM calendar_definition
WHERE workspace_id = ?
ORDER BY created_at DESC, id
LIMIT ? OFFSET ?
`

type AdminListCalendarsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) AdminListCalendars(ctx context.Context, arg AdminListCalendarsParams) ([]CalendarDefinition, error) {
	rows, err := q.query(ctx, q.adminListCalendarsStmt, adminListCalendars, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarDefinition
	for rows.Next() {
		var i CalendarDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Mode,
			&i.IntervalType,
			&i.IntervalUnit,
			&i.IntervalCount,
			&i.ResetAfterIntervals,
			&i.EndBehavior,
			&i.Timezone,
			&i.HideFutureRewards,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListDailyStats = `-- name: AdminListDailyStats :many
SELECT workspace_id, calendar_id, stats_date, operation_count, grant_count, unique_users, updated_at
FROM calendar_stats_daily
WHERE workspace_id = ?
  AND calendar_id = ?
  AND stats_date >= ?
  AND stats_date <= ?
ORDER BY stats_date
`

type AdminListDailyStatsParams struct {
	WorkspaceID string    `json:"workspace_id"`
	CalendarID  string    `json:"calendar_id"`
	StatsDate   time.Time `json:"stats_date"`
	StatsDate_2 time.Time `json:"stats_date_2"`
}

func (q *Queries) AdminListDailyStats(ctx context.Context, arg AdminListDailyStatsParams) ([]CalendarStatsDaily, error) {
	rows, err := q.query(ctx, q.adminListDailyStatsStmt, adminListDailyStats,
		arg.WorkspaceID,
		arg.CalendarID,
		arg.StatsDate,
		arg.StatsDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarStatsDaily
	for rows.Next() {
		var i CalendarStatsDaily
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CalendarID,
			&i.StatsDate,
			&i.OperationCount,
			&i.GrantCount,
			&i.UniqueUsers,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListLocalizations = `-- name: AdminListLocalizations :many
SELECT workspace_id, calendar_id, locale, title, description, created_at, updated_at
FROM calendar_localization
WHERE workspace_id = ? AND calendar_id = ?
ORDER BY locale
`

type AdminListLocalizationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
}

func (q *Queries) AdminListLocalizations(ctx context.Context, arg AdminListLocalizationsParams) ([]CalendarLocalization, error) {
	rows, err := q.query(ctx, q.adminListLocalizationsStmt, adminListLocalizations, arg.WorkspaceID, arg.CalendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarLocalization
	for rows.Next() {
		var i CalendarLocalization
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CalendarID,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOperations = `-- name: AdminListOperations :many
SELECT id, workspace_id, calendar_id, app_id, platform_id, platform_user_id, operation_id, granted, status, position, rewards_snapshot, current_position, claim_count, last_claim_position, last_claim_at, next_claim_at, is_completed, reset_count, was_reset, occurred_at, created_at
FROM calendar_operation
WHERE workspace_id = ? AND calendar_id = ?
ORDER BY occurred_at DESC, id DESC
LIMIT ? OFFSET ?
`

type AdminListOperationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) AdminListOperations(ctx context.Context, arg AdminListOperationsParams) ([]CalendarOperation, error) {
	rows, err := q.query(ctx, q.adminListOperationsStmt, adminListOperations,
		arg.WorkspaceID,
		arg.CalendarID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarOperation
	for rows.Next() {
		var i CalendarOperation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CalendarID,
			&i.AppID,
			&i.PlatformID,
			&i.PlatformUserID,
			&i.OperationID,
			&i.Granted,
			&i.Status,
			&i.Position,
			&i.RewardsSnapshot,
			&i.CurrentPosition,
			&i.ClaimCount,
			&i.LastClaimPosition,
			&i.LastClaimAt,
			&i.NextClaimAt,
			&i.IsCompleted,
			&i.ResetCount,
			&i.WasReset,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetCalendarActive = `-- name: AdminSetCalendarActive :execrows
UPDATE calendar_definition
SET is_active = ?
WHERE workspace_id = ? AND id = ? AND deleted_at IS NULL
`

type AdminSetCalendarActiveParams struct {
	IsActive    bool   `json:"is_active"`
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) AdminSetCalendarActive(ctx context.Context, arg AdminSetCalendarActiveParams) (int64, error) {
	result, err := q.exec(ctx, q.adminSetCalendarActiveStmt, adminSetCalendarActive, arg.IsActive, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminSoftDeleteCalendar = `-- name: AdminSoftDeleteCalendar :execrows
UPDATE calendar_definition
SET deleted_at = NOW(), is_active = FALSE
WHERE workspace_id = ? AND id = ? AND deleted_at IS NULL
`

type AdminSoftDeleteCalendarParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) AdminSoftDeleteCalendar(ctx context.Context, arg AdminSoftDeleteCalendarParams) (int64, error) {
	result, err := q.exec(ctx, q.adminSoftDeleteCalendarStmt, adminSoftDeleteCalendar, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpdateCalendar = `-- name: AdminUpdateCalendar :execrows
UPDATE calendar_definition
SET type = ?,
    mode = ?,
    interval_type = ?,
    interval_unit = ?,
    interval_count = ?,
    reset_after_intervals = ?,
    end_behavior = ?,
    timezone = ?,
    hide_future_rewards = ?,
    is_active = ?,
    start_at = ?,
    end_at = ?
WHERE workspace_id = ? AND id = ? AND deleted_at IS NULL
`

type AdminUpdateCalendarParams struct {
	Type                string                         `json:"type"`
	Mode                CalendarDefinitionMode         `json:"mode"`
	IntervalType        CalendarDefinitionIntervalType `json:"interval_type"`
	IntervalUnit        CalendarDefinitionIntervalUnit `json:"interval_unit"`
	IntervalCount       uint32                         `json:"interval_count"`
	ResetAfterIntervals uint32                         `json:"reset_after_intervals"`
	EndBehavior         CalendarDefinitionEndBehavior  `json:"end_behavior"`
	Timezone            string                         `json:"timezone"`
	HideFutureRewards   bool                           `json:"hide_future_rewards"`
	IsActive            bool                           `json:"is_active"`
	StartAt             sql.NullTime                   `json:"start_at"`
	EndAt               sql.NullTime                   `json:"end_at"`
	WorkspaceID         string                         `json:"workspace_id"`
	ID                  string                         `json:"id"`
}

func (q *Queries) AdminUpdateCalendar(ctx context.Context, arg AdminUpdateCalendarParams) (int64, error) {
	result, err := q.exec(ctx, q.adminUpdateCalendarStmt, adminUpdateCalendar,
		arg.Type,
		arg.Mode,
		arg.IntervalType,
		arg.IntervalUnit,
		arg.IntervalCount,
		arg.ResetAfterIntervals,
		arg.EndBehavior,
		arg.Timezone,
		arg.HideFutureRewards,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpdateReward = `-- name: AdminUpdateReward :execrows
UPDATE calendar_reward
SET step_id = ?,
    item_key = ?,
    reward_type = ?,
    item_count = ?,
    duration_unit = ?,
    position = ?
WHERE workspace_id = ? AND calendar_id = ? AND id = ?
`

type AdminUpdateRewardParams struct {
	StepID       uint64                         `json:"step_id"`
	ItemKey      string                         `json:"item_key"`
	RewardType   CalendarRewardRewardType       `json:"reward_type"`
	ItemCount    int64                          `json:"item_count"`
	DurationUnit NullCalendarRewardDurationUnit `json:"duration_unit"`
	Position     uint32                         `json:"position"`
	WorkspaceID  string                         `json:"workspace_id"`
	CalendarID   string                         `json:"calendar_id"`
	ID           uint64                         `json:"id"`
}

func (q *Queries) AdminUpdateReward(ctx context.Context, arg AdminUpdateRewardParams) (int64, error) {
	result, err := q.exec(ctx, q.adminUpdateRewardStmt, adminUpdateReward,
		arg.StepID,
		arg.ItemKey,
		arg.RewardType,
		arg.ItemCount,
		arg.DurationUnit,
		arg.Position,
		arg.WorkspaceID,
		arg.CalendarID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpdateStep = `-- name: AdminUpdateStep :execrows
UPDATE calendar_step
SET position = ?
WHERE workspace_id = ? AND calendar_id = ? AND id = ?
`

type AdminUpdateStepParams struct {
	Position    uint32 `json:"position"`
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) AdminUpdateStep(ctx context.Context, arg AdminUpdateStepParams) (int64, error) {
	result, err := q.exec(ctx, q.adminUpdateStepStmt, adminUpdateStep,
		arg.Position,
		arg.WorkspaceID,
		arg.CalendarID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpsertLocalization = `-- name: AdminUpsertLocalization :exec
INSERT INTO calendar_localization (
    workspace_id, calendar_id, locale, title, description
) VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    description = VALUES(description)
`

type AdminUpsertLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	CalendarID  string `json:"calendar_id"`
	Locale      string `json:"locale"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) AdminUpsertLocalization(ctx context.Context, arg AdminUpsertLocalizationParams) error {
	_, err := q.exec(ctx, q.adminUpsertLocalizationStmt, adminUpsertLocalization,
		arg.WorkspaceID,
		arg.CalendarID,
		arg.Locale,
		arg.Title,
		arg.Description,
	)
	return err
}

const adminUpsertReward = `-- name: AdminUpsertReward :execlastid
INSERT INTO calendar_reward (
    workspace_id, calendar_id, step_id, item_key,
    reward_type, item_count, duration_unit, position
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    id = LAST_INSERT_ID(id),
    reward_type = VALUES(reward_type),
    item_count = VALUES(item_count),
    duration_unit = VALUES(duration_unit),
    position = VALUES(position)
`

type AdminUpsertRewardParams struct {
	WorkspaceID  string                         `json:"workspace_id"`
	CalendarID   string                         `json:"calendar_id"`
	StepID       uint64                         `json:"step_id"`
	ItemKey      string                         `json:"item_key"`
	RewardType   CalendarRewardRewardType       `json:"reward_type"`
	ItemCount    int64                          `json:"item_count"`
	DurationUnit NullCalendarRewardDurationUnit `json:"duration_unit"`
	Position     uint32                         `json:"position"`
}

func (q *Queries) AdminUpsertReward(ctx context.Context, arg AdminUpsertRewardParams) (int64, error) {
	result, err := q.exec(ctx, q.adminUpsertRewardStmt, adminUpsertReward,
		arg.WorkspaceID,
		arg.CalendarID,
		arg.StepID,
		arg.ItemKey,
		arg.RewardType,
		arg.ItemCount,
		arg.DurationUnit,
		arg.Position,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createOperation = `-- name: CreateOperation :execlastid
INSERT INTO calendar_operation (
    workspace_id, calendar_id, app_id, platform_id, platform_user_id,
    operation_id, granted, status, position, rewards_snapshot,
    current_position, claim_count, last_claim_position, last_claim_at,
    next_claim_at, is_completed, reset_count, was_reset, occurred_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOperationParams struct {
	WorkspaceID       string          `json:"workspace_id"`
	CalendarID        string          `json:"calendar_id"`
	AppID             int64           `json:"app_id"`
	PlatformID        int64           `json:"platform_id"`
	PlatformUserID    string          `json:"platform_user_id"`
	OperationID       string          `json:"operation_id"`
	Granted           bool            `json:"granted"`
	Status            string          `json:"status"`
	Position          sql.NullInt32   `json:"position"`
	RewardsSnapshot   json.RawMessage `json:"rewards_snapshot"`
	CurrentPosition   uint32          `json:"current_position"`
	ClaimCount        uint64          `json:"claim_count"`
	LastClaimPosition sql.NullInt32   `json:"last_claim_position"`
	LastClaimAt       sql.NullTime    `json:"last_claim_at"`
	NextClaimAt       sql.NullTime    `json:"next_claim_at"`
	IsCompleted       bool            `json:"is_completed"`
	ResetCount        uint64          `json:"reset_count"`
	WasReset          bool            `json:"was_reset"`
	OccurredAt        time.Time       `json:"occurred_at"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (int64, error) {
	result, err := q.exec(ctx, q.createOperationStmt, createOperation,
		arg.WorkspaceID,
		arg.CalendarID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.OperationID,
		arg.Granted,
		arg.Status,
		arg.Position,
		arg.RewardsSnapshot,
		arg.CurrentPosition,
		arg.ClaimCount,
		arg.LastClaimPosition,
		arg.LastClaimAt,
		arg.NextClaimAt,
		arg.IsCompleted,
		arg.ResetCount,
		arg.WasReset,
		arg.OccurredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getCalendarBundle = `-- name: GetCalendarBundle :many
SELECT
    c.id,
    c.workspace_id,
    c.type,
    c.mode,
    c.interval_type,
    c.interval_unit,
    c.interval_count,
    c.reset_after_intervals,
    c.end_behavior,
    c.timezone,
    c.hide_future_rewards,
    c.is_active,
    c.start_at,
    c.end_at,
    c.deleted_at,
    c.created_at,
    c.updated_at,
    l.locale AS localization_locale,
    l.title AS localization_title,
    l.description AS localization_description,
    s.id AS step_id,
    s.position AS step_position,
    r.id AS reward_id,
    r.item_key AS reward_item_key,
    r.reward_type AS reward_type,
    r.item_count AS reward_item_count,
    r.duration_unit AS reward_duration_unit,
    r.position AS reward_position
FROM calendar_definition c
LEFT JOIN calendar_localization l
  ON l.workspace_id = c.workspace_id
 AND l.calendar_id = c.id
 AND l.locale = ?
LEFT JOIN calendar_step s
  ON s.workspace_id = c.workspace_id
 AND s.calendar_id = c.id
LEFT JOIN calendar_reward r
  ON r.workspace_id = s.workspace_id
 AND r.calendar_id = s.calendar_id
 AND r.step_id = s.id
WHERE c.workspace_id = ?
  AND (c.id = ? OR c.type = ?)
ORDER BY s.position, r.position, r.id
`

type GetCalendarBundleParams struct {
	Locale      string `json:"locale"`
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
	Type        string `json:"type"`
}

type GetCalendarBundleRow struct {
	ID                      string                         `json:"id"`
	WorkspaceID             string                         `json:"workspace_id"`
	Type                    string                         `json:"type"`
	Mode                    CalendarDefinitionMode         `json:"mode"`
	IntervalType            CalendarDefinitionIntervalType `json:"interval_type"`
	IntervalUnit            CalendarDefinitionIntervalUnit `json:"interval_unit"`
	IntervalCount           uint32                         `json:"interval_count"`
	ResetAfterIntervals     uint32                         `json:"reset_after_intervals"`
	EndBehavior             CalendarDefinitionEndBehavior  `json:"end_behavior"`
	Timezone                string                         `json:"timezone"`
	HideFutureRewards       bool                           `json:"hide_future_rewards"`
	IsActive                bool                           `json:"is_active"`
	StartAt                 sql.NullTime                   `json:"start_at"`
	EndAt                   sql.NullTime                   `json:"end_at"`
	DeletedAt               sql.NullTime                   `json:"deleted_at"`
	CreatedAt               time.Time                      `json:"created_at"`
	UpdatedAt               time.Time                      `json:"updated_at"`
	LocalizationLocale      sql.NullString                 `json:"localization_locale"`
	LocalizationTitle       sql.NullString                 `json:"localization_title"`
	LocalizationDescription sql.NullString                 `json:"localization_description"`
	StepID                  sql.NullInt64                  `json:"step_id"`
	StepPosition            sql.NullInt32                  `json:"step_position"`
	RewardID                sql.NullInt64                  `json:"reward_id"`
	RewardItemKey           sql.NullString                 `json:"reward_item_key"`
	RewardType              NullCalendarRewardRewardType   `json:"reward_type"`
	RewardItemCount         sql.NullInt64                  `json:"reward_item_count"`
	RewardDurationUnit      NullCalendarRewardDurationUnit `json:"reward_duration_unit"`
	RewardPosition          sql.NullInt32                  `json:"reward_position"`
}

func (q *Queries) GetCalendarBundle(ctx context.Context, arg GetCalendarBundleParams) ([]GetCalendarBundleRow, error) {
	rows, err := q.query(ctx, q.getCalendarBundleStmt, getCalendarBundle,
		arg.Locale,
		arg.WorkspaceID,
		arg.ID,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCalendarBundleRow
	for rows.Next() {
		var i GetCalendarBundleRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Mode,
			&i.IntervalType,
			&i.IntervalUnit,
			&i.IntervalCount,
			&i.ResetAfterIntervals,
			&i.EndBehavior,
			&i.Timezone,
			&i.HideFutureRewards,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocalizationLocale,
			&i.LocalizationTitle,
			&i.LocalizationDescription,
			&i.StepID,
			&i.StepPosition,
			&i.RewardID,
			&i.RewardItemKey,
			&i.RewardType,
			&i.RewardItemCount,
			&i.RewardDurationUnit,
			&i.RewardPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgress = `-- name: GetProgress :one
SELECT workspace_id, calendar_id, app_id, platform_id, platform_user_id, current_position, claim_count, last_claim_position, last_claim_at, next_claim_at, is_completed, reset_count, last_was_reset, created_at, updated_at
FROM calendar_progress
WHERE workspace_id = ?
  AND calendar_id = ?
  AND app_id = ?
  AND platform_id = ?
  AND platform_user_id = ?
LIMIT 1
`

type GetProgressParams struct {
	WorkspaceID    string `json:"workspace_id"`
	CalendarID     string `json:"calendar_id"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) GetProgress(ctx context.Context, arg GetProgressParams) (CalendarProgress, error) {
	row := q.queryRow(ctx, q.getProgressStmt, getProgress,
		arg.WorkspaceID,
		arg.CalendarID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
	)
	var i CalendarProgress
	err := row.Scan(
		&i.WorkspaceID,
		&i.CalendarID,
		&i.AppID,
		&i.PlatformID,
		&i.PlatformUserID,
		&i.CurrentPosition,
		&i.ClaimCount,
		&i.LastClaimPosition,
		&i.LastClaimAt,
		&i.NextClaimAt,
		&i.IsCompleted,
		&i.ResetCount,
		&i.LastWasReset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecordBundleForUpdate = `-- name: GetRecordBundleForUpdate :many
SELECT
    c.id,
    c.workspace_id,
    c.type,
    c.mode,
    c.interval_type,
    c.interval_unit,
    c.interval_count,
    c.reset_after_intervals,
    c.end_behavior,
    c.timezone,
    c.hide_future_rewards,
    c.is_active,
    c.start_at,
    c.end_at,
    c.deleted_at,
    c.created_at,
    c.updated_at,
    p.current_position,
    p.claim_count,
    p.last_claim_position,
    p.last_claim_at,
    p.next_claim_at,
    p.is_completed,
    p.reset_count,
    p.last_was_reset,
    o.id AS operation_row_id,
    o.operation_id AS existing_operation_id,
    o.granted AS operation_granted,
    o.status AS operation_status,
    o.position AS operation_position,
    COALESCE(o.rewards_snapshot, JSON_ARRAY()) AS operation_rewards_snapshot,
    o.current_position AS operation_current_position,
    o.claim_count AS operation_claim_count,
    o.last_claim_position AS operation_last_claim_position,
    o.last_claim_at AS operation_last_claim_at,
    o.next_claim_at AS operation_next_claim_at,
    o.is_completed AS operation_is_completed,
    o.reset_count AS operation_reset_count,
    o.was_reset AS operation_was_reset,
    o.occurred_at AS operation_occurred_at,
    s.id AS step_id,
    s.position AS step_position,
    r.id AS reward_id,
    r.item_key AS reward_item_key,
    r.reward_type AS reward_type,
    r.item_count AS reward_item_count,
    r.duration_unit AS reward_duration_unit,
    r.position AS reward_position
FROM calendar_definition c
LEFT JOIN calendar_progress p
  ON p.workspace_id = c.workspace_id
 AND p.calendar_id = c.id
 AND p.app_id = ?
 AND p.platform_id = ?
 AND p.platform_user_id = ?
LEFT JOIN calendar_operation o
  ON o.workspace_id = c.workspace_id
 AND o.calendar_id = c.id
 AND o.app_id = ?
 AND o.platform_id = ?
 AND o.platform_user_id = ?
 AND o.operation_id = ?
LEFT JOIN calendar_step s
  ON s.workspace_id = c.workspace_id
 AND s.calendar_id = c.id
LEFT JOIN calendar_reward r
  ON r.workspace_id = s.workspace_id
 AND r.calendar_id = s.calendar_id
 AND r.step_id = s.id
WHERE c.workspace_id = ?
  AND (c.id = ? OR c.type = ?)
ORDER BY s.position, r.position, r.id
FOR UPDATE
`

type GetRecordBundleForUpdateParams struct {
	AppID            int64  `json:"app_id"`
	PlatformID       int64  `json:"platform_id"`
	PlatformUserID   string `json:"platform_user_id"`
	AppID_2          int64  `json:"app_id_2"`
	PlatformID_2     int64  `json:"platform_id_2"`
	PlatformUserID_2 string `json:"platform_user_id_2"`
	OperationID      string `json:"operation_id"`
	WorkspaceID      string `json:"workspace_id"`
	ID               string `json:"id"`
	Type             string `json:"type"`
}

type GetRecordBundleForUpdateRow struct {
	ID                         string                         `json:"id"`
	WorkspaceID                string                         `json:"workspace_id"`
	Type                       string                         `json:"type"`
	Mode                       CalendarDefinitionMode         `json:"mode"`
	IntervalType               CalendarDefinitionIntervalType `json:"interval_type"`
	IntervalUnit               CalendarDefinitionIntervalUnit `json:"interval_unit"`
	IntervalCount              uint32                         `json:"interval_count"`
	ResetAfterIntervals        uint32                         `json:"reset_after_intervals"`
	EndBehavior                CalendarDefinitionEndBehavior  `json:"end_behavior"`
	Timezone                   string                         `json:"timezone"`
	HideFutureRewards          bool                           `json:"hide_future_rewards"`
	IsActive                   bool                           `json:"is_active"`
	StartAt                    sql.NullTime                   `json:"start_at"`
	EndAt                      sql.NullTime                   `json:"end_at"`
	DeletedAt                  sql.NullTime                   `json:"deleted_at"`
	CreatedAt                  time.Time                      `json:"created_at"`
	UpdatedAt                  time.Time                      `json:"updated_at"`
	CurrentPosition            sql.NullInt32                  `json:"current_position"`
	ClaimCount                 sql.NullInt64                  `json:"claim_count"`
	LastClaimPosition          sql.NullInt32                  `json:"last_claim_position"`
	LastClaimAt                sql.NullTime                   `json:"last_claim_at"`
	NextClaimAt                sql.NullTime                   `json:"next_claim_at"`
	IsCompleted                sql.NullBool                   `json:"is_completed"`
	ResetCount                 sql.NullInt64                  `json:"reset_count"`
	LastWasReset               sql.NullBool                   `json:"last_was_reset"`
	OperationRowID             sql.NullInt64                  `json:"operation_row_id"`
	ExistingOperationID        sql.NullString                 `json:"existing_operation_id"`
	OperationGranted           sql.NullBool                   `json:"operation_granted"`
	OperationStatus            sql.NullString                 `json:"operation_status"`
	OperationPosition          sql.NullInt32                  `json:"operation_position"`
	OperationRewardsSnapshot   json.RawMessage                `json:"operation_rewards_snapshot"`
	OperationCurrentPosition   sql.NullInt32                  `json:"operation_current_position"`
	OperationClaimCount        sql.NullInt64                  `json:"operation_claim_count"`
	OperationLastClaimPosition sql.NullInt32                  `json:"operation_last_claim_position"`
	OperationLastClaimAt       sql.NullTime                   `json:"operation_last_claim_at"`
	OperationNextClaimAt       sql.NullTime                   `json:"operation_next_claim_at"`
	OperationIsCompleted       sql.NullBool                   `json:"operation_is_completed"`
	OperationResetCount        sql.NullInt64                  `json:"operation_reset_count"`
	OperationWasReset          sql.NullBool                   `json:"operation_was_reset"`
	OperationOccurredAt        sql.NullTime                   `json:"operation_occurred_at"`
	StepID                     sql.NullInt64                  `json:"step_id"`
	StepPosition               sql.NullInt32                  `json:"step_position"`
	RewardID                   sql.NullInt64                  `json:"reward_id"`
	RewardItemKey              sql.NullString                 `json:"reward_item_key"`
	RewardType                 NullCalendarRewardRewardType   `json:"reward_type"`
	RewardItemCount            sql.NullInt64                  `json:"reward_item_count"`
	RewardDurationUnit         NullCalendarRewardDurationUnit `json:"reward_duration_unit"`
	RewardPosition             sql.NullInt32                  `json:"reward_position"`
}

func (q *Queries) GetRecordBundleForUpdate(ctx context.Context, arg GetRecordBundleForUpdateParams) ([]GetRecordBundleForUpdateRow, error) {
	rows, err := q.query(ctx, q.getRecordBundleForUpdateStmt, getRecordBundleForUpdate,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.AppID_2,
		arg.PlatformID_2,
		arg.PlatformUserID_2,
		arg.OperationID,
		arg.WorkspaceID,
		arg.ID,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecordBundleForUpdateRow
	for rows.Next() {
		var i GetRecordBundleForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Mode,
			&i.IntervalType,
			&i.IntervalUnit,
			&i.IntervalCount,
			&i.ResetAfterIntervals,
			&i.EndBehavior,
			&i.Timezone,
			&i.HideFutureRewards,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentPosition,
			&i.ClaimCount,
			&i.LastClaimPosition,
			&i.LastClaimAt,
			&i.NextClaimAt,
			&i.IsCompleted,
			&i.ResetCount,
			&i.LastWasReset,
			&i.OperationRowID,
			&i.ExistingOperationID,
			&i.OperationGranted,
			&i.OperationStatus,
			&i.OperationPosition,
			&i.OperationRewardsSnapshot,
			&i.OperationCurrentPosition,
			&i.OperationClaimCount,
			&i.OperationLastClaimPosition,
			&i.OperationLastClaimAt,
			&i.OperationNextClaimAt,
			&i.OperationIsCompleted,
			&i.OperationResetCount,
			&i.OperationWasReset,
			&i.OperationOccurredAt,
			&i.StepID,
			&i.StepPosition,
			&i.RewardID,
			&i.RewardItemKey,
			&i.RewardType,
			&i.RewardItemCount,
			&i.RewardDurationUnit,
			&i.RewardPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCalendars = `-- name: ListActiveCalendars :many
SELECT
    c.id,
    c.workspace_id,
    c.type,
    c.mode,
    c.is_active,
    c.start_at,
    c.end_at,
    l.locale,
    l.title,
    l.description
FROM calendar_definition c
LEFT JOIN calendar_localization l
  ON l.workspace_id = c.workspace_id
 AND l.calendar_id = c.id
 AND l.locale = ?
WHERE c.workspace_id = ?
  AND c.is_active = TRUE
  AND c.deleted_at IS NULL
  AND (c.start_at IS NULL OR c.start_at <= ?)
  AND (c.end_at IS NULL OR c.end_at > ?)
ORDER BY c.created_at DESC, c.id
`

type ListActiveCalendarsParams struct {
	Locale      string       `json:"locale"`
	WorkspaceID string       `json:"workspace_id"`
	StartAt     sql.NullTime `json:"start_at"`
	EndAt       sql.NullTime `json:"end_at"`
}

type ListActiveCalendarsRow struct {
	ID          string                 `json:"id"`
	WorkspaceID string                 `json:"workspace_id"`
	Type        string                 `json:"type"`
	Mode        CalendarDefinitionMode `json:"mode"`
	IsActive    bool                   `json:"is_active"`
	StartAt     sql.NullTime           `json:"start_at"`
	EndAt       sql.NullTime           `json:"end_at"`
	Locale      sql.NullString         `json:"locale"`
	Title       sql.NullString         `json:"title"`
	Description sql.NullString         `json:"description"`
}

func (q *Queries) ListActiveCalendars(ctx context.Context, arg ListActiveCalendarsParams) ([]ListActiveCalendarsRow, error) {
	rows, err := q.query(ctx, q.listActiveCalendarsStmt, listActiveCalendars,
		arg.Locale,
		arg.WorkspaceID,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCalendarsRow
	for rows.Next() {
		var i ListActiveCalendarsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Mode,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.Locale,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshDailyStats = `-- name: RefreshDailyStats :exec
INSERT INTO calendar_stats_daily (
    workspace_id, calendar_id, stats_date,
    operation_count, grant_count, unique_users
)
SELECT
    workspace_id,
    calendar_id,
    DATE(occurred_at),
    COUNT(*),
    COALESCE(SUM(granted), 0),
    COUNT(DISTINCT CONCAT_WS(':', app_id, platform_id, platform_user_id))
FROM calendar_operation
WHERE occurred_at >= ? AND occurred_at < ?
GROUP BY workspace_id, calendar_id, DATE(occurred_at)
ON DUPLICATE KEY UPDATE
    operation_count = VALUES(operation_count),
    grant_count = VALUES(grant_count),
    unique_users = VALUES(unique_users),
    updated_at = NOW()
`

type RefreshDailyStatsParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

func (q *Queries) RefreshDailyStats(ctx context.Context, arg RefreshDailyStatsParams) error {
	_, err := q.exec(ctx, q.refreshDailyStatsStmt, refreshDailyStats, arg.OccurredAt, arg.OccurredAt_2)
	return err
}
