// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type CpaAssignmentCodeMode string

const (
	CpaAssignmentCodeModeSharedCode   CpaAssignmentCodeMode = "shared_code"
	CpaAssignmentCodeModePersonalCode CpaAssignmentCodeMode = "personal_code"
)

func (e *CpaAssignmentCodeMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CpaAssignmentCodeMode(s)
	case string:
		*e = CpaAssignmentCodeMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CpaAssignmentCodeMode: %T", src)
	}
	return nil
}

type NullCpaAssignmentCodeMode struct {
	CpaAssignmentCodeMode CpaAssignmentCodeMode `json:"cpa_assignment_code_mode"`
	Valid                 bool                  `json:"valid"` // Valid is true if CpaAssignmentCodeMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCpaAssignmentCodeMode) Scan(value interface{}) error {
	if value == nil {
		ns.CpaAssignmentCodeMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CpaAssignmentCodeMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCpaAssignmentCodeMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CpaAssignmentCodeMode), nil
}

type CpaAssignmentEventEventType string

const (
	CpaAssignmentEventEventTypeIssued    CpaAssignmentEventEventType = "issued"
	CpaAssignmentEventEventTypeCompleted CpaAssignmentEventEventType = "completed"
)

func (e *CpaAssignmentEventEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CpaAssignmentEventEventType(s)
	case string:
		*e = CpaAssignmentEventEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for CpaAssignmentEventEventType: %T", src)
	}
	return nil
}

type NullCpaAssignmentEventEventType struct {
	CpaAssignmentEventEventType CpaAssignmentEventEventType `json:"cpa_assignment_event_event_type"`
	Valid                       bool                        `json:"valid"` // Valid is true if CpaAssignmentEventEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCpaAssignmentEventEventType) Scan(value interface{}) error {
	if value == nil {
		ns.CpaAssignmentEventEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CpaAssignmentEventEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCpaAssignmentEventEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CpaAssignmentEventEventType), nil
}

type CpaAssignmentStatus string

const (
	CpaAssignmentStatusIssued    CpaAssignmentStatus = "issued"
	CpaAssignmentStatusCompleted CpaAssignmentStatus = "completed"
)

func (e *CpaAssignmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CpaAssignmentStatus(s)
	case string:
		*e = CpaAssignmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CpaAssignmentStatus: %T", src)
	}
	return nil
}

type NullCpaAssignmentStatus struct {
	CpaAssignmentStatus CpaAssignmentStatus `json:"cpa_assignment_status"`
	Valid               bool                `json:"valid"` // Valid is true if CpaAssignmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCpaAssignmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CpaAssignmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CpaAssignmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCpaAssignmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CpaAssignmentStatus), nil
}

type CpaCodeSource string

const (
	CpaCodeSourceGenerated CpaCodeSource = "generated"
	CpaCodeSourcePool      CpaCodeSource = "pool"
)

func (e *CpaCodeSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CpaCodeSource(s)
	case string:
		*e = CpaCodeSource(s)
	default:
		return fmt.Errorf("unsupported scan type for CpaCodeSource: %T", src)
	}
	return nil
}

type NullCpaCodeSource struct {
	CpaCodeSource CpaCodeSource `json:"cpa_code_source"`
	Valid         bool          `json:"valid"` // Valid is true if CpaCodeSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCpaCodeSource) Scan(value interface{}) error {
	if value == nil {
		ns.CpaCodeSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CpaCodeSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCpaCodeSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CpaCodeSource), nil
}

type CpaCodeStatus string

const (
	CpaCodeStatusAvailable CpaCodeStatus = "available"
	CpaCodeStatusIssued    CpaCodeStatus = "issued"
	CpaCodeStatusCompleted CpaCodeStatus = "completed"
	CpaCodeStatusDeleted   CpaCodeStatus = "deleted"
)

func (e *CpaCodeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CpaCodeStatus(s)
	case string:
		*e = CpaCodeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CpaCodeStatus: %T", src)
	}
	return nil
}

type NullCpaCodeStatus struct {
	CpaCodeStatus CpaCodeStatus `json:"cpa_code_status"`
	Valid         bool          `json:"valid"` // Valid is true if CpaCodeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCpaCodeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CpaCodeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CpaCodeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCpaCodeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CpaCodeStatus), nil
}

type CpaOfferCodeMode string

const (
	CpaOfferCodeModeSharedCode   CpaOfferCodeMode = "shared_code"
	CpaOfferCodeModePersonalCode CpaOfferCodeMode = "personal_code"
)

func (e *CpaOfferCodeMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CpaOfferCodeMode(s)
	case string:
		*e = CpaOfferCodeMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CpaOfferCodeMode: %T", src)
	}
	return nil
}

type NullCpaOfferCodeMode struct {
	CpaOfferCodeMode CpaOfferCodeMode `json:"cpa_offer_code_mode"`
	Valid            bool             `json:"valid"` // Valid is true if CpaOfferCodeMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCpaOfferCodeMode) Scan(value interface{}) error {
	if value == nil {
		ns.CpaOfferCodeMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CpaOfferCodeMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCpaOfferCodeMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CpaOfferCodeMode), nil
}

type CpaOfferCodeSource string

const (
	CpaOfferCodeSourceGenerated CpaOfferCodeSource = "generated"
	CpaOfferCodeSourcePool      CpaOfferCodeSource = "pool"
)

func (e *CpaOfferCodeSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CpaOfferCodeSource(s)
	case string:
		*e = CpaOfferCodeSource(s)
	default:
		return fmt.Errorf("unsupported scan type for CpaOfferCodeSource: %T", src)
	}
	return nil
}

type NullCpaOfferCodeSource struct {
	CpaOfferCodeSource CpaOfferCodeSource `json:"cpa_offer_code_source"`
	Valid              bool               `json:"valid"` // Valid is true if CpaOfferCodeSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCpaOfferCodeSource) Scan(value interface{}) error {
	if value == nil {
		ns.CpaOfferCodeSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CpaOfferCodeSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCpaOfferCodeSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CpaOfferCodeSource), nil
}

type CpaRewardDurationUnit string

const (
	CpaRewardDurationUnitSecond CpaRewardDurationUnit = "second"
	CpaRewardDurationUnitMinute CpaRewardDurationUnit = "minute"
	CpaRewardDurationUnitHour   CpaRewardDurationUnit = "hour"
	CpaRewardDurationUnitDay    CpaRewardDurationUnit = "day"
	CpaRewardDurationUnitWeek   CpaRewardDurationUnit = "week"
	CpaRewardDurationUnitMonth  CpaRewardDurationUnit = "month"
	CpaRewardDurationUnitYear   CpaRewardDurationUnit = "year"
)

func (e *CpaRewardDurationUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CpaRewardDurationUnit(s)
	case string:
		*e = CpaRewardDurationUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for CpaRewardDurationUnit: %T", src)
	}
	return nil
}

type NullCpaRewardDurationUnit struct {
	CpaRewardDurationUnit CpaRewardDurationUnit `json:"cpa_reward_duration_unit"`
	Valid                 bool                  `json:"valid"` // Valid is true if CpaRewardDurationUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCpaRewardDurationUnit) Scan(value interface{}) error {
	if value == nil {
		ns.CpaRewardDurationUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CpaRewardDurationUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCpaRewardDurationUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CpaRewardDurationUnit), nil
}

type CpaRewardRewardType string

const (
	CpaRewardRewardTypeQuantity CpaRewardRewardType = "quantity"
	CpaRewardRewardTypeDuration CpaRewardRewardType = "duration"
)

func (e *CpaRewardRewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CpaRewardRewardType(s)
	case string:
		*e = CpaRewardRewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for CpaRewardRewardType: %T", src)
	}
	return nil
}

type NullCpaRewardRewardType struct {
	CpaRewardRewardType CpaRewardRewardType `json:"cpa_reward_reward_type"`
	Valid               bool                `json:"valid"` // Valid is true if CpaRewardRewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCpaRewardRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.CpaRewardRewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CpaRewardRewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCpaRewardRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CpaRewardRewardType), nil
}

type CpaAssignment struct {
	ID             uint64                `json:"id"`
	WorkspaceID    string                `json:"workspace_id"`
	CpaID          string                `json:"cpa_id"`
	AppID          int64                 `json:"app_id"`
	PlatformID     int64                 `json:"platform_id"`
	PlatformUserID string                `json:"platform_user_id"`
	CodeID         sql.NullInt64         `json:"code_id"`
	Code           string                `json:"code"`
	CodeMode       CpaAssignmentCodeMode `json:"code_mode"`
	Status         CpaAssignmentStatus   `json:"status"`
	IssuedAt       time.Time             `json:"issued_at"`
	CompletedAt    sql.NullTime          `json:"completed_at"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type CpaAssignmentEvent struct {
	ID           uint64                      `json:"id"`
	WorkspaceID  string                      `json:"workspace_id"`
	CpaID        string                      `json:"cpa_id"`
	AssignmentID uint64                      `json:"assignment_id"`
	EventType    CpaAssignmentEventEventType `json:"event_type"`
	OccurredAt   time.Time                   `json:"occurred_at"`
	CreatedAt    time.Time                   `json:"created_at"`
}

type CpaCode struct {
	ID          uint64        `json:"id"`
	WorkspaceID string        `json:"workspace_id"`
	CpaID       string        `json:"cpa_id"`
	Code        string        `json:"code"`
	Source      CpaCodeSource `json:"source"`
	Status      CpaCodeStatus `json:"status"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
}

type CpaLocalization struct {
	WorkspaceID string    `json:"workspace_id"`
	CpaID       string    `json:"cpa_id"`
	Locale      string    `json:"locale"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type CpaOffer struct {
	WorkspaceID       string                 `json:"workspace_id"`
	ID                string                 `json:"id"`
	Payload           json.RawMessage        `json:"payload"`
	Target            json.RawMessage        `json:"target"`
	CodeMode          CpaOfferCodeMode       `json:"code_mode"`
	CodeSource        NullCpaOfferCodeSource `json:"code_source"`
	SharedCode        sql.NullString         `json:"shared_code"`
	GeneratedLength   sql.NullInt16          `json:"generated_length"`
	GeneratedAlphabet sql.NullString         `json:"generated_alphabet"`
	IsActive          bool                   `json:"is_active"`
	StartAt           sql.NullTime           `json:"start_at"`
	EndAt             sql.NullTime           `json:"end_at"`
	CreatedAt         time.Time              `json:"created_at"`
	UpdatedAt         time.Time              `json:"updated_at"`
}

type CpaReward struct {
	ID           uint64                    `json:"id"`
	WorkspaceID  string                    `json:"workspace_id"`
	CpaID        string                    `json:"cpa_id"`
	RewardKey    string                    `json:"reward_key"`
	RewardType   CpaRewardRewardType       `json:"reward_type"`
	Quantity     int64                     `json:"quantity"`
	Scale        uint16                    `json:"scale"`
	DurationUnit NullCpaRewardDurationUnit `json:"duration_unit"`
	CreatedAt    time.Time                 `json:"created_at"`
	UpdatedAt    time.Time                 `json:"updated_at"`
}

type CpaStatsDaily struct {
	WorkspaceID    string    `json:"workspace_id"`
	CpaID          string    `json:"cpa_id"`
	StatsDate      time.Time `json:"stats_date"`
	IssuedCount    uint64    `json:"issued_count"`
	CompletedCount uint64    `json:"completed_count"`
	UniqueUsers    uint64    `json:"unique_users"`
	UpdatedAt      time.Time `json:"updated_at"`
}
