// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const adminAddCode = `-- name: AdminAddCode :execrows
INSERT IGNORE INTO cpa_code (workspace_id, cpa_id, code, source)
VALUES (?, ?, ?, ?)
`

type AdminAddCodeParams struct {
	WorkspaceID string        `json:"workspace_id"`
	CpaID       string        `json:"cpa_id"`
	Code        string        `json:"code"`
	Source      CpaCodeSource `json:"source"`
}

func (q *Queries) AdminAddCode(ctx context.Context, arg AdminAddCodeParams) (int64, error) {
	result, err := q.exec(ctx, q.adminAddCodeStmt, adminAddCode,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Code,
		arg.Source,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteAvailableCodes = `-- name: AdminDeleteAvailableCodes :execrows
UPDATE cpa_code
SET status = 'deleted', deleted_at = NOW()
WHERE workspace_id = ?
  AND cpa_id = ?
  AND status = 'available'
`

type AdminDeleteAvailableCodesParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) AdminDeleteAvailableCodes(ctx context.Context, arg AdminDeleteAvailableCodesParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteAvailableCodesStmt, adminDeleteAvailableCodes, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteCompletedCodeRows = `-- name: AdminDeleteCompletedCodeRows :execrows
UPDATE cpa_code c
JOIN cpa_assignment a ON a.code_id = c.id
SET c.status = 'deleted', c.deleted_at = NOW()
WHERE a.workspace_id = ?
  AND a.cpa_id = ?
  AND a.status = 'completed'
  AND a.deleted_at IS NOT NULL
`

type AdminDeleteCompletedCodeRowsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) AdminDeleteCompletedCodeRows(ctx context.Context, arg AdminDeleteCompletedCodeRowsParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteCompletedCodeRowsStmt, adminDeleteCompletedCodeRows, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteCompletedCodes = `-- name: AdminDeleteCompletedCodes :execrows
UPDATE cpa_assignment
SET deleted_at = NOW()
WHERE workspace_id = ?
  AND cpa_id = ?
  AND status = 'completed'
  AND deleted_at IS NULL
`

type AdminDeleteCompletedCodesParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) AdminDeleteCompletedCodes(ctx context.Context, arg AdminDeleteCompletedCodesParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteCompletedCodesStmt, adminDeleteCompletedCodes, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteIssuedCodeRows = `-- name: AdminDeleteIssuedCodeRows :execrows
UPDATE cpa_code c
JOIN cpa_assignment a ON a.code_id = c.id
SET c.status = 'deleted', c.deleted_at = NOW()
WHERE a.workspace_id = ?
  AND a.cpa_id = ?
  AND a.status = 'issued'
  AND a.deleted_at IS NOT NULL
`

type AdminDeleteIssuedCodeRowsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) AdminDeleteIssuedCodeRows(ctx context.Context, arg AdminDeleteIssuedCodeRowsParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteIssuedCodeRowsStmt, adminDeleteIssuedCodeRows, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteIssuedCodes = `-- name: AdminDeleteIssuedCodes :execrows
UPDATE cpa_assignment
SET deleted_at = NOW()
WHERE workspace_id = ?
  AND cpa_id = ?
  AND status = 'issued'
  AND deleted_at IS NULL
`

type AdminDeleteIssuedCodesParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) AdminDeleteIssuedCodes(ctx context.Context, arg AdminDeleteIssuedCodesParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteIssuedCodesStmt, adminDeleteIssuedCodes, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteLocalization = `-- name: AdminDeleteLocalization :execrows
DELETE FROM cpa_localization
WHERE workspace_id = ? AND cpa_id = ? AND locale = ?
`

type AdminDeleteLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminDeleteLocalization(ctx context.Context, arg AdminDeleteLocalizationParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteLocalizationStmt, adminDeleteLocalization, arg.WorkspaceID, arg.CpaID, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteOffer = `-- name: AdminDeleteOffer :execrows
DELETE FROM cpa_offer
WHERE workspace_id = ? AND id = ?
`

type AdminDeleteOfferParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) AdminDeleteOffer(ctx context.Context, arg AdminDeleteOfferParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteOfferStmt, adminDeleteOffer, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteReward = `-- name: AdminDeleteReward :execrows
DELETE FROM cpa_reward
WHERE workspace_id = ? AND cpa_id = ? AND reward_key = ?
`

type AdminDeleteRewardParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	RewardKey   string `json:"reward_key"`
}

func (q *Queries) AdminDeleteReward(ctx context.Context, arg AdminDeleteRewardParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteRewardStmt, adminDeleteReward, arg.WorkspaceID, arg.CpaID, arg.RewardKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminGetCodeStats = `-- name: AdminGetCodeStats :one
SELECT
    COUNT(*) AS codes_total,
    CAST(COALESCE(SUM(status = 'available'), 0) AS UNSIGNED) AS available_total,
    CAST(COALESCE(SUM(status = 'issued'), 0) AS UNSIGNED) AS issued_total,
    CAST(COALESCE(SUM(status = 'completed'), 0) AS UNSIGNED) AS completed_total,
    CAST(COALESCE(SUM(status = 'deleted'), 0) AS UNSIGNED) AS deleted_total
FROM cpa_code
WHERE workspace_id = ? AND cpa_id = ?
`

type AdminGetCodeStatsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

type AdminGetCodeStatsRow struct {
	CodesTotal     int64 `json:"codes_total"`
	AvailableTotal int64 `json:"available_total"`
	IssuedTotal    int64 `json:"issued_total"`
	CompletedTotal int64 `json:"completed_total"`
	DeletedTotal   int64 `json:"deleted_total"`
}

func (q *Queries) AdminGetCodeStats(ctx context.Context, arg AdminGetCodeStatsParams) (AdminGetCodeStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetCodeStatsStmt, adminGetCodeStats, arg.WorkspaceID, arg.CpaID)
	var i AdminGetCodeStatsRow
	err := row.Scan(
		&i.CodesTotal,
		&i.AvailableTotal,
		&i.IssuedTotal,
		&i.CompletedTotal,
		&i.DeletedTotal,
	)
	return i, err
}

const adminGetOffer = `-- name: AdminGetOffer :one
SELECT workspace_id, id, payload, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
FROM cpa_offer
WHERE workspace_id = ? AND id = ?
LIMIT 1
`

type AdminGetOfferParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) AdminGetOffer(ctx context.Context, arg AdminGetOfferParams) (CpaOffer, error) {
	row := q.queryRow(ctx, q.adminGetOfferStmt, adminGetOffer, arg.WorkspaceID, arg.ID)
	var i CpaOffer
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Payload,
		&i.CodeMode,
		&i.CodeSource,
		&i.SharedCode,
		&i.GeneratedLength,
		&i.GeneratedAlphabet,
		&i.IsActive,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetOfferStats = `-- name: AdminGetOfferStats :one
SELECT
    COUNT(*) AS assignments_total,
    CAST(COALESCE(SUM(status = 'issued'), 0) AS UNSIGNED) AS issued_total,
    CAST(COALESCE(SUM(status = 'completed'), 0) AS UNSIGNED) AS completed_total,
    CAST(COALESCE(SUM(deleted_at IS NOT NULL), 0) AS UNSIGNED) AS deleted_total
FROM cpa_assignment
WHERE workspace_id = ? AND cpa_id = ?
`

type AdminGetOfferStatsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

type AdminGetOfferStatsRow struct {
	AssignmentsTotal int64 `json:"assignments_total"`
	IssuedTotal      int64 `json:"issued_total"`
	CompletedTotal   int64 `json:"completed_total"`
	DeletedTotal     int64 `json:"deleted_total"`
}

func (q *Queries) AdminGetOfferStats(ctx context.Context, arg AdminGetOfferStatsParams) (AdminGetOfferStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetOfferStatsStmt, adminGetOfferStats, arg.WorkspaceID, arg.CpaID)
	var i AdminGetOfferStatsRow
	err := row.Scan(
		&i.AssignmentsTotal,
		&i.IssuedTotal,
		&i.CompletedTotal,
		&i.DeletedTotal,
	)
	return i, err
}

const adminListAssignmentEvents = `-- name: AdminListAssignmentEvents :many
SELECT id, workspace_id, cpa_id, assignment_id, event_type, occurred_at, created_at
FROM cpa_assignment_event
WHERE workspace_id = ?
  AND cpa_id = ?
  AND (? = '' OR CAST(event_type AS CHAR) = ?)
ORDER BY occurred_at DESC, id DESC
LIMIT ? OFFSET ?
`

type AdminListAssignmentEventsParams struct {
	WorkspaceID string                      `json:"workspace_id"`
	CpaID       string                      `json:"cpa_id"`
	Column3     interface{}                 `json:"column_3"`
	EventType   CpaAssignmentEventEventType `json:"event_type"`
	Limit       int32                       `json:"limit"`
	Offset      int32                       `json:"offset"`
}

func (q *Queries) AdminListAssignmentEvents(ctx context.Context, arg AdminListAssignmentEventsParams) ([]CpaAssignmentEvent, error) {
	rows, err := q.query(ctx, q.adminListAssignmentEventsStmt, adminListAssignmentEvents,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Column3,
		arg.EventType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaAssignmentEvent
	for rows.Next() {
		var i CpaAssignmentEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.AssignmentID,
			&i.EventType,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAssignments = `-- name: AdminListAssignments :many
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = ?
  AND cpa_id = ?
  AND (? = '' OR CAST(status AS CHAR) = ?)
ORDER BY issued_at DESC, id DESC
LIMIT ? OFFSET ?
`

type AdminListAssignmentsParams struct {
	WorkspaceID string              `json:"workspace_id"`
	CpaID       string              `json:"cpa_id"`
	Column3     interface{}         `json:"column_3"`
	Status      CpaAssignmentStatus `json:"status"`
	Limit       int32               `json:"limit"`
	Offset      int32               `json:"offset"`
}

func (q *Queries) AdminListAssignments(ctx context.Context, arg AdminListAssignmentsParams) ([]CpaAssignment, error) {
	rows, err := q.query(ctx, q.adminListAssignmentsStmt, adminListAssignments,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Column3,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaAssignment
	for rows.Next() {
		var i CpaAssignment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.AppID,
			&i.PlatformID,
			&i.PlatformUserID,
			&i.CodeID,
			&i.Code,
			&i.CodeMode,
			&i.Status,
			&i.IssuedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCodes = `-- name: AdminListCodes :many
SELECT id, workspace_id, cpa_id, code, source, status, created_at, updated_at, deleted_at
FROM cpa_code
WHERE workspace_id = ?
  AND cpa_id = ?
  AND (? = '' OR CAST(status AS CHAR) = ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type AdminListCodesParams struct {
	WorkspaceID string        `json:"workspace_id"`
	CpaID       string        `json:"cpa_id"`
	Column3     interface{}   `json:"column_3"`
	Status      CpaCodeStatus `json:"status"`
	Limit       int32         `json:"limit"`
	Offset      int32         `json:"offset"`
}

func (q *Queries) AdminListCodes(ctx context.Context, arg AdminListCodesParams) ([]CpaCode, error) {
	rows, err := q.query(ctx, q.adminListCodesStmt, adminListCodes,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Column3,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaCode
	for rows.Next() {
		var i CpaCode
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.Code,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListDailyStats = `-- name: AdminListDailyStats :many
SELECT workspace_id, cpa_id, stats_date, issued_count, completed_count, unique_users, updated_at
FROM cpa_stats_daily
WHERE workspace_id = ?
  AND cpa_id = ?
  AND stats_date >= ?
  AND stats_date <= ?
ORDER BY stats_date
`

type AdminListDailyStatsParams struct {
	WorkspaceID string    `json:"workspace_id"`
	CpaID       string    `json:"cpa_id"`
	StatsDate   time.Time `json:"stats_date"`
	StatsDate_2 time.Time `json:"stats_date_2"`
}

func (q *Queries) AdminListDailyStats(ctx context.Context, arg AdminListDailyStatsParams) ([]CpaStatsDaily, error) {
	rows, err := q.query(ctx, q.adminListDailyStatsStmt, adminListDailyStats,
		arg.WorkspaceID,
		arg.CpaID,
		arg.StatsDate,
		arg.StatsDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaStatsDaily
	for rows.Next() {
		var i CpaStatsDaily
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CpaID,
			&i.StatsDate,
			&i.IssuedCount,
			&i.CompletedCount,
			&i.UniqueUsers,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOfferBundleRewards = `-- name: AdminListOfferBundleRewards :many
SELECT
    o.workspace_id,
    o.id AS cpa_id,
    r.reward_key,
    r.reward_type,
    r.quantity AS reward_quantity
    , r.duration_unit
FROM (
    SELECT workspace_id, id, payload, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
    FROM cpa_offer
    WHERE cpa_offer.workspace_id = ?
    ORDER BY cpa_offer.created_at DESC, cpa_offer.id
    LIMIT ? OFFSET ?
) o
JOIN cpa_reward r
    ON r.workspace_id = o.workspace_id
   AND r.cpa_id = o.id
ORDER BY o.created_at DESC, o.id, r.id
`

type AdminListOfferBundleRewardsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type AdminListOfferBundleRewardsRow struct {
	WorkspaceID    string                    `json:"workspace_id"`
	CpaID          string                    `json:"cpa_id"`
	RewardKey      string                    `json:"reward_key"`
	RewardType     CpaRewardRewardType       `json:"reward_type"`
	RewardQuantity int64                     `json:"reward_quantity"`
	DurationUnit   NullCpaRewardDurationUnit `json:"duration_unit"`
}

func (q *Queries) AdminListOfferBundleRewards(ctx context.Context, arg AdminListOfferBundleRewardsParams) ([]AdminListOfferBundleRewardsRow, error) {
	rows, err := q.query(ctx, q.adminListOfferBundleRewardsStmt, adminListOfferBundleRewards, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOfferBundleRewardsRow
	for rows.Next() {
		var i AdminListOfferBundleRewardsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CpaID,
			&i.RewardKey,
			&i.RewardType,
			&i.RewardQuantity,
			&i.DurationUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOfferBundles = `-- name: AdminListOfferBundles :many
SELECT
    o.workspace_id, o.id, o.payload, o.code_mode, o.code_source, o.shared_code, o.generated_length, o.generated_alphabet, o.is_active, o.start_at, o.end_at, o.created_at, o.updated_at,
    l.locale,
    l.title AS localization_title,
    l.description AS localization_description
FROM (
    SELECT workspace_id, id, payload, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
    FROM cpa_offer
    WHERE cpa_offer.workspace_id = ?
    ORDER BY cpa_offer.created_at DESC, cpa_offer.id
    LIMIT ? OFFSET ?
) o
LEFT JOIN cpa_localization l
    ON l.workspace_id = o.workspace_id
   AND l.cpa_id = o.id
ORDER BY o.created_at DESC, o.id, l.locale
`

type AdminListOfferBundlesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type AdminListOfferBundlesRow struct {
	WorkspaceID             string                 `json:"workspace_id"`
	ID                      string                 `json:"id"`
	Payload                 json.RawMessage        `json:"payload"`
	CodeMode                CpaOfferCodeMode       `json:"code_mode"`
	CodeSource              NullCpaOfferCodeSource `json:"code_source"`
	SharedCode              sql.NullString         `json:"shared_code"`
	GeneratedLength         sql.NullInt16          `json:"generated_length"`
	GeneratedAlphabet       sql.NullString         `json:"generated_alphabet"`
	IsActive                bool                   `json:"is_active"`
	StartAt                 sql.NullTime           `json:"start_at"`
	EndAt                   sql.NullTime           `json:"end_at"`
	CreatedAt               time.Time              `json:"created_at"`
	UpdatedAt               time.Time              `json:"updated_at"`
	Locale                  sql.NullString         `json:"locale"`
	LocalizationTitle       sql.NullString         `json:"localization_title"`
	LocalizationDescription sql.NullString         `json:"localization_description"`
}

func (q *Queries) AdminListOfferBundles(ctx context.Context, arg AdminListOfferBundlesParams) ([]AdminListOfferBundlesRow, error) {
	rows, err := q.query(ctx, q.adminListOfferBundlesStmt, adminListOfferBundles, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOfferBundlesRow
	for rows.Next() {
		var i AdminListOfferBundlesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Payload,
			&i.CodeMode,
			&i.CodeSource,
			&i.SharedCode,
			&i.GeneratedLength,
			&i.GeneratedAlphabet,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Locale,
			&i.LocalizationTitle,
			&i.LocalizationDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOffers = `-- name: AdminListOffers :many
SELECT workspace_id, id, payload, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
FROM cpa_offer
WHERE workspace_id = ?
ORDER BY created_at DESC, id
LIMIT ? OFFSET ?
`

type AdminListOffersParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) AdminListOffers(ctx context.Context, arg AdminListOffersParams) ([]CpaOffer, error) {
	rows, err := q.query(ctx, q.adminListOffersStmt, adminListOffers, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaOffer
	for rows.Next() {
		var i CpaOffer
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Payload,
			&i.CodeMode,
			&i.CodeSource,
			&i.SharedCode,
			&i.GeneratedLength,
			&i.GeneratedAlphabet,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpsertLocalization = `-- name: AdminUpsertLocalization :exec
INSERT INTO cpa_localization (
    workspace_id, cpa_id, locale, title, description
) VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    description = VALUES(description)
`

type AdminUpsertLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Locale      string `json:"locale"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) AdminUpsertLocalization(ctx context.Context, arg AdminUpsertLocalizationParams) error {
	_, err := q.exec(ctx, q.adminUpsertLocalizationStmt, adminUpsertLocalization,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Locale,
		arg.Title,
		arg.Description,
	)
	return err
}

const adminUpsertOffer = `-- name: AdminUpsertOffer :exec
INSERT INTO cpa_offer (
    workspace_id, id, payload, code_mode, code_source, shared_code,
    generated_length, generated_alphabet, is_active, start_at, end_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    payload = VALUES(payload),
    code_mode = VALUES(code_mode),
    code_source = VALUES(code_source),
    shared_code = VALUES(shared_code),
    generated_length = VALUES(generated_length),
    generated_alphabet = VALUES(generated_alphabet),
    is_active = VALUES(is_active),
    start_at = VALUES(start_at),
    end_at = VALUES(end_at)
`

type AdminUpsertOfferParams struct {
	WorkspaceID       string                 `json:"workspace_id"`
	ID                string                 `json:"id"`
	Payload           json.RawMessage        `json:"payload"`
	CodeMode          CpaOfferCodeMode       `json:"code_mode"`
	CodeSource        NullCpaOfferCodeSource `json:"code_source"`
	SharedCode        sql.NullString         `json:"shared_code"`
	GeneratedLength   sql.NullInt16          `json:"generated_length"`
	GeneratedAlphabet sql.NullString         `json:"generated_alphabet"`
	IsActive          bool                   `json:"is_active"`
	StartAt           sql.NullTime           `json:"start_at"`
	EndAt             sql.NullTime           `json:"end_at"`
}

func (q *Queries) AdminUpsertOffer(ctx context.Context, arg AdminUpsertOfferParams) error {
	_, err := q.exec(ctx, q.adminUpsertOfferStmt, adminUpsertOffer,
		arg.WorkspaceID,
		arg.ID,
		arg.Payload,
		arg.CodeMode,
		arg.CodeSource,
		arg.SharedCode,
		arg.GeneratedLength,
		arg.GeneratedAlphabet,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
	)
	return err
}

const adminUpsertReward = `-- name: AdminUpsertReward :exec
INSERT INTO cpa_reward (
    workspace_id, cpa_id, reward_key, reward_type, quantity, duration_unit
) VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    reward_type = VALUES(reward_type),
    quantity = VALUES(quantity),
    duration_unit = VALUES(duration_unit)
`

type AdminUpsertRewardParams struct {
	WorkspaceID  string                    `json:"workspace_id"`
	CpaID        string                    `json:"cpa_id"`
	RewardKey    string                    `json:"reward_key"`
	RewardType   CpaRewardRewardType       `json:"reward_type"`
	Quantity     int64                     `json:"quantity"`
	DurationUnit NullCpaRewardDurationUnit `json:"duration_unit"`
}

func (q *Queries) AdminUpsertReward(ctx context.Context, arg AdminUpsertRewardParams) error {
	_, err := q.exec(ctx, q.adminUpsertRewardStmt, adminUpsertReward,
		arg.WorkspaceID,
		arg.CpaID,
		arg.RewardKey,
		arg.RewardType,
		arg.Quantity,
		arg.DurationUnit,
	)
	return err
}

const completeAssignment = `-- name: CompleteAssignment :execrows
UPDATE cpa_assignment
SET status = 'completed', completed_at = NOW()
WHERE workspace_id = ?
  AND id = ?
  AND status = 'issued'
  AND deleted_at IS NULL
`

type CompleteAssignmentParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) CompleteAssignment(ctx context.Context, arg CompleteAssignmentParams) (int64, error) {
	result, err := q.exec(ctx, q.completeAssignmentStmt, completeAssignment, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAssignment = `-- name: CreateAssignment :execlastid
INSERT INTO cpa_assignment (
    workspace_id, cpa_id, app_id, platform_id, platform_user_id,
    code_id, code, code_mode
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAssignmentParams struct {
	WorkspaceID    string                `json:"workspace_id"`
	CpaID          string                `json:"cpa_id"`
	AppID          int64                 `json:"app_id"`
	PlatformID     int64                 `json:"platform_id"`
	PlatformUserID string                `json:"platform_user_id"`
	CodeID         sql.NullInt64         `json:"code_id"`
	Code           string                `json:"code"`
	CodeMode       CpaAssignmentCodeMode `json:"code_mode"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (int64, error) {
	result, err := q.exec(ctx, q.createAssignmentStmt, createAssignment,
		arg.WorkspaceID,
		arg.CpaID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.CodeID,
		arg.Code,
		arg.CodeMode,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createAssignmentEvent = `-- name: CreateAssignmentEvent :execlastid
INSERT INTO cpa_assignment_event (
    workspace_id, cpa_id, assignment_id, event_type
) VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id)
`

type CreateAssignmentEventParams struct {
	WorkspaceID  string                      `json:"workspace_id"`
	CpaID        string                      `json:"cpa_id"`
	AssignmentID uint64                      `json:"assignment_id"`
	EventType    CpaAssignmentEventEventType `json:"event_type"`
}

func (q *Queries) CreateAssignmentEvent(ctx context.Context, arg CreateAssignmentEventParams) (int64, error) {
	result, err := q.exec(ctx, q.createAssignmentEventStmt, createAssignmentEvent,
		arg.WorkspaceID,
		arg.CpaID,
		arg.AssignmentID,
		arg.EventType,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createGeneratedCode = `-- name: CreateGeneratedCode :execlastid
INSERT INTO cpa_code (workspace_id, cpa_id, code, source)
VALUES (?, ?, ?, 'generated')
`

type CreateGeneratedCodeParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Code        string `json:"code"`
}

func (q *Queries) CreateGeneratedCode(ctx context.Context, arg CreateGeneratedCodeParams) (int64, error) {
	result, err := q.exec(ctx, q.createGeneratedCodeStmt, createGeneratedCode, arg.WorkspaceID, arg.CpaID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getActiveOfferForUpdate = `-- name: GetActiveOfferForUpdate :one
SELECT workspace_id, id, payload, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
FROM cpa_offer
WHERE workspace_id = ?
  AND id = ?
  AND is_active = TRUE
  AND (start_at IS NULL OR start_at <= NOW())
  AND (end_at IS NULL OR end_at > NOW())
LIMIT 1
FOR UPDATE
`

type GetActiveOfferForUpdateParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetActiveOfferForUpdate(ctx context.Context, arg GetActiveOfferForUpdateParams) (CpaOffer, error) {
	row := q.queryRow(ctx, q.getActiveOfferForUpdateStmt, getActiveOfferForUpdate, arg.WorkspaceID, arg.ID)
	var i CpaOffer
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Payload,
		&i.CodeMode,
		&i.CodeSource,
		&i.SharedCode,
		&i.GeneratedLength,
		&i.GeneratedAlphabet,
		&i.IsActive,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = ?
  AND cpa_id = ?
  AND app_id = ?
  AND platform_id = ?
  AND platform_user_id = ?
  AND deleted_at IS NULL
LIMIT 1
`

type GetAssignmentParams struct {
	WorkspaceID    string `json:"workspace_id"`
	CpaID          string `json:"cpa_id"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) GetAssignment(ctx context.Context, arg GetAssignmentParams) (CpaAssignment, error) {
	row := q.queryRow(ctx, q.getAssignmentStmt, getAssignment,
		arg.WorkspaceID,
		arg.CpaID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
	)
	var i CpaAssignment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.AppID,
		&i.PlatformID,
		&i.PlatformUserID,
		&i.CodeID,
		&i.Code,
		&i.CodeMode,
		&i.Status,
		&i.IssuedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = ? AND id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetAssignmentByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) GetAssignmentByID(ctx context.Context, arg GetAssignmentByIDParams) (CpaAssignment, error) {
	row := q.queryRow(ctx, q.getAssignmentByIDStmt, getAssignmentByID, arg.WorkspaceID, arg.ID)
	var i CpaAssignment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.AppID,
		&i.PlatformID,
		&i.PlatformUserID,
		&i.CodeID,
		&i.Code,
		&i.CodeMode,
		&i.Status,
		&i.IssuedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentForUpdate = `-- name: GetAssignmentForUpdate :one
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = ?
  AND cpa_id = ?
  AND app_id = ?
  AND platform_id = ?
  AND platform_user_id = ?
  AND deleted_at IS NULL
LIMIT 1
FOR UPDATE
`

type GetAssignmentForUpdateParams struct {
	WorkspaceID    string `json:"workspace_id"`
	CpaID          string `json:"cpa_id"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) GetAssignmentForUpdate(ctx context.Context, arg GetAssignmentForUpdateParams) (CpaAssignment, error) {
	row := q.queryRow(ctx, q.getAssignmentForUpdateStmt, getAssignmentForUpdate,
		arg.WorkspaceID,
		arg.CpaID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
	)
	var i CpaAssignment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.AppID,
		&i.PlatformID,
		&i.PlatformUserID,
		&i.CodeID,
		&i.Code,
		&i.CodeMode,
		&i.Status,
		&i.IssuedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailableCodeForUpdate = `-- name: GetAvailableCodeForUpdate :one
SELECT id, workspace_id, cpa_id, code, source, status, created_at, updated_at, deleted_at
FROM cpa_code
WHERE workspace_id = ?
  AND cpa_id = ?
  AND source = 'pool'
  AND status = 'available'
ORDER BY id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type GetAvailableCodeForUpdateParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) GetAvailableCodeForUpdate(ctx context.Context, arg GetAvailableCodeForUpdateParams) (CpaCode, error) {
	row := q.queryRow(ctx, q.getAvailableCodeForUpdateStmt, getAvailableCodeForUpdate, arg.WorkspaceID, arg.CpaID)
	var i CpaCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCodeByValue = `-- name: GetCodeByValue :one
SELECT id, workspace_id, cpa_id, code, source, status, created_at, updated_at, deleted_at
FROM cpa_code
WHERE workspace_id = ? AND cpa_id = ? AND code = ?
LIMIT 1
`

type GetCodeByValueParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Code        string `json:"code"`
}

func (q *Queries) GetCodeByValue(ctx context.Context, arg GetCodeByValueParams) (CpaCode, error) {
	row := q.queryRow(ctx, q.getCodeByValueStmt, getCodeByValue, arg.WorkspaceID, arg.CpaID, arg.Code)
	var i CpaCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLocalization = `-- name: GetLocalization :one
SELECT workspace_id, cpa_id, locale, title, description, created_at, updated_at
FROM cpa_localization
WHERE workspace_id = ? AND cpa_id = ? AND locale = ?
LIMIT 1
`

type GetLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) GetLocalization(ctx context.Context, arg GetLocalizationParams) (CpaLocalization, error) {
	row := q.queryRow(ctx, q.getLocalizationStmt, getLocalization, arg.WorkspaceID, arg.CpaID, arg.Locale)
	var i CpaLocalization
	err := row.Scan(
		&i.WorkspaceID,
		&i.CpaID,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOfferBundles = `-- name: ListActiveOfferBundles :many
SELECT
    o.workspace_id,
    o.id,
    o.payload,
    o.code_mode,
    o.code_source,
    o.shared_code,
    o.generated_length,
    o.generated_alphabet,
    o.is_active,
    o.start_at,
    o.end_at,
    o.created_at,
    o.updated_at,
    l.locale AS localized_locale,
    l.title AS localized_title,
    l.description AS localized_description,
    a.id AS assignment_id,
    a.code AS assignment_code,
    a.code_mode AS assignment_code_mode,
    a.status AS assignment_status,
    a.issued_at AS assignment_issued_at,
    a.completed_at AS assignment_completed_at,
    r.reward_key,
    r.reward_type,
    r.quantity AS reward_quantity,
    r.duration_unit
FROM cpa_offer o
LEFT JOIN cpa_localization l
    ON l.workspace_id = o.workspace_id
   AND l.cpa_id = o.id
   AND l.locale = ?
LEFT JOIN cpa_assignment a
    ON a.workspace_id = o.workspace_id
   AND a.cpa_id = o.id
   AND a.app_id = ?
   AND a.platform_id = ?
   AND a.platform_user_id = ?
   AND a.deleted_at IS NULL
LEFT JOIN cpa_reward r
    ON r.workspace_id = o.workspace_id
   AND r.cpa_id = o.id
WHERE o.workspace_id = ?
  AND o.is_active = TRUE
  AND (o.start_at IS NULL OR o.start_at <= NOW())
  AND (o.end_at IS NULL OR o.end_at > NOW())
ORDER BY o.created_at DESC, o.id, r.id
`

type ListActiveOfferBundlesParams struct {
	Locale         string `json:"locale"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
	WorkspaceID    string `json:"workspace_id"`
}

type ListActiveOfferBundlesRow struct {
	WorkspaceID           string                    `json:"workspace_id"`
	ID                    string                    `json:"id"`
	Payload               json.RawMessage           `json:"payload"`
	CodeMode              CpaOfferCodeMode          `json:"code_mode"`
	CodeSource            NullCpaOfferCodeSource    `json:"code_source"`
	SharedCode            sql.NullString            `json:"shared_code"`
	GeneratedLength       sql.NullInt16             `json:"generated_length"`
	GeneratedAlphabet     sql.NullString            `json:"generated_alphabet"`
	IsActive              bool                      `json:"is_active"`
	StartAt               sql.NullTime              `json:"start_at"`
	EndAt                 sql.NullTime              `json:"end_at"`
	CreatedAt             time.Time                 `json:"created_at"`
	UpdatedAt             time.Time                 `json:"updated_at"`
	LocalizedLocale       sql.NullString            `json:"localized_locale"`
	LocalizedTitle        sql.NullString            `json:"localized_title"`
	LocalizedDescription  sql.NullString            `json:"localized_description"`
	AssignmentID          sql.NullInt64             `json:"assignment_id"`
	AssignmentCode        sql.NullString            `json:"assignment_code"`
	AssignmentCodeMode    NullCpaAssignmentCodeMode `json:"assignment_code_mode"`
	AssignmentStatus      NullCpaAssignmentStatus   `json:"assignment_status"`
	AssignmentIssuedAt    sql.NullTime              `json:"assignment_issued_at"`
	AssignmentCompletedAt sql.NullTime              `json:"assignment_completed_at"`
	RewardKey             sql.NullString            `json:"reward_key"`
	RewardType            NullCpaRewardRewardType   `json:"reward_type"`
	RewardQuantity        sql.NullInt64             `json:"reward_quantity"`
	DurationUnit          NullCpaRewardDurationUnit `json:"duration_unit"`
}

func (q *Queries) ListActiveOfferBundles(ctx context.Context, arg ListActiveOfferBundlesParams) ([]ListActiveOfferBundlesRow, error) {
	rows, err := q.query(ctx, q.listActiveOfferBundlesStmt, listActiveOfferBundles,
		arg.Locale,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveOfferBundlesRow
	for rows.Next() {
		var i ListActiveOfferBundlesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Payload,
			&i.CodeMode,
			&i.CodeSource,
			&i.SharedCode,
			&i.GeneratedLength,
			&i.GeneratedAlphabet,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocalizedLocale,
			&i.LocalizedTitle,
			&i.LocalizedDescription,
			&i.AssignmentID,
			&i.AssignmentCode,
			&i.AssignmentCodeMode,
			&i.AssignmentStatus,
			&i.AssignmentIssuedAt,
			&i.AssignmentCompletedAt,
			&i.RewardKey,
			&i.RewardType,
			&i.RewardQuantity,
			&i.DurationUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveOffers = `-- name: ListActiveOffers :many
SELECT workspace_id, id, payload, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
FROM cpa_offer
WHERE workspace_id = ?
  AND is_active = TRUE
  AND (start_at IS NULL OR start_at <= NOW())
  AND (end_at IS NULL OR end_at > NOW())
ORDER BY created_at DESC, id
`

func (q *Queries) ListActiveOffers(ctx context.Context, workspaceID string) ([]CpaOffer, error) {
	rows, err := q.query(ctx, q.listActiveOffersStmt, listActiveOffers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaOffer
	for rows.Next() {
		var i CpaOffer
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Payload,
			&i.CodeMode,
			&i.CodeSource,
			&i.SharedCode,
			&i.GeneratedLength,
			&i.GeneratedAlphabet,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalizations = `-- name: ListLocalizations :many
SELECT workspace_id, cpa_id, locale, title, description, created_at, updated_at
FROM cpa_localization
WHERE workspace_id = ? AND cpa_id = ?
ORDER BY locale
`

type ListLocalizationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) ListLocalizations(ctx context.Context, arg ListLocalizationsParams) ([]CpaLocalization, error) {
	rows, err := q.query(ctx, q.listLocalizationsStmt, listLocalizations, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaLocalization
	for rows.Next() {
		var i CpaLocalization
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CpaID,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewards = `-- name: ListRewards :many
SELECT id, workspace_id, cpa_id, reward_key, reward_type, quantity, duration_unit, created_at, updated_at
FROM cpa_reward
WHERE workspace_id = ? AND cpa_id = ?
ORDER BY id
`

type ListRewardsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) ListRewards(ctx context.Context, arg ListRewardsParams) ([]CpaReward, error) {
	rows, err := q.query(ctx, q.listRewardsStmt, listRewards, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaReward
	for rows.Next() {
		var i CpaReward
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.RewardKey,
			&i.RewardType,
			&i.Quantity,
			&i.DurationUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAssignments = `-- name: ListUserAssignments :many
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = ?
  AND app_id = ?
  AND platform_id = ?
  AND platform_user_id = ?
  AND deleted_at IS NULL
ORDER BY issued_at DESC, id DESC
`

type ListUserAssignmentsParams struct {
	WorkspaceID    string `json:"workspace_id"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) ListUserAssignments(ctx context.Context, arg ListUserAssignmentsParams) ([]CpaAssignment, error) {
	rows, err := q.query(ctx, q.listUserAssignmentsStmt, listUserAssignments,
		arg.WorkspaceID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaAssignment
	for rows.Next() {
		var i CpaAssignment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.AppID,
			&i.PlatformID,
			&i.PlatformUserID,
			&i.CodeID,
			&i.Code,
			&i.CodeMode,
			&i.Status,
			&i.IssuedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCodeCompleted = `-- name: MarkCodeCompleted :execrows
UPDATE cpa_code
SET status = 'completed'
WHERE id = ? AND status = 'issued'
`

func (q *Queries) MarkCodeCompleted(ctx context.Context, id uint64) (int64, error) {
	result, err := q.exec(ctx, q.markCodeCompletedStmt, markCodeCompleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markCodeIssued = `-- name: MarkCodeIssued :execrows
UPDATE cpa_code
SET status = 'issued'
WHERE id = ? AND status = 'available'
`

func (q *Queries) MarkCodeIssued(ctx context.Context, id uint64) (int64, error) {
	result, err := q.exec(ctx, q.markCodeIssuedStmt, markCodeIssued, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refreshDailyStats = `-- name: RefreshDailyStats :exec
INSERT INTO cpa_stats_daily (
    workspace_id, cpa_id, stats_date,
    issued_count, completed_count, unique_users
)
SELECT
    workspace_id,
    cpa_id,
    DATE(occurred_at),
    SUM(event_type = 'issued'),
    SUM(event_type = 'completed'),
    COUNT(DISTINCT assignment_id)
FROM cpa_assignment_event
WHERE occurred_at >= ?
  AND occurred_at < ?
GROUP BY workspace_id, cpa_id, DATE(occurred_at)
ON DUPLICATE KEY UPDATE
    issued_count = VALUES(issued_count),
    completed_count = VALUES(completed_count),
    unique_users = VALUES(unique_users),
    updated_at = NOW()
`

type RefreshDailyStatsParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

func (q *Queries) RefreshDailyStats(ctx context.Context, arg RefreshDailyStatsParams) error {
	_, err := q.exec(ctx, q.refreshDailyStatsStmt, refreshDailyStats, arg.OccurredAt, arg.OccurredAt_2)
	return err
}
