CREATE TABLE IF NOT EXISTS clb_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source_service VARCHAR(64) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    event_key VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    payload LONGBLOB NOT NULL,
    payload_content_type VARCHAR(64) NOT NULL DEFAULT 'application/json',
    status ENUM('pending', 'processing', 'ok', 'reject') NOT NULL DEFAULT 'pending',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_by VARCHAR(128) NULL,
    locked_until DATETIME NULL,
    delivered_at DATETIME NULL,
    rejected_at DATETIME NULL,
    last_error TEXT NULL,
    reject_reason TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY clb_event_key_uq (source_service, event_key),
    UNIQUE KEY clb_event_idempotency_uq (idempotency_key),
    KEY clb_event_due_idx (status, next_attempt_at, locked_until, id),
    KEY clb_event_type_idx (source_service, event_type, status, created_at)
);
