// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type ControlAccountStatus string

const (
	ControlAccountStatusActive   ControlAccountStatus = "active"
	ControlAccountStatusDisabled ControlAccountStatus = "disabled"
)

func (e *ControlAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ControlAccountStatus(s)
	case string:
		*e = ControlAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ControlAccountStatus: %T", src)
	}
	return nil
}

type NullControlAccountStatus struct {
	ControlAccountStatus ControlAccountStatus `json:"control_account_status"`
	Valid                bool                 `json:"valid"` // Valid is true if ControlAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullControlAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ControlAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ControlAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullControlAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ControlAccountStatus), nil
}

type ControlAuditEventResult string

const (
	ControlAuditEventResultSucceeded ControlAuditEventResult = "succeeded"
	ControlAuditEventResultFailed    ControlAuditEventResult = "failed"
)

func (e *ControlAuditEventResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ControlAuditEventResult(s)
	case string:
		*e = ControlAuditEventResult(s)
	default:
		return fmt.Errorf("unsupported scan type for ControlAuditEventResult: %T", src)
	}
	return nil
}

type NullControlAuditEventResult struct {
	ControlAuditEventResult ControlAuditEventResult `json:"control_audit_event_result"`
	Valid                   bool                    `json:"valid"` // Valid is true if ControlAuditEventResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullControlAuditEventResult) Scan(value interface{}) error {
	if value == nil {
		ns.ControlAuditEventResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ControlAuditEventResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullControlAuditEventResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ControlAuditEventResult), nil
}

type ControlMethodStatus string

const (
	ControlMethodStatusActive     ControlMethodStatus = "active"
	ControlMethodStatusDeprecated ControlMethodStatus = "deprecated"
)

func (e *ControlMethodStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ControlMethodStatus(s)
	case string:
		*e = ControlMethodStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ControlMethodStatus: %T", src)
	}
	return nil
}

type NullControlMethodStatus struct {
	ControlMethodStatus ControlMethodStatus `json:"control_method_status"`
	Valid               bool                `json:"valid"` // Valid is true if ControlMethodStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullControlMethodStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ControlMethodStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ControlMethodStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullControlMethodStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ControlMethodStatus), nil
}

type ControlWorkspaceMemberStatus string

const (
	ControlWorkspaceMemberStatusActive  ControlWorkspaceMemberStatus = "active"
	ControlWorkspaceMemberStatusRemoved ControlWorkspaceMemberStatus = "removed"
)

func (e *ControlWorkspaceMemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ControlWorkspaceMemberStatus(s)
	case string:
		*e = ControlWorkspaceMemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ControlWorkspaceMemberStatus: %T", src)
	}
	return nil
}

type NullControlWorkspaceMemberStatus struct {
	ControlWorkspaceMemberStatus ControlWorkspaceMemberStatus `json:"control_workspace_member_status"`
	Valid                        bool                         `json:"valid"` // Valid is true if ControlWorkspaceMemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullControlWorkspaceMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ControlWorkspaceMemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ControlWorkspaceMemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullControlWorkspaceMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ControlWorkspaceMemberStatus), nil
}

type ControlWorkspaceStatus string

const (
	ControlWorkspaceStatusActive   ControlWorkspaceStatus = "active"
	ControlWorkspaceStatusArchived ControlWorkspaceStatus = "archived"
)

func (e *ControlWorkspaceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ControlWorkspaceStatus(s)
	case string:
		*e = ControlWorkspaceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ControlWorkspaceStatus: %T", src)
	}
	return nil
}

type NullControlWorkspaceStatus struct {
	ControlWorkspaceStatus ControlWorkspaceStatus `json:"control_workspace_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if ControlWorkspaceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullControlWorkspaceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ControlWorkspaceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ControlWorkspaceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullControlWorkspaceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ControlWorkspaceStatus), nil
}

type ControlAccount struct {
	ID          string               `json:"id"`
	DisplayName string               `json:"display_name"`
	Status      ControlAccountStatus `json:"status"`
	CreatedAt   time.Time            `json:"created_at"`
	UpdatedAt   time.Time            `json:"updated_at"`
}

type ControlAuditEvent struct {
	ID          string                  `json:"id"`
	WorkspaceID sql.NullString          `json:"workspace_id"`
	ActorID     sql.NullString          `json:"actor_id"`
	MethodKey   string                  `json:"method_key"`
	TargetType  string                  `json:"target_type"`
	TargetID    string                  `json:"target_id"`
	BeforeData  json.RawMessage         `json:"before_data"`
	AfterData   json.RawMessage         `json:"after_data"`
	Result      ControlAuditEventResult `json:"result"`
	RequestID   string                  `json:"request_id"`
	OccurredAt  time.Time               `json:"occurred_at"`
}

type ControlIdentity struct {
	AccountID       string          `json:"account_id"`
	Provider        string          `json:"provider"`
	ProviderSubject string          `json:"provider_subject"`
	Payload         json.RawMessage `json:"payload"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type ControlMethod struct {
	MethodKey       string              `json:"method_key"`
	Service         string              `json:"service"`
	GroupKey        string              `json:"group_key"`
	Title           string              `json:"title"`
	WorkspaceScoped bool                `json:"workspace_scoped"`
	IsSensitive     bool                `json:"is_sensitive"`
	SchemaRevision  uint32              `json:"schema_revision"`
	Status          ControlMethodStatus `json:"status"`
	CreatedAt       time.Time           `json:"created_at"`
	UpdatedAt       time.Time           `json:"updated_at"`
}

type ControlRole struct {
	ID          string       `json:"id"`
	WorkspaceID string       `json:"workspace_id"`
	Code        string       `json:"code"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Position    int32        `json:"position"`
	IsOwner     bool         `json:"is_owner"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type ControlRoleMember struct {
	RoleID    string    `json:"role_id"`
	AccountID string    `json:"account_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ControlRolePermission struct {
	RoleID    string    `json:"role_id"`
	MethodKey string    `json:"method_key"`
	CreatedAt time.Time `json:"created_at"`
}

type ControlSession struct {
	ID         string       `json:"id"`
	AccountID  string       `json:"account_id"`
	TokenHash  string       `json:"token_hash"`
	Ip         string       `json:"ip"`
	UserAgent  string       `json:"user_agent"`
	BindToIp   bool         `json:"bind_to_ip"`
	ExpiresAt  time.Time    `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
	LastUsedAt time.Time    `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type ControlTwoFactor struct {
	AccountID    string          `json:"account_id"`
	Secret       string          `json:"secret"`
	BackupHashes json.RawMessage `json:"backup_hashes"`
	ActivatedAt  sql.NullTime    `json:"activated_at"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type ControlTwoFactorChallenge struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	TokenHash string    `json:"token_hash"`
	Ip        string    `json:"ip"`
	UserAgent string    `json:"user_agent"`
	BindToIp  bool      `json:"bind_to_ip"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type ControlWorkspace struct {
	ID        string                 `json:"id"`
	Slug      string                 `json:"slug"`
	Title     string                 `json:"title"`
	Status    ControlWorkspaceStatus `json:"status"`
	CreatedBy string                 `json:"created_by"`
	CreatedAt time.Time              `json:"created_at"`
	UpdatedAt time.Time              `json:"updated_at"`
}

type ControlWorkspaceAuthVersion struct {
	WorkspaceID string    `json:"workspace_id"`
	Version     string    `json:"version"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ControlWorkspaceInvite struct {
	ID          string        `json:"id"`
	WorkspaceID string        `json:"workspace_id"`
	CreatedBy   string        `json:"created_by"`
	TokenHash   string        `json:"token_hash"`
	MaxUses     sql.NullInt32 `json:"max_uses"`
	UsedCount   uint32        `json:"used_count"`
	ExpiresAt   sql.NullTime  `json:"expires_at"`
	RevokedAt   sql.NullTime  `json:"revoked_at"`
	CreatedAt   time.Time     `json:"created_at"`
}

type ControlWorkspaceInviteRole struct {
	InviteID string `json:"invite_id"`
	RoleID   string `json:"role_id"`
}

type ControlWorkspaceMember struct {
	WorkspaceID string                       `json:"workspace_id"`
	AccountID   string                       `json:"account_id"`
	Status      ControlWorkspaceMemberStatus `json:"status"`
	JoinedAt    time.Time                    `json:"joined_at"`
	UpdatedAt   time.Time                    `json:"updated_at"`
}
