// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const activateTwoFactor = `-- name: ActivateTwoFactor :execrows
UPDATE control_two_factor SET activated_at = NOW()
WHERE account_id = ? AND activated_at IS NULL
`

func (q *Queries) ActivateTwoFactor(ctx context.Context, accountID string) (int64, error) {
	result, err := q.exec(ctx, q.activateTwoFactorStmt, activateTwoFactor, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const addInviteRole = `-- name: AddInviteRole :exec
INSERT INTO control_workspace_invite_role (invite_id, role_id) VALUES (?, ?)
`

type AddInviteRoleParams struct {
	InviteID string `json:"invite_id"`
	RoleID   string `json:"role_id"`
}

func (q *Queries) AddInviteRole(ctx context.Context, arg AddInviteRoleParams) error {
	_, err := q.exec(ctx, q.addInviteRoleStmt, addInviteRole, arg.InviteID, arg.RoleID)
	return err
}

const addRoleMember = `-- name: AddRoleMember :exec
INSERT IGNORE INTO control_role_member (role_id, account_id) VALUES (?, ?)
`

type AddRoleMemberParams struct {
	RoleID    string `json:"role_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) AddRoleMember(ctx context.Context, arg AddRoleMemberParams) error {
	_, err := q.exec(ctx, q.addRoleMemberStmt, addRoleMember, arg.RoleID, arg.AccountID)
	return err
}

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO control_workspace_member (workspace_id, account_id)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE status = 'active'
`

type AddWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.exec(ctx, q.addWorkspaceMemberStmt, addWorkspaceMember, arg.WorkspaceID, arg.AccountID)
	return err
}

const checkAccess = `-- name: CheckAccess :one
SELECT EXISTS(
    SELECT 1
    FROM control_workspace_member m
    JOIN control_method cm ON cm.method_key = ? AND cm.status = 'active' AND cm.workspace_scoped = TRUE
    JOIN control_role_member rm ON rm.account_id = m.account_id
    JOIN control_role r ON r.id = rm.role_id
    LEFT JOIN control_role_permission p ON p.role_id = r.id AND p.method_key = cm.method_key
    WHERE m.workspace_id = ? AND m.account_id = ? AND m.status = 'active'
      AND r.workspace_id = m.workspace_id AND r.deleted_at IS NULL
      AND (r.is_owner = TRUE OR p.method_key IS NOT NULL)
) AS allowed
`

type CheckAccessParams struct {
	MethodKey   string `json:"method_key"`
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) CheckAccess(ctx context.Context, arg CheckAccessParams) (bool, error) {
	row := q.queryRow(ctx, q.checkAccessStmt, checkAccess, arg.MethodKey, arg.WorkspaceID, arg.AccountID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const clearRolePermissions = `-- name: ClearRolePermissions :execrows
DELETE FROM control_role_permission WHERE role_id = ?
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID string) (int64, error) {
	result, err := q.exec(ctx, q.clearRolePermissionsStmt, clearRolePermissions, roleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countIdentities = `-- name: CountIdentities :one
SELECT COUNT(*) AS count FROM control_identity WHERE account_id = ?
`

func (q *Queries) CountIdentities(ctx context.Context, accountID string) (int64, error) {
	row := q.queryRow(ctx, q.countIdentitiesStmt, countIdentities, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO control_account (id, display_name) VALUES (?, ?)
`

type CreateAccountParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.exec(ctx, q.createAccountStmt, createAccount, arg.ID, arg.DisplayName)
	return err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO control_audit_event (
    id, workspace_id, actor_id, method_key, target_type, target_id,
    before_data, after_data, result, request_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditEventParams struct {
	ID          string                  `json:"id"`
	WorkspaceID sql.NullString          `json:"workspace_id"`
	ActorID     sql.NullString          `json:"actor_id"`
	MethodKey   string                  `json:"method_key"`
	TargetType  string                  `json:"target_type"`
	TargetID    string                  `json:"target_id"`
	BeforeData  json.RawMessage         `json:"before_data"`
	AfterData   json.RawMessage         `json:"after_data"`
	Result      ControlAuditEventResult `json:"result"`
	RequestID   string                  `json:"request_id"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.exec(ctx, q.createAuditEventStmt, createAuditEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.ActorID,
		arg.MethodKey,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeData,
		arg.AfterData,
		arg.Result,
		arg.RequestID,
	)
	return err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO control_workspace_invite (id, workspace_id, created_by, token_hash, max_uses, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateInviteParams struct {
	ID          string        `json:"id"`
	WorkspaceID string        `json:"workspace_id"`
	CreatedBy   string        `json:"created_by"`
	TokenHash   string        `json:"token_hash"`
	MaxUses     sql.NullInt32 `json:"max_uses"`
	ExpiresAt   sql.NullTime  `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.exec(ctx, q.createInviteStmt, createInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.TokenHash,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO control_role (id, workspace_id, code, title, description, position, is_owner)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRoleParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Code        string `json:"code"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Position    int32  `json:"position"`
	IsOwner     bool   `json:"is_owner"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.exec(ctx, q.createRoleStmt, createRole,
		arg.ID,
		arg.WorkspaceID,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.IsOwner,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO control_session (id, account_id, token_hash, ip, user_agent, bind_to_ip, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	TokenHash string    `json:"token_hash"`
	Ip        string    `json:"ip"`
	UserAgent string    `json:"user_agent"`
	BindToIp  bool      `json:"bind_to_ip"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.exec(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.Ip,
		arg.UserAgent,
		arg.BindToIp,
		arg.ExpiresAt,
	)
	return err
}

const createTwoFactorChallenge = `-- name: CreateTwoFactorChallenge :exec
INSERT INTO control_two_factor_challenge (id, account_id, token_hash, ip, user_agent, bind_to_ip, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTwoFactorChallengeParams struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	TokenHash string    `json:"token_hash"`
	Ip        string    `json:"ip"`
	UserAgent string    `json:"user_agent"`
	BindToIp  bool      `json:"bind_to_ip"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateTwoFactorChallenge(ctx context.Context, arg CreateTwoFactorChallengeParams) error {
	_, err := q.exec(ctx, q.createTwoFactorChallengeStmt, createTwoFactorChallenge,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.Ip,
		arg.UserAgent,
		arg.BindToIp,
		arg.ExpiresAt,
	)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO control_workspace (id, slug, title, created_by) VALUES (?, ?, ?, ?)
`

type CreateWorkspaceParams struct {
	ID        string `json:"id"`
	Slug      string `json:"slug"`
	Title     string `json:"title"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.exec(ctx, q.createWorkspaceStmt, createWorkspace,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.CreatedBy,
	)
	return err
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
DELETE FROM control_identity WHERE account_id = ? AND provider = ?
`

type DeleteIdentityParams struct {
	AccountID string `json:"account_id"`
	Provider  string `json:"provider"`
}

func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteIdentityStmt, deleteIdentity, arg.AccountID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRole = `-- name: DeleteRole :execrows
UPDATE control_role SET deleted_at = NOW()
WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL AND is_owner = FALSE
`

type DeleteRoleParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteRoleStmt, deleteRole, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRolePermission = `-- name: DeleteRolePermission :execrows
DELETE FROM control_role_permission WHERE role_id = ? AND method_key = ?
`

type DeleteRolePermissionParams struct {
	RoleID    string `json:"role_id"`
	MethodKey string `json:"method_key"`
}

func (q *Queries) DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteRolePermissionStmt, deleteRolePermission, arg.RoleID, arg.MethodKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTwoFactor = `-- name: DeleteTwoFactor :execrows
DELETE FROM control_two_factor WHERE account_id = ?
`

func (q *Queries) DeleteTwoFactor(ctx context.Context, accountID string) (int64, error) {
	result, err := q.exec(ctx, q.deleteTwoFactorStmt, deleteTwoFactor, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTwoFactorChallenge = `-- name: DeleteTwoFactorChallenge :execrows
DELETE FROM control_two_factor_challenge WHERE id = ?
`

func (q *Queries) DeleteTwoFactorChallenge(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteTwoFactorChallengeStmt, deleteTwoFactorChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findAccountByIdentity = `-- name: FindAccountByIdentity :one
SELECT a.id, a.display_name, a.status, a.created_at, a.updated_at
FROM control_identity i
JOIN control_account a ON a.id = i.account_id
WHERE i.provider = ? AND i.provider_subject = ?
LIMIT 1
`

type FindAccountByIdentityParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) FindAccountByIdentity(ctx context.Context, arg FindAccountByIdentityParams) (ControlAccount, error) {
	row := q.queryRow(ctx, q.findAccountByIdentityStmt, findAccountByIdentity, arg.Provider, arg.ProviderSubject)
	var i ControlAccount
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, display_name, status, created_at, updated_at
FROM control_account WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (ControlAccount, error) {
	row := q.queryRow(ctx, q.getAccountStmt, getAccount, id)
	var i ControlAccount
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountPosition = `-- name: GetAccountPosition :one
SELECT COALESCE((
    SELECT r.position
    FROM control_workspace_member m
    JOIN control_role_member rm ON rm.account_id = m.account_id
    JOIN control_role r ON r.id = rm.role_id
    WHERE m.workspace_id = ? AND m.account_id = ? AND m.status = 'active'
      AND r.workspace_id = m.workspace_id AND r.deleted_at IS NULL
    ORDER BY r.position
    LIMIT 1
), 2147483647) AS position
`

type GetAccountPositionParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) GetAccountPosition(ctx context.Context, arg GetAccountPositionParams) (interface{}, error) {
	row := q.queryRow(ctx, q.getAccountPositionStmt, getAccountPosition, arg.WorkspaceID, arg.AccountID)
	var position interface{}
	err := row.Scan(&position)
	return position, err
}

const getActiveInviteByHashForUpdate = `-- name: GetActiveInviteByHashForUpdate :one
SELECT id, workspace_id, created_by, token_hash, max_uses, used_count, expires_at, revoked_at, created_at
FROM control_workspace_invite
WHERE token_hash = ? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > NOW())
  AND (max_uses IS NULL OR used_count < max_uses)
LIMIT 1 FOR UPDATE
`

func (q *Queries) GetActiveInviteByHashForUpdate(ctx context.Context, tokenHash string) (ControlWorkspaceInvite, error) {
	row := q.queryRow(ctx, q.getActiveInviteByHashForUpdateStmt, getActiveInviteByHashForUpdate, tokenHash)
	var i ControlWorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.TokenHash,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionByHash = `-- name: GetActiveSessionByHash :one
SELECT id, account_id, token_hash, ip, user_agent, bind_to_ip, expires_at, revoked_at, last_used_at, created_at
FROM control_session
WHERE token_hash = ? AND revoked_at IS NULL AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetActiveSessionByHash(ctx context.Context, tokenHash string) (ControlSession, error) {
	row := q.queryRow(ctx, q.getActiveSessionByHashStmt, getActiveSessionByHash, tokenHash)
	var i ControlSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Ip,
		&i.UserAgent,
		&i.BindToIp,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthVersion = `-- name: GetAuthVersion :one
SELECT workspace_id, version, updated_at FROM control_workspace_auth_version WHERE workspace_id = ? LIMIT 1
`

func (q *Queries) GetAuthVersion(ctx context.Context, workspaceID string) (ControlWorkspaceAuthVersion, error) {
	row := q.queryRow(ctx, q.getAuthVersionStmt, getAuthVersion, workspaceID)
	var i ControlWorkspaceAuthVersion
	err := row.Scan(&i.WorkspaceID, &i.Version, &i.UpdatedAt)
	return i, err
}

const getMethod = `-- name: GetMethod :one
SELECT method_key, service, group_key, title, workspace_scoped, is_sensitive, schema_revision, status, created_at, updated_at
FROM control_method WHERE method_key = ? LIMIT 1
`

func (q *Queries) GetMethod(ctx context.Context, methodKey string) (ControlMethod, error) {
	row := q.queryRow(ctx, q.getMethodStmt, getMethod, methodKey)
	var i ControlMethod
	err := row.Scan(
		&i.MethodKey,
		&i.Service,
		&i.GroupKey,
		&i.Title,
		&i.WorkspaceScoped,
		&i.IsSensitive,
		&i.SchemaRevision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, workspace_id, code, title, description, position, is_owner, deleted_at, created_at, updated_at
FROM control_role WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL LIMIT 1
`

type GetRoleParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (ControlRole, error) {
	row := q.queryRow(ctx, q.getRoleStmt, getRole, arg.ID, arg.WorkspaceID)
	var i ControlRole
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.IsOwner,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTwoFactor = `-- name: GetTwoFactor :one
SELECT account_id, secret, backup_hashes, activated_at, created_at, updated_at
FROM control_two_factor WHERE account_id = ? LIMIT 1
`

func (q *Queries) GetTwoFactor(ctx context.Context, accountID string) (ControlTwoFactor, error) {
	row := q.queryRow(ctx, q.getTwoFactorStmt, getTwoFactor, accountID)
	var i ControlTwoFactor
	err := row.Scan(
		&i.AccountID,
		&i.Secret,
		&i.BackupHashes,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTwoFactorChallengeForUpdate = `-- name: GetTwoFactorChallengeForUpdate :one
SELECT id, account_id, token_hash, ip, user_agent, bind_to_ip, expires_at, created_at
FROM control_two_factor_challenge
WHERE token_hash = ? AND expires_at > NOW()
LIMIT 1 FOR UPDATE
`

func (q *Queries) GetTwoFactorChallengeForUpdate(ctx context.Context, tokenHash string) (ControlTwoFactorChallenge, error) {
	row := q.queryRow(ctx, q.getTwoFactorChallengeForUpdateStmt, getTwoFactorChallengeForUpdate, tokenHash)
	var i ControlTwoFactorChallenge
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Ip,
		&i.UserAgent,
		&i.BindToIp,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTwoFactorForUpdate = `-- name: GetTwoFactorForUpdate :one
SELECT account_id, secret, backup_hashes, activated_at, created_at, updated_at
FROM control_two_factor WHERE account_id = ? LIMIT 1 FOR UPDATE
`

func (q *Queries) GetTwoFactorForUpdate(ctx context.Context, accountID string) (ControlTwoFactor, error) {
	row := q.queryRow(ctx, q.getTwoFactorForUpdateStmt, getTwoFactorForUpdate, accountID)
	var i ControlTwoFactor
	err := row.Scan(
		&i.AccountID,
		&i.Secret,
		&i.BackupHashes,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, slug, title, status, created_by, created_at, updated_at
FROM control_workspace WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (ControlWorkspace, error) {
	row := q.queryRow(ctx, q.getWorkspaceStmt, getWorkspace, id)
	var i ControlWorkspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveTwoFactor = `-- name: HasActiveTwoFactor :one
SELECT EXISTS(
    SELECT 1 FROM control_two_factor WHERE account_id = ? AND activated_at IS NOT NULL
) AS active
`

func (q *Queries) HasActiveTwoFactor(ctx context.Context, accountID string) (bool, error) {
	row := q.queryRow(ctx, q.hasActiveTwoFactorStmt, hasActiveTwoFactor, accountID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const incrementInviteUse = `-- name: IncrementInviteUse :execrows
UPDATE control_workspace_invite SET used_count = used_count + 1
WHERE id = ? AND revoked_at IS NULL AND (max_uses IS NULL OR used_count < max_uses)
`

func (q *Queries) IncrementInviteUse(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.incrementInviteUseStmt, incrementInviteUse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const isActiveWorkspaceMember = `-- name: IsActiveWorkspaceMember :one
SELECT EXISTS(
    SELECT 1 FROM control_workspace_member
    WHERE workspace_id = ? AND account_id = ? AND status = 'active'
) AS active
`

type IsActiveWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) IsActiveWorkspaceMember(ctx context.Context, arg IsActiveWorkspaceMemberParams) (bool, error) {
	row := q.queryRow(ctx, q.isActiveWorkspaceMemberStmt, isActiveWorkspaceMember, arg.WorkspaceID, arg.AccountID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, workspace_id, actor_id, method_key, target_type, target_id,
       before_data, after_data, result, request_id, occurred_at
FROM control_audit_event
WHERE workspace_id = ?
ORDER BY occurred_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListAuditEventsParams struct {
	WorkspaceID sql.NullString `json:"workspace_id"`
	Limit       int32          `json:"limit"`
	Offset      int32          `json:"offset"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ControlAuditEvent, error) {
	rows, err := q.query(ctx, q.listAuditEventsStmt, listAuditEvents, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlAuditEvent
	for rows.Next() {
		var i ControlAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.MethodKey,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeData,
			&i.AfterData,
			&i.Result,
			&i.RequestID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsFiltered = `-- name: ListAuditEventsFiltered :many
SELECT id, workspace_id, actor_id, method_key, target_type, target_id,
       before_data, after_data, result, request_id, occurred_at
FROM control_audit_event
WHERE workspace_id = ?
  AND (? = '' OR method_key = ?)
  AND (? = '' OR actor_id = ?)
  AND (? IS NULL OR occurred_at >= ?)
  AND (? IS NULL OR occurred_at < ?)
ORDER BY occurred_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListAuditEventsFilteredParams struct {
	WorkspaceID  sql.NullString `json:"workspace_id"`
	Column2      interface{}    `json:"column_2"`
	MethodKey    string         `json:"method_key"`
	Column4      interface{}    `json:"column_4"`
	ActorID      sql.NullString `json:"actor_id"`
	Column6      interface{}    `json:"column_6"`
	OccurredAt   time.Time      `json:"occurred_at"`
	Column8      interface{}    `json:"column_8"`
	OccurredAt_2 time.Time      `json:"occurred_at_2"`
	Limit        int32          `json:"limit"`
	Offset       int32          `json:"offset"`
}

func (q *Queries) ListAuditEventsFiltered(ctx context.Context, arg ListAuditEventsFilteredParams) ([]ControlAuditEvent, error) {
	rows, err := q.query(ctx, q.listAuditEventsFilteredStmt, listAuditEventsFiltered,
		arg.WorkspaceID,
		arg.Column2,
		arg.MethodKey,
		arg.Column4,
		arg.ActorID,
		arg.Column6,
		arg.OccurredAt,
		arg.Column8,
		arg.OccurredAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlAuditEvent
	for rows.Next() {
		var i ControlAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.MethodKey,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeData,
			&i.AfterData,
			&i.Result,
			&i.RequestID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentities = `-- name: ListIdentities :many
SELECT account_id, provider, provider_subject, payload, created_at, updated_at
FROM control_identity WHERE account_id = ? ORDER BY provider
`

func (q *Queries) ListIdentities(ctx context.Context, accountID string) ([]ControlIdentity, error) {
	rows, err := q.query(ctx, q.listIdentitiesStmt, listIdentities, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlIdentity
	for rows.Next() {
		var i ControlIdentity
		if err := rows.Scan(
			&i.AccountID,
			&i.Provider,
			&i.ProviderSubject,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInviteRoles = `-- name: ListInviteRoles :many
SELECT role_id FROM control_workspace_invite_role WHERE invite_id = ? ORDER BY role_id
`

func (q *Queries) ListInviteRoles(ctx context.Context, inviteID string) ([]string, error) {
	rows, err := q.query(ctx, q.listInviteRolesStmt, listInviteRoles, inviteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, workspace_id, created_by, token_hash, max_uses, used_count, expires_at, revoked_at, created_at
FROM control_workspace_invite WHERE workspace_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListInvitesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]ControlWorkspaceInvite, error) {
	rows, err := q.query(ctx, q.listInvitesStmt, listInvites, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlWorkspaceInvite
	for rows.Next() {
		var i ControlWorkspaceInvite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.TokenHash,
			&i.MaxUses,
			&i.UsedCount,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMethods = `-- name: ListMethods :many
SELECT method_key, service, group_key, title, workspace_scoped, is_sensitive, schema_revision, status, created_at, updated_at
FROM control_method WHERE status = 'active' ORDER BY service, group_key, method_key
`

func (q *Queries) ListMethods(ctx context.Context) ([]ControlMethod, error) {
	rows, err := q.query(ctx, q.listMethodsStmt, listMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlMethod
	for rows.Next() {
		var i ControlMethod
		if err := rows.Scan(
			&i.MethodKey,
			&i.Service,
			&i.GroupKey,
			&i.Title,
			&i.WorkspaceScoped,
			&i.IsSensitive,
			&i.SchemaRevision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT p.role_id, p.method_key, p.created_at
FROM control_role_permission p
JOIN control_role r ON r.id = p.role_id
WHERE r.workspace_id = ? AND p.role_id = ? AND r.deleted_at IS NULL
ORDER BY p.method_key
`

type ListRolePermissionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	RoleID      string `json:"role_id"`
}

func (q *Queries) ListRolePermissions(ctx context.Context, arg ListRolePermissionsParams) ([]ControlRolePermission, error) {
	rows, err := q.query(ctx, q.listRolePermissionsStmt, listRolePermissions, arg.WorkspaceID, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRolePermission
	for rows.Next() {
		var i ControlRolePermission
		if err := rows.Scan(&i.RoleID, &i.MethodKey, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT r.id, r.workspace_id, r.code, r.title, r.description, r.position, r.is_owner, r.deleted_at, r.created_at, r.updated_at,
       COUNT(rm.account_id) AS member_count
FROM control_role r
LEFT JOIN control_role_member rm ON rm.role_id = r.id
WHERE r.workspace_id = ? AND r.deleted_at IS NULL
GROUP BY r.id
ORDER BY r.position, r.id
`

type ListRolesRow struct {
	ID          string       `json:"id"`
	WorkspaceID string       `json:"workspace_id"`
	Code        string       `json:"code"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Position    int32        `json:"position"`
	IsOwner     bool         `json:"is_owner"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	MemberCount int64        `json:"member_count"`
}

func (q *Queries) ListRoles(ctx context.Context, workspaceID string) ([]ListRolesRow, error) {
	rows, err := q.query(ctx, q.listRolesStmt, listRoles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.IsOwner,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, account_id, token_hash, ip, user_agent, bind_to_ip, expires_at, revoked_at, last_used_at, created_at
FROM control_session WHERE account_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context, accountID string) ([]ControlSession, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlSession
	for rows.Next() {
		var i ControlSession
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.Ip,
			&i.UserAgent,
			&i.BindToIp,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT m.workspace_id, m.account_id, m.status, m.joined_at, m.updated_at,
       a.display_name, COALESCE(MIN(r.position), 2147483647) AS position
FROM control_workspace_member m
JOIN control_account a ON a.id = m.account_id
LEFT JOIN control_role_member rm ON rm.account_id = m.account_id
LEFT JOIN control_role r ON r.id = rm.role_id AND r.workspace_id = m.workspace_id AND r.deleted_at IS NULL
WHERE m.workspace_id = ? AND m.status = 'active'
GROUP BY m.workspace_id, m.account_id, m.status, m.joined_at, m.updated_at, a.display_name
ORDER BY position, m.joined_at
LIMIT ? OFFSET ?
`

type ListWorkspaceMembersParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListWorkspaceMembersRow struct {
	WorkspaceID string                       `json:"workspace_id"`
	AccountID   string                       `json:"account_id"`
	Status      ControlWorkspaceMemberStatus `json:"status"`
	JoinedAt    time.Time                    `json:"joined_at"`
	UpdatedAt   time.Time                    `json:"updated_at"`
	DisplayName string                       `json:"display_name"`
	Position    interface{}                  `json:"position"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, arg ListWorkspaceMembersParams) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.query(ctx, q.listWorkspaceMembersStmt, listWorkspaceMembers, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersRow
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.AccountID,
			&i.Status,
			&i.JoinedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForAccount = `-- name: ListWorkspacesForAccount :many
SELECT w.id, w.slug, w.title, w.status, w.created_by, w.created_at, w.updated_at
FROM control_workspace w
JOIN control_workspace_member m ON m.workspace_id = w.id
WHERE m.account_id = ? AND m.status = 'active'
ORDER BY w.created_at DESC LIMIT ? OFFSET ?
`

type ListWorkspacesForAccountParams struct {
	AccountID string `json:"account_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListWorkspacesForAccount(ctx context.Context, arg ListWorkspacesForAccountParams) ([]ControlWorkspace, error) {
	rows, err := q.query(ctx, q.listWorkspacesForAccountStmt, listWorkspacesForAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlWorkspace
	for rows.Next() {
		var i ControlWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleMember = `-- name: RemoveRoleMember :execrows
DELETE FROM control_role_member WHERE role_id = ? AND account_id = ?
`

type RemoveRoleMemberParams struct {
	RoleID    string `json:"role_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) RemoveRoleMember(ctx context.Context, arg RemoveRoleMemberParams) (int64, error) {
	result, err := q.exec(ctx, q.removeRoleMemberStmt, removeRoleMember, arg.RoleID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :execrows
UPDATE control_workspace_member SET status = 'removed'
WHERE workspace_id = ? AND account_id = ? AND status = 'active'
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (int64, error) {
	result, err := q.exec(ctx, q.removeWorkspaceMemberStmt, removeWorkspaceMember, arg.WorkspaceID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeWorkspaceMemberRoles = `-- name: RemoveWorkspaceMemberRoles :execrows
DELETE rm
FROM control_role_member rm
JOIN control_role r ON r.id = rm.role_id
WHERE r.workspace_id = ? AND rm.account_id = ?
`

type RemoveWorkspaceMemberRolesParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) RemoveWorkspaceMemberRoles(ctx context.Context, arg RemoveWorkspaceMemberRolesParams) (int64, error) {
	result, err := q.exec(ctx, q.removeWorkspaceMemberRolesStmt, removeWorkspaceMemberRoles, arg.WorkspaceID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAllSessions = `-- name: RevokeAllSessions :execrows
UPDATE control_session SET revoked_at = NOW()
WHERE account_id = ? AND revoked_at IS NULL AND (? = '' OR id <> ?)
`

type RevokeAllSessionsParams struct {
	AccountID string      `json:"account_id"`
	Column2   interface{} `json:"column_2"`
	ID        string      `json:"id"`
}

func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) (int64, error) {
	result, err := q.exec(ctx, q.revokeAllSessionsStmt, revokeAllSessions, arg.AccountID, arg.Column2, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE control_workspace_invite SET revoked_at = NOW()
WHERE id = ? AND workspace_id = ? AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.exec(ctx, q.revokeInviteStmt, revokeInvite, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE control_session SET revoked_at = NOW()
WHERE id = ? AND account_id = ? AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.exec(ctx, q.revokeSessionStmt, revokeSession, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRolePermission = `-- name: SetRolePermission :exec
INSERT IGNORE INTO control_role_permission (role_id, method_key) VALUES (?, ?)
`

type SetRolePermissionParams struct {
	RoleID    string `json:"role_id"`
	MethodKey string `json:"method_key"`
}

func (q *Queries) SetRolePermission(ctx context.Context, arg SetRolePermissionParams) error {
	_, err := q.exec(ctx, q.setRolePermissionStmt, setRolePermission, arg.RoleID, arg.MethodKey)
	return err
}

const touchAuthVersion = `-- name: TouchAuthVersion :exec
INSERT INTO control_workspace_auth_version (workspace_id, version)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE version = VALUES(version)
`

type TouchAuthVersionParams struct {
	WorkspaceID string `json:"workspace_id"`
	Version     string `json:"version"`
}

func (q *Queries) TouchAuthVersion(ctx context.Context, arg TouchAuthVersionParams) error {
	_, err := q.exec(ctx, q.touchAuthVersionStmt, touchAuthVersion, arg.WorkspaceID, arg.Version)
	return err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE control_session SET last_used_at = NOW()
WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.touchSessionStmt, touchSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePendingTwoFactorBackupHashes = `-- name: UpdatePendingTwoFactorBackupHashes :execrows
UPDATE control_two_factor SET backup_hashes = ? WHERE account_id = ? AND activated_at IS NULL
`

type UpdatePendingTwoFactorBackupHashesParams struct {
	BackupHashes json.RawMessage `json:"backup_hashes"`
	AccountID    string          `json:"account_id"`
}

func (q *Queries) UpdatePendingTwoFactorBackupHashes(ctx context.Context, arg UpdatePendingTwoFactorBackupHashesParams) (int64, error) {
	result, err := q.exec(ctx, q.updatePendingTwoFactorBackupHashesStmt, updatePendingTwoFactorBackupHashes, arg.BackupHashes, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE control_role SET title = ?, description = ?, position = ?
WHERE id = ? AND workspace_id = ? AND deleted_at IS NULL AND is_owner = FALSE
`

type UpdateRoleParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Position    int32  `json:"position"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.exec(ctx, q.updateRoleStmt, updateRole,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.ID,
		arg.WorkspaceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTwoFactorBackupHashes = `-- name: UpdateTwoFactorBackupHashes :execrows
UPDATE control_two_factor SET backup_hashes = ? WHERE account_id = ? AND activated_at IS NOT NULL
`

type UpdateTwoFactorBackupHashesParams struct {
	BackupHashes json.RawMessage `json:"backup_hashes"`
	AccountID    string          `json:"account_id"`
}

func (q *Queries) UpdateTwoFactorBackupHashes(ctx context.Context, arg UpdateTwoFactorBackupHashesParams) (int64, error) {
	result, err := q.exec(ctx, q.updateTwoFactorBackupHashesStmt, updateTwoFactorBackupHashes, arg.BackupHashes, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspace = `-- name: UpdateWorkspace :execrows
UPDATE control_workspace SET slug = ?, title = ?, status = ? WHERE id = ?
`

type UpdateWorkspaceParams struct {
	Slug   string                 `json:"slug"`
	Title  string                 `json:"title"`
	Status ControlWorkspaceStatus `json:"status"`
	ID     string                 `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (int64, error) {
	result, err := q.exec(ctx, q.updateWorkspaceStmt, updateWorkspace,
		arg.Slug,
		arg.Title,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertIdentity = `-- name: UpsertIdentity :exec
INSERT INTO control_identity (account_id, provider, provider_subject, payload)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE provider_subject = VALUES(provider_subject), payload = VALUES(payload)
`

type UpsertIdentityParams struct {
	AccountID       string          `json:"account_id"`
	Provider        string          `json:"provider"`
	ProviderSubject string          `json:"provider_subject"`
	Payload         json.RawMessage `json:"payload"`
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) error {
	_, err := q.exec(ctx, q.upsertIdentityStmt, upsertIdentity,
		arg.AccountID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Payload,
	)
	return err
}

const upsertMethod = `-- name: UpsertMethod :exec
INSERT INTO control_method (method_key, service, group_key, title, workspace_scoped, is_sensitive, schema_revision, status)
VALUES (?, ?, ?, ?, ?, ?, ?, 'active')
ON DUPLICATE KEY UPDATE service = VALUES(service), group_key = VALUES(group_key), title = VALUES(title),
    workspace_scoped = VALUES(workspace_scoped), is_sensitive = VALUES(is_sensitive), schema_revision = VALUES(schema_revision), status = 'active'
`

type UpsertMethodParams struct {
	MethodKey       string `json:"method_key"`
	Service         string `json:"service"`
	GroupKey        string `json:"group_key"`
	Title           string `json:"title"`
	WorkspaceScoped bool   `json:"workspace_scoped"`
	IsSensitive     bool   `json:"is_sensitive"`
	SchemaRevision  uint32 `json:"schema_revision"`
}

func (q *Queries) UpsertMethod(ctx context.Context, arg UpsertMethodParams) error {
	_, err := q.exec(ctx, q.upsertMethodStmt, upsertMethod,
		arg.MethodKey,
		arg.Service,
		arg.GroupKey,
		arg.Title,
		arg.WorkspaceScoped,
		arg.IsSensitive,
		arg.SchemaRevision,
	)
	return err
}

const upsertTwoFactor = `-- name: UpsertTwoFactor :exec
INSERT INTO control_two_factor (account_id, secret, backup_hashes, activated_at)
VALUES (?, ?, ?, NULL)
ON DUPLICATE KEY UPDATE secret = VALUES(secret), backup_hashes = VALUES(backup_hashes), activated_at = NULL
`

type UpsertTwoFactorParams struct {
	AccountID    string          `json:"account_id"`
	Secret       string          `json:"secret"`
	BackupHashes json.RawMessage `json:"backup_hashes"`
}

func (q *Queries) UpsertTwoFactor(ctx context.Context, arg UpsertTwoFactorParams) error {
	_, err := q.exec(ctx, q.upsertTwoFactorStmt, upsertTwoFactor, arg.AccountID, arg.Secret, arg.BackupHashes)
	return err
}
