// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type PromoRewardDurationUnit string

const (
	PromoRewardDurationUnitSecond PromoRewardDurationUnit = "second"
	PromoRewardDurationUnitMinute PromoRewardDurationUnit = "minute"
	PromoRewardDurationUnitHour   PromoRewardDurationUnit = "hour"
	PromoRewardDurationUnitDay    PromoRewardDurationUnit = "day"
	PromoRewardDurationUnitWeek   PromoRewardDurationUnit = "week"
	PromoRewardDurationUnitMonth  PromoRewardDurationUnit = "month"
	PromoRewardDurationUnitYear   PromoRewardDurationUnit = "year"
)

func (e *PromoRewardDurationUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromoRewardDurationUnit(s)
	case string:
		*e = PromoRewardDurationUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for PromoRewardDurationUnit: %T", src)
	}
	return nil
}

type NullPromoRewardDurationUnit struct {
	PromoRewardDurationUnit PromoRewardDurationUnit `json:"promo_reward_duration_unit"`
	Valid                   bool                    `json:"valid"` // Valid is true if PromoRewardDurationUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromoRewardDurationUnit) Scan(value interface{}) error {
	if value == nil {
		ns.PromoRewardDurationUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromoRewardDurationUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromoRewardDurationUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromoRewardDurationUnit), nil
}

type PromoRewardRewardType string

const (
	PromoRewardRewardTypeQuantity PromoRewardRewardType = "quantity"
	PromoRewardRewardTypeDuration PromoRewardRewardType = "duration"
)

func (e *PromoRewardRewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromoRewardRewardType(s)
	case string:
		*e = PromoRewardRewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromoRewardRewardType: %T", src)
	}
	return nil
}

type NullPromoRewardRewardType struct {
	PromoRewardRewardType PromoRewardRewardType `json:"promo_reward_reward_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if PromoRewardRewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromoRewardRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.PromoRewardRewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromoRewardRewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromoRewardRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromoRewardRewardType), nil
}

type PromoLocalization struct {
	WorkspaceID string    `json:"workspace_id"`
	PromoID     uint64    `json:"promo_id"`
	Locale      string    `json:"locale"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PromoOffer struct {
	ID              uint64          `json:"id"`
	WorkspaceID     string          `json:"workspace_id"`
	Code            string          `json:"code"`
	CodeNormalized  string          `json:"code_normalized"`
	Payload         json.RawMessage `json:"payload"`
	Target          json.RawMessage `json:"target"`
	MaxActivations  uint64          `json:"max_activations"`
	ActivationCount uint64          `json:"activation_count"`
	IsActive        bool            `json:"is_active"`
	StartAt         sql.NullTime    `json:"start_at"`
	EndAt           sql.NullTime    `json:"end_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type PromoRedemption struct {
	ID             uint64          `json:"id"`
	WorkspaceID    string          `json:"workspace_id"`
	PromoID        uint64          `json:"promo_id"`
	AppID          int64           `json:"app_id"`
	PlatformID     int64           `json:"platform_id"`
	PlatformUserID string          `json:"platform_user_id"`
	RewardSnapshot json.RawMessage `json:"reward_snapshot"`
	RedeemedAt     time.Time       `json:"redeemed_at"`
	CreatedAt      time.Time       `json:"created_at"`
}

type PromoRedemptionEvent struct {
	ID           uint64    `json:"id"`
	WorkspaceID  string    `json:"workspace_id"`
	PromoID      uint64    `json:"promo_id"`
	RedemptionID uint64    `json:"redemption_id"`
	OccurredAt   time.Time `json:"occurred_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type PromoReward struct {
	ID           uint64                      `json:"id"`
	WorkspaceID  string                      `json:"workspace_id"`
	PromoID      uint64                      `json:"promo_id"`
	RewardKey    string                      `json:"reward_key"`
	RewardType   PromoRewardRewardType       `json:"reward_type"`
	Quantity     int64                       `json:"quantity"`
	Scale        uint16                      `json:"scale"`
	DurationUnit NullPromoRewardDurationUnit `json:"duration_unit"`
	CreatedAt    time.Time                   `json:"created_at"`
	UpdatedAt    time.Time                   `json:"updated_at"`
}

type PromoStatsDaily struct {
	WorkspaceID     string    `json:"workspace_id"`
	PromoID         uint64    `json:"promo_id"`
	StatsDate       time.Time `json:"stats_date"`
	RedemptionCount uint64    `json:"redemption_count"`
	UniqueUsers     uint64    `json:"unique_users"`
	UpdatedAt       time.Time `json:"updated_at"`
}
