// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const adminCreatePromo = `-- name: AdminCreatePromo :execlastid
INSERT INTO promo_offer (
    workspace_id, code, code_normalized, payload, max_activations,
    is_active, start_at, end_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AdminCreatePromoParams struct {
	WorkspaceID    string          `json:"workspace_id"`
	Code           string          `json:"code"`
	CodeNormalized string          `json:"code_normalized"`
	Payload        json.RawMessage `json:"payload"`
	MaxActivations uint64          `json:"max_activations"`
	IsActive       bool            `json:"is_active"`
	StartAt        sql.NullTime    `json:"start_at"`
	EndAt          sql.NullTime    `json:"end_at"`
}

func (q *Queries) AdminCreatePromo(ctx context.Context, arg AdminCreatePromoParams) (int64, error) {
	result, err := q.exec(ctx, q.adminCreatePromoStmt, adminCreatePromo,
		arg.WorkspaceID,
		arg.Code,
		arg.CodeNormalized,
		arg.Payload,
		arg.MaxActivations,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const adminDeleteLocalization = `-- name: AdminDeleteLocalization :execrows
DELETE FROM promo_localization
WHERE workspace_id = ? AND promo_id = ? AND locale = ?
`

type AdminDeleteLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     uint64 `json:"promo_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminDeleteLocalization(ctx context.Context, arg AdminDeleteLocalizationParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteLocalizationStmt, adminDeleteLocalization, arg.WorkspaceID, arg.PromoID, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteReward = `-- name: AdminDeleteReward :execrows
DELETE FROM promo_reward
WHERE workspace_id = ? AND promo_id = ? AND reward_key = ?
`

type AdminDeleteRewardParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     uint64 `json:"promo_id"`
	RewardKey   string `json:"reward_key"`
}

func (q *Queries) AdminDeleteReward(ctx context.Context, arg AdminDeleteRewardParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteRewardStmt, adminDeleteReward, arg.WorkspaceID, arg.PromoID, arg.RewardKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminGetLocalization = `-- name: AdminGetLocalization :one
SELECT workspace_id, promo_id, locale, title, description, created_at, updated_at
FROM promo_localization
WHERE workspace_id = ? AND promo_id = ? AND locale = ?
LIMIT 1
`

type AdminGetLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     uint64 `json:"promo_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminGetLocalization(ctx context.Context, arg AdminGetLocalizationParams) (PromoLocalization, error) {
	row := q.queryRow(ctx, q.adminGetLocalizationStmt, adminGetLocalization, arg.WorkspaceID, arg.PromoID, arg.Locale)
	var i PromoLocalization
	err := row.Scan(
		&i.WorkspaceID,
		&i.PromoID,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetPromo = `-- name: AdminGetPromo :one
SELECT id, workspace_id, code, code_normalized, payload, max_activations, activation_count, is_active, start_at, end_at, deleted_at, created_at, updated_at
FROM promo_offer
WHERE workspace_id = ? AND id = ?
LIMIT 1
`

type AdminGetPromoParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) AdminGetPromo(ctx context.Context, arg AdminGetPromoParams) (PromoOffer, error) {
	row := q.queryRow(ctx, q.adminGetPromoStmt, adminGetPromo, arg.WorkspaceID, arg.ID)
	var i PromoOffer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.CodeNormalized,
		&i.Payload,
		&i.MaxActivations,
		&i.ActivationCount,
		&i.IsActive,
		&i.StartAt,
		&i.EndAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetReward = `-- name: AdminGetReward :one
SELECT id, workspace_id, promo_id, reward_key, reward_type, quantity, duration_unit, created_at, updated_at
FROM promo_reward
WHERE workspace_id = ? AND promo_id = ? AND reward_key = ?
LIMIT 1
`

type AdminGetRewardParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     uint64 `json:"promo_id"`
	RewardKey   string `json:"reward_key"`
}

func (q *Queries) AdminGetReward(ctx context.Context, arg AdminGetRewardParams) (PromoReward, error) {
	row := q.queryRow(ctx, q.adminGetRewardStmt, adminGetReward, arg.WorkspaceID, arg.PromoID, arg.RewardKey)
	var i PromoReward
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PromoID,
		&i.RewardKey,
		&i.RewardType,
		&i.Quantity,
		&i.DurationUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetStats = `-- name: AdminGetStats :one
SELECT
    activation_count,
    max_activations,
    CASE
        WHEN max_activations = 0 THEN -1
        ELSE CAST(max_activations - activation_count AS SIGNED)
    END AS remaining_activations
FROM promo_offer
WHERE workspace_id = ? AND id = ?
LIMIT 1
`

type AdminGetStatsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          uint64 `json:"id"`
}

type AdminGetStatsRow struct {
	ActivationCount      uint64 `json:"activation_count"`
	MaxActivations       uint64 `json:"max_activations"`
	RemainingActivations int64  `json:"remaining_activations"`
}

func (q *Queries) AdminGetStats(ctx context.Context, arg AdminGetStatsParams) (AdminGetStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetStatsStmt, adminGetStats, arg.WorkspaceID, arg.ID)
	var i AdminGetStatsRow
	err := row.Scan(&i.ActivationCount, &i.MaxActivations, &i.RemainingActivations)
	return i, err
}

const adminListDailyStats = `-- name: AdminListDailyStats :many
SELECT workspace_id, promo_id, stats_date, redemption_count, unique_users, updated_at
FROM promo_stats_daily
WHERE workspace_id = ?
  AND promo_id = ?
  AND stats_date >= ?
  AND stats_date <= ?
ORDER BY stats_date
`

type AdminListDailyStatsParams struct {
	WorkspaceID string    `json:"workspace_id"`
	PromoID     uint64    `json:"promo_id"`
	StatsDate   time.Time `json:"stats_date"`
	StatsDate_2 time.Time `json:"stats_date_2"`
}

func (q *Queries) AdminListDailyStats(ctx context.Context, arg AdminListDailyStatsParams) ([]PromoStatsDaily, error) {
	rows, err := q.query(ctx, q.adminListDailyStatsStmt, adminListDailyStats,
		arg.WorkspaceID,
		arg.PromoID,
		arg.StatsDate,
		arg.StatsDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoStatsDaily
	for rows.Next() {
		var i PromoStatsDaily
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.PromoID,
			&i.StatsDate,
			&i.RedemptionCount,
			&i.UniqueUsers,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListLocalizations = `-- name: AdminListLocalizations :many
SELECT workspace_id, promo_id, locale, title, description, created_at, updated_at
FROM promo_localization
WHERE workspace_id = ? AND promo_id = ?
ORDER BY locale
`

type AdminListLocalizationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     uint64 `json:"promo_id"`
}

func (q *Queries) AdminListLocalizations(ctx context.Context, arg AdminListLocalizationsParams) ([]PromoLocalization, error) {
	rows, err := q.query(ctx, q.adminListLocalizationsStmt, adminListLocalizations, arg.WorkspaceID, arg.PromoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoLocalization
	for rows.Next() {
		var i PromoLocalization
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.PromoID,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPromos = `-- name: AdminListPromos :many
SELECT id, workspace_id, code, code_normalized, payload, max_activations, activation_count, is_active, start_at, end_at, deleted_at, created_at, updated_at
FROM promo_offer
WHERE workspace_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type AdminListPromosParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) AdminListPromos(ctx context.Context, arg AdminListPromosParams) ([]PromoOffer, error) {
	rows, err := q.query(ctx, q.adminListPromosStmt, adminListPromos, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoOffer
	for rows.Next() {
		var i PromoOffer
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.CodeNormalized,
			&i.Payload,
			&i.MaxActivations,
			&i.ActivationCount,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRedemptions = `-- name: AdminListRedemptions :many
SELECT id, workspace_id, promo_id, app_id, platform_id, platform_user_id, reward_snapshot, redeemed_at, created_at
FROM promo_redemption
WHERE workspace_id = ?
  AND promo_id = ?
ORDER BY redeemed_at DESC, id DESC
LIMIT ? OFFSET ?
`

type AdminListRedemptionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     uint64 `json:"promo_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) AdminListRedemptions(ctx context.Context, arg AdminListRedemptionsParams) ([]PromoRedemption, error) {
	rows, err := q.query(ctx, q.adminListRedemptionsStmt, adminListRedemptions,
		arg.WorkspaceID,
		arg.PromoID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoRedemption
	for rows.Next() {
		var i PromoRedemption
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PromoID,
			&i.AppID,
			&i.PlatformID,
			&i.PlatformUserID,
			&i.RewardSnapshot,
			&i.RedeemedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSoftDeletePromo = `-- name: AdminSoftDeletePromo :execrows
UPDATE promo_offer
SET deleted_at = NOW(), is_active = FALSE
WHERE workspace_id = ? AND id = ? AND deleted_at IS NULL
`

type AdminSoftDeletePromoParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          uint64 `json:"id"`
}

func (q *Queries) AdminSoftDeletePromo(ctx context.Context, arg AdminSoftDeletePromoParams) (int64, error) {
	result, err := q.exec(ctx, q.adminSoftDeletePromoStmt, adminSoftDeletePromo, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpdatePromo = `-- name: AdminUpdatePromo :execrows
UPDATE promo_offer
SET code = ?,
    code_normalized = ?,
    payload = ?,
    max_activations = ?,
    is_active = ?,
    start_at = ?,
    end_at = ?
WHERE workspace_id = ? AND id = ? AND deleted_at IS NULL
`

type AdminUpdatePromoParams struct {
	Code           string          `json:"code"`
	CodeNormalized string          `json:"code_normalized"`
	Payload        json.RawMessage `json:"payload"`
	MaxActivations uint64          `json:"max_activations"`
	IsActive       bool            `json:"is_active"`
	StartAt        sql.NullTime    `json:"start_at"`
	EndAt          sql.NullTime    `json:"end_at"`
	WorkspaceID    string          `json:"workspace_id"`
	ID             uint64          `json:"id"`
}

func (q *Queries) AdminUpdatePromo(ctx context.Context, arg AdminUpdatePromoParams) (int64, error) {
	result, err := q.exec(ctx, q.adminUpdatePromoStmt, adminUpdatePromo,
		arg.Code,
		arg.CodeNormalized,
		arg.Payload,
		arg.MaxActivations,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpsertLocalization = `-- name: AdminUpsertLocalization :exec
INSERT INTO promo_localization (
    workspace_id, promo_id, locale, title, description
) VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    description = VALUES(description)
`

type AdminUpsertLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     uint64 `json:"promo_id"`
	Locale      string `json:"locale"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) AdminUpsertLocalization(ctx context.Context, arg AdminUpsertLocalizationParams) error {
	_, err := q.exec(ctx, q.adminUpsertLocalizationStmt, adminUpsertLocalization,
		arg.WorkspaceID,
		arg.PromoID,
		arg.Locale,
		arg.Title,
		arg.Description,
	)
	return err
}

const adminUpsertReward = `-- name: AdminUpsertReward :exec
INSERT INTO promo_reward (
    workspace_id, promo_id, reward_key, reward_type, quantity, duration_unit
)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    reward_type = VALUES(reward_type),
    quantity = VALUES(quantity),
    duration_unit = VALUES(duration_unit)
`

type AdminUpsertRewardParams struct {
	WorkspaceID  string                      `json:"workspace_id"`
	PromoID      uint64                      `json:"promo_id"`
	RewardKey    string                      `json:"reward_key"`
	RewardType   PromoRewardRewardType       `json:"reward_type"`
	Quantity     int64                       `json:"quantity"`
	DurationUnit NullPromoRewardDurationUnit `json:"duration_unit"`
}

func (q *Queries) AdminUpsertReward(ctx context.Context, arg AdminUpsertRewardParams) error {
	_, err := q.exec(ctx, q.adminUpsertRewardStmt, adminUpsertReward,
		arg.WorkspaceID,
		arg.PromoID,
		arg.RewardKey,
		arg.RewardType,
		arg.Quantity,
		arg.DurationUnit,
	)
	return err
}

const createRedemption = `-- name: CreateRedemption :execlastid
INSERT INTO promo_redemption (
    workspace_id, promo_id, app_id, platform_id, platform_user_id,
    reward_snapshot
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateRedemptionParams struct {
	WorkspaceID    string          `json:"workspace_id"`
	PromoID        uint64          `json:"promo_id"`
	AppID          int64           `json:"app_id"`
	PlatformID     int64           `json:"platform_id"`
	PlatformUserID string          `json:"platform_user_id"`
	RewardSnapshot json.RawMessage `json:"reward_snapshot"`
}

func (q *Queries) CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (int64, error) {
	result, err := q.exec(ctx, q.createRedemptionStmt, createRedemption,
		arg.WorkspaceID,
		arg.PromoID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.RewardSnapshot,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getApplyBundleForUpdate = `-- name: GetApplyBundleForUpdate :many
SELECT
    o.id,
    o.workspace_id,
    o.code,
    o.payload,
    o.max_activations,
    o.activation_count,
    o.is_active,
    o.start_at,
    o.end_at,
    o.deleted_at,
    o.created_at,
    o.updated_at,
    l.locale AS localization_locale,
    l.title AS localization_title,
    l.description AS localization_description,
    a.id AS redemption_id,
    a.app_id AS redemption_app_id,
    a.platform_id AS redemption_platform_id,
    a.platform_user_id AS redemption_platform_user_id,
    a.redeemed_at AS redemption_redeemed_at,
    r.id AS reward_id,
    r.reward_key,
    r.reward_type,
    r.quantity AS reward_quantity,
    r.duration_unit
FROM promo_offer o
LEFT JOIN promo_localization l
  ON l.workspace_id = o.workspace_id
 AND l.promo_id = o.id
 AND l.locale = ?
LEFT JOIN promo_redemption a
  ON a.workspace_id = o.workspace_id
 AND a.promo_id = o.id
 AND a.app_id = ?
 AND a.platform_id = ?
 AND a.platform_user_id = ?
LEFT JOIN promo_reward r
  ON r.workspace_id = o.workspace_id
 AND r.promo_id = o.id
WHERE o.workspace_id = ?
  AND o.code_normalized = ?
ORDER BY r.id
FOR UPDATE
`

type GetApplyBundleForUpdateParams struct {
	Locale         string `json:"locale"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
	WorkspaceID    string `json:"workspace_id"`
	CodeNormalized string `json:"code_normalized"`
}

type GetApplyBundleForUpdateRow struct {
	ID                       uint64                      `json:"id"`
	WorkspaceID              string                      `json:"workspace_id"`
	Code                     string                      `json:"code"`
	Payload                  json.RawMessage             `json:"payload"`
	MaxActivations           uint64                      `json:"max_activations"`
	ActivationCount          uint64                      `json:"activation_count"`
	IsActive                 bool                        `json:"is_active"`
	StartAt                  sql.NullTime                `json:"start_at"`
	EndAt                    sql.NullTime                `json:"end_at"`
	DeletedAt                sql.NullTime                `json:"deleted_at"`
	CreatedAt                time.Time                   `json:"created_at"`
	UpdatedAt                time.Time                   `json:"updated_at"`
	LocalizationLocale       sql.NullString              `json:"localization_locale"`
	LocalizationTitle        sql.NullString              `json:"localization_title"`
	LocalizationDescription  sql.NullString              `json:"localization_description"`
	RedemptionID             sql.NullInt64               `json:"redemption_id"`
	RedemptionAppID          sql.NullInt64               `json:"redemption_app_id"`
	RedemptionPlatformID     sql.NullInt64               `json:"redemption_platform_id"`
	RedemptionPlatformUserID sql.NullString              `json:"redemption_platform_user_id"`
	RedemptionRedeemedAt     sql.NullTime                `json:"redemption_redeemed_at"`
	RewardID                 sql.NullInt64               `json:"reward_id"`
	RewardKey                sql.NullString              `json:"reward_key"`
	RewardType               NullPromoRewardRewardType   `json:"reward_type"`
	RewardQuantity           sql.NullInt64               `json:"reward_quantity"`
	DurationUnit             NullPromoRewardDurationUnit `json:"duration_unit"`
}

func (q *Queries) GetApplyBundleForUpdate(ctx context.Context, arg GetApplyBundleForUpdateParams) ([]GetApplyBundleForUpdateRow, error) {
	rows, err := q.query(ctx, q.getApplyBundleForUpdateStmt, getApplyBundleForUpdate,
		arg.Locale,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.WorkspaceID,
		arg.CodeNormalized,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplyBundleForUpdateRow
	for rows.Next() {
		var i GetApplyBundleForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.Payload,
			&i.MaxActivations,
			&i.ActivationCount,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocalizationLocale,
			&i.LocalizationTitle,
			&i.LocalizationDescription,
			&i.RedemptionID,
			&i.RedemptionAppID,
			&i.RedemptionPlatformID,
			&i.RedemptionPlatformUserID,
			&i.RedemptionRedeemedAt,
			&i.RewardID,
			&i.RewardKey,
			&i.RewardType,
			&i.RewardQuantity,
			&i.DurationUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedemption = `-- name: GetRedemption :one
SELECT id, workspace_id, promo_id, app_id, platform_id, platform_user_id, reward_snapshot, redeemed_at, created_at
FROM promo_redemption
WHERE workspace_id = ?
  AND promo_id = ?
  AND app_id = ?
  AND platform_id = ?
  AND platform_user_id = ?
LIMIT 1
`

type GetRedemptionParams struct {
	WorkspaceID    string `json:"workspace_id"`
	PromoID        uint64 `json:"promo_id"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) GetRedemption(ctx context.Context, arg GetRedemptionParams) (PromoRedemption, error) {
	row := q.queryRow(ctx, q.getRedemptionStmt, getRedemption,
		arg.WorkspaceID,
		arg.PromoID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
	)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PromoID,
		&i.AppID,
		&i.PlatformID,
		&i.PlatformUserID,
		&i.RewardSnapshot,
		&i.RedeemedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRewards = `-- name: ListRewards :many
SELECT id, workspace_id, promo_id, reward_key, reward_type, quantity, duration_unit, created_at, updated_at
FROM promo_reward
WHERE workspace_id = ? AND promo_id = ?
ORDER BY id
`

type ListRewardsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     uint64 `json:"promo_id"`
}

func (q *Queries) ListRewards(ctx context.Context, arg ListRewardsParams) ([]PromoReward, error) {
	rows, err := q.query(ctx, q.listRewardsStmt, listRewards, arg.WorkspaceID, arg.PromoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoReward
	for rows.Next() {
		var i PromoReward
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PromoID,
			&i.RewardKey,
			&i.RewardType,
			&i.Quantity,
			&i.DurationUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshDailyStats = `-- name: RefreshDailyStats :exec
INSERT INTO promo_stats_daily (
    workspace_id, promo_id, stats_date, redemption_count, unique_users
)
SELECT
    e.workspace_id,
    e.promo_id,
    DATE(e.occurred_at),
    COUNT(*),
    COUNT(DISTINCT CONCAT_WS(':', r.app_id, r.platform_id, r.platform_user_id))
FROM promo_redemption_event e
JOIN promo_redemption r
  ON r.workspace_id = e.workspace_id
 AND r.promo_id = e.promo_id
 AND r.id = e.redemption_id
WHERE e.occurred_at >= ? AND e.occurred_at < ?
GROUP BY e.workspace_id, e.promo_id, DATE(e.occurred_at)
ON DUPLICATE KEY UPDATE
    redemption_count = VALUES(redemption_count),
    unique_users = VALUES(unique_users),
    updated_at = NOW()
`

type RefreshDailyStatsParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

func (q *Queries) RefreshDailyStats(ctx context.Context, arg RefreshDailyStatsParams) error {
	_, err := q.exec(ctx, q.refreshDailyStatsStmt, refreshDailyStats, arg.OccurredAt, arg.OccurredAt_2)
	return err
}
